//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AGAccessorySettingDelegate-Protocol.h"
#import "MediaServiceUpdatedDelegate-Protocol.h"

@class CMSHomeManager, MediaServiceConfiguration, NSString;
@protocol CMSMediaServiceChangedDelegate;

@interface CMSSettingsManager : NSObject <MediaServiceUpdatedDelegate, AGAccessorySettingDelegate>
{
    id <CMSMediaServiceChangedDelegate> _serviceChangedDelegate;	// 8 = 0x8
    CMSHomeManager *_homeManager;	// 16 = 0x10
    MediaServiceConfiguration *_serviceConfig;	// 24 = 0x18
}

+ (_Bool)allowExplicitContentHomeKitValue;	// IMP=0x0000000100006d94
+ (_Bool)updateListeningHistoryHomeKitValue;	// IMP=0x0000000100006d0c
+ (_Bool)listeningHistorySettingForService:(id)arg1 user:(id)arg2;	// IMP=0x0000000100006b7c
+ (id)sharedManager;	// IMP=0x00000001000066d0
- (void).cxx_destruct;	// IMP=0x0000000100007f68
@property(retain, nonatomic) MediaServiceConfiguration *serviceConfig; // @synthesize serviceConfig=_serviceConfig;
@property(retain, nonatomic) CMSHomeManager *homeManager; // @synthesize homeManager=_homeManager;
@property(nonatomic) __weak id <CMSMediaServiceChangedDelegate> serviceChangedDelegate; // @synthesize serviceChangedDelegate=_serviceChangedDelegate;
- (void)accessorySettingDidUpdate:(id)arg1;	// IMP=0x0000000100007a94
- (id)_settingsObject:(_Bool)arg1;	// IMP=0x0000000100007a54
- (void)connectionInvalidated;	// IMP=0x00000001000079d0
- (void)connectionInterrupted;	// IMP=0x000000010000794c
- (void)userDidRemoveService:(id)arg1 homeUserID:(id)arg2;	// IMP=0x00000001000074e8
- (void)serviceSettingDidUpdate:(id)arg1 homeUserID:(id)arg2;	// IMP=0x0000000100006e1c
- (void)_initializeHomePodPlaybackConstraints;	// IMP=0x0000000100006940
- (id)init;	// IMP=0x0000000100006770

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

