//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class TVAirPlayAPRKVideoSession;

@interface TVAirPlayAPRKViewController : UIViewController
{
    TVAirPlayAPRKVideoSession *_videoSession;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010001905c
@property(retain, nonatomic) TVAirPlayAPRKVideoSession *videoSession; // @synthesize videoSession=_videoSession;
- (void)viewDidLoad;	// IMP=0x0000000100018ce4
- (id)initWithVideoSession:(id)arg1;	// IMP=0x0000000100018c5c

@end

