//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVPlayback/TVPURLMediaItem.h>

#import "TVAirPlayResourceLoadingMediaItem-Protocol.h"

@class NSString;
@protocol TVAirPlayResourceLoadingMediaItemDelegate;

@interface TVAirPlayMediaItem : TVPURLMediaItem <TVAirPlayResourceLoadingMediaItem>
{
    id <TVAirPlayResourceLoadingMediaItemDelegate> _resourceLoadingDelegate;	// 8 = 0x8
}

+ (id)sslPropertiesForIdentity:(id)arg1 psk:(id)arg2;	// IMP=0x000000010001884c
- (void).cxx_destruct;	// IMP=0x00000001000189b0
@property(nonatomic) __weak id <TVAirPlayResourceLoadingMediaItemDelegate> resourceLoadingDelegate; // @synthesize resourceLoadingDelegate=_resourceLoadingDelegate;
- (_Bool)hasTrait:(id)arg1;	// IMP=0x00000001000187c8
- (void)loadStreamingKeyForRequest:(id)arg1;	// IMP=0x0000000100018760

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

