//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSAudioFileManager : NSObject
{
}

+ (id)audioFileWriterForAttentiveSiri;	// IMP=0x0000000100015b98
+ (void)cleanupOrphanedGradingFiles;	// IMP=0x000000010001550c
+ (void)pruneNumberOfGradingFilesTo:(unsigned long long)arg1;	// IMP=0x00000001000153e8
+ (void)pruneNumberOfLogFilesTo:(unsigned long long)arg1;	// IMP=0x0000000100014ec0
+ (void)pruneLogFiles;	// IMP=0x0000000100014e04
+ (void)removeLogFilesOlderThanNDays:(float)arg1;	// IMP=0x0000000100014c8c
+ (id)_getDateLabel;	// IMP=0x0000000100014bbc
+ (id)_createAudioFileWriterForPHSTrainingWithLoggingDir:(id)arg1 inputFormat:(struct AudioStreamBasicDescription)arg2 outputFormat:(struct AudioStreamBasicDescription)arg3;	// IMP=0x00000001000149f0
+ (id)_createAudioFileWriterWithLoggingDir:(id)arg1 withLoggingUUID:(id)arg2 inputFormat:(struct AudioStreamBasicDescription)arg3 outputFormat:(struct AudioStreamBasicDescription)arg4;	// IMP=0x000000010001483c
+ (id)_createAudioFileWriterForOpportuneSpeakListenerWithLoggingDir:(id)arg1 inputFormat:(struct AudioStreamBasicDescription)arg2 outputFormat:(struct AudioStreamBasicDescription)arg3;	// IMP=0x000000010001465c
+ (id)_createAudioFileWriterForAdBlockerWithLoggingDir:(id)arg1 inputFormat:(struct AudioStreamBasicDescription)arg2 outputFormat:(struct AudioStreamBasicDescription)arg3;	// IMP=0x000000010001447c
+ (id)createAudioFileWriterForAdBlockerWithInputFormat:(struct AudioStreamBasicDescription)arg1 outputFormat:(struct AudioStreamBasicDescription)arg2;	// IMP=0x0000000100014364
+ (id)createSelectiveChannelAudioFileWriterWithChannelBitset:(unsigned long long)arg1;	// IMP=0x00000001000140f0
+ (id)createAudioFileWriterWithInputFormat:(struct AudioStreamBasicDescription)arg1 outputFormat:(struct AudioStreamBasicDescription)arg2 withLoggingUUID:(id)arg3;	// IMP=0x0000000100013f70
+ (id)createAudioFileWriterForRemoteVADWithInputFormat:(struct AudioStreamBasicDescription)arg1 outputFormat:(struct AudioStreamBasicDescription)arg2 withLoggingUUID:(id)arg3;	// IMP=0x0000000100013e3c
+ (id)createAudioFileWriterForPHSTrainingWithInputFormat:(struct AudioStreamBasicDescription)arg1 outputFormat:(struct AudioStreamBasicDescription)arg2;	// IMP=0x0000000100013d28
+ (id)createAudioFileWriterForOpportuneSpeakListenerWithInputFormat:(struct AudioStreamBasicDescription)arg1 outputFormat:(struct AudioStreamBasicDescription)arg2;	// IMP=0x0000000100013c14
+ (void)_readDataFromFileHandle:(id)arg1 toFileHandle:(id)arg2;	// IMP=0x0000000100013850
+ (void)generateDeviceAudioLogging:(id)arg1 speechId:(id)arg2;	// IMP=0x0000000100013160
+ (id)_sharedAudioLoggingQueue;	// IMP=0x00000001000130c4

@end

