//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface IDSLocalDeliveryQueue : NSObject
{
    NSMutableArray *_messages;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    NSMutableDictionary *_statistics;	// 24 = 0x18
    struct os_unfair_lock_s _statisticsLock;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001004b7be8
- (void)clearStats;	// IMP=0x00000001004b7814
- (id)statisticsForDataProtectionClass:(unsigned int)arg1;	// IMP=0x00000001004b771c
@property(readonly) NSDictionary *statistics;
- (void)_addStatsFromDict:(id)arg1 toAggregate:(id)arg2;	// IMP=0x00000001004b6d78
- (void)_removeMessageFromStatistics:(id)arg1;	// IMP=0x00000001004b6658
- (void)_addMessageToStatistics:(id)arg1;	// IMP=0x00000001004b6130
- (id)nextSocketPairMessageNotOnServices:(id)arg1;	// IMP=0x00000001004b5820
- (void)dequeueMessage:(id)arg1;	// IMP=0x00000001004b5574
- (void)enqueueMessage:(id)arg1;	// IMP=0x00000001004b4fec
- (void)pushMessage:(id)arg1;	// IMP=0x00000001004b4d14
- (void)removeMessages:(id)arg1;	// IMP=0x00000001004b4cac
- (unsigned long long)countForDataMessageType:(long long)arg1;	// IMP=0x00000001004b4b64
- (unsigned long long)countForDataProtectionClass:(unsigned int)arg1;	// IMP=0x00000001004b4a1c
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *messages;
- (void)dealloc;	// IMP=0x00000001004b48d0
- (id)initWithIdentifier:(id)arg1;	// IMP=0x00000001004b47c0

@end

