//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GeoServices/GEOServer.h>

@interface GEODirectionsServer : GEOServer
{
}

+ (id)identifier;	// IMP=0x00000001000109f4
- (void)cancelWithMessage:(id)arg1;	// IMP=0x0000000100008c6c
- (void)startWithMessage:(id)arg1;	// IMP=0x0000000100008718
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3;	// IMP=0x0000000100010a00

@end

