//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GeoServices/GEOServer.h>

@interface GEOWiFiQualityServiceServer : GEOServer
{
}

+ (id)identifier;	// IMP=0x0000000100013004
- (void)cancelWithMessage:(id)arg1;	// IMP=0x000000010002b1e8
- (void)tileWithMessage:(id)arg1;	// IMP=0x000000010002ae44
- (void)submitWithMessage:(id)arg1;	// IMP=0x000000010002aac4
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3;	// IMP=0x0000000100013010

@end

