//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface AccountVirtualCardStatusUpdate : SQLiteEntity
{
}

+ (id)_propertySettersForAccountVirtualCardStatusUpdate;	// IMP=0x00000001000871a0
+ (id)_predicateForEventPID:(long long)arg1;	// IMP=0x000000010008712c
+ (id)databaseTable;	// IMP=0x0000000100087120
+ (void)deleteVirtualCardStatusUpdatesWithEventPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x0000000100086fe4
+ (id)insertVirtualCardStatusUpdate:(id)arg1 forEventPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x0000000100086c34
+ (id)virtualCardStatusUpdatesWithEventPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00000001000869ec
- (_Bool)deleteFromDatabase;	// IMP=0x0000000100087084
- (id)virtualCardStatusUpdate;	// IMP=0x0000000100086dec

@end

