//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDUserNotification.h"

#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface PDAccountPaymentPastDueUserNotification : PDUserNotification <NSSecureCoding>
{
    _Bool _useGenericMessaging;	// 96 = 0x60
    NSString *_accountIdentifier;	// 104 = 0x68
    unsigned long long _featureIdentifier;	// 112 = 0x70
    long long _variant;	// 120 = 0x78
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010014e658
- (void).cxx_destruct;	// IMP=0x000000010014ed38
@property(nonatomic) long long variant; // @synthesize variant=_variant;
@property(readonly, nonatomic) unsigned long long featureIdentifier; // @synthesize featureIdentifier=_featureIdentifier;
@property(readonly, nonatomic) _Bool useGenericMessaging; // @synthesize useGenericMessaging=_useGenericMessaging;
@property(readonly, nonatomic) NSString *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x000000010014eb74
- (_Bool)needsNotificationSettings;	// IMP=0x000000010014eb6c
- (unsigned long long)notificationType;	// IMP=0x000000010014eb64
- (_Bool)isValid;	// IMP=0x000000010014eae8
- (id)_title;	// IMP=0x000000010014ea9c
- (id)_messageString;	// IMP=0x000000010014e944
- (long long)_variantForDay:(long long)arg1 cycle:(long long)arg2;	// IMP=0x000000010014e874
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010014e780
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010014e660
- (void)_updateForNextPastDueNotificationForAccount:(id)arg1;	// IMP=0x000000010014df44
- (id)initWithPassUniqueIdentifier:(id)arg1 account:(id)arg2;	// IMP=0x000000010014dd58

@end

