//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDNetworkConnectionTask.h"

@class NSString, NSURL;

@interface PDBarcodeServiceConnectionTask : PDNetworkConnectionTask
{
    NSURL *_barcodeServiceURL;	// 8 = 0x8
    NSString *_passUniqueIdentifier;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001000c6314
- (void).cxx_destruct;	// IMP=0x00000001000c7010
@property(copy, nonatomic) NSString *passUniqueIdentifier; // @synthesize passUniqueIdentifier=_passUniqueIdentifier;
@property(copy, nonatomic) NSURL *barcodeServiceURL; // @synthesize barcodeServiceURL=_barcodeServiceURL;
- (_Bool)isValid;	// IMP=0x00000001000c6fc0
- (void)handleResponse:(id)arg1 data:(id)arg2;	// IMP=0x00000001000c6dec
- (id)request;	// IMP=0x00000001000c65ac
- (unsigned long long)numberOfBackoffLevels;	// IMP=0x00000001000c659c
- (const CDStruct_316206b0 *)backoffLevels;	// IMP=0x00000001000c6590
- (id)bodyDictionary;	// IMP=0x00000001000c6588
- (id)headerFields;	// IMP=0x00000001000c64dc
- (id)queryFields;	// IMP=0x00000001000c64d4
- (id)endpointComponents;	// IMP=0x00000001000c64cc
- (id)method;	// IMP=0x00000001000c64c4
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000c6418
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000c631c

@end

