//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface PDCloudStoreCounterpartRecordParserIdentifiers : NSObject
{
    NSMutableDictionary *_identifierToParserZones;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010023e20c
- (id)description;	// IMP=0x000000010023e1fc
- (void)removeIdentifiers:(id)arg1;	// IMP=0x000000010023e0dc
- (id)allRecords;	// IMP=0x000000010023dfc8
- (id)allRecordsWithIdentifier:(id)arg1;	// IMP=0x000000010023defc
- (void)addRecord:(id)arg1 identifier:(id)arg2;	// IMP=0x000000010023de48
- (void)enumerateKeysAndObjectsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010023de38
- (id)init;	// IMP=0x000000010023ddd4

@end

