//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface PDObjectSettingsManager : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    int _needsArchive;	// 12 = 0xc
    NSMutableDictionary *_objectSettings;	// 16 = 0x10
}

+ (void)removeSafehavenArchive;	// IMP=0x000000010024bd14
+ (id)archive;	// IMP=0x000000010024b8d8
+ (id)archiveWithURL:(id)arg1;	// IMP=0x000000010024c2d0
- (void).cxx_destruct;	// IMP=0x000000010024bf58
- (id)_objectSettings;	// IMP=0x000000010024bf10
- (void)_requestArchiveToDisk;	// IMP=0x000000010024bd18
- (id)uniqueIdentifiers;	// IMP=0x000000010024bcc4
- (void)removeSettingsForObjectWithUniqueIdentifier:(id)arg1;	// IMP=0x000000010024bc58
- (void)updateSettings:(unsigned long long)arg1 forObjectWithUniqueIdentifier:(id)arg2 defaultSettings:(unsigned long long)arg3;	// IMP=0x000000010024bb68
- (_Bool)settingEnabled:(unsigned long long)arg1 forObjectWithUniqueIdentifier:(id)arg2 defaultSettings:(unsigned long long)arg3;	// IMP=0x000000010024bb30
- (unsigned long long)settingsForObjectWithUniqueIdentifier:(id)arg1 defaultSettings:(unsigned long long)arg2;	// IMP=0x000000010024ba9c
- (_Bool)hasSettingsForObjectWithUniqueIdentifier:(id)arg1;	// IMP=0x000000010024ba18
- (id)initWithObjectSettings:(id)arg1;	// IMP=0x000000010024b970
- (id)init;	// IMP=0x000000010024b960
- (unsigned long long)_defaultSettingsForObjectClass:(Class)arg1;	// IMP=0x000000010024c1a0
- (void)applySettingsToObject:(id)arg1;	// IMP=0x000000010024c140
- (void)updateSettings:(unsigned long long)arg1 forObject:(id)arg2;	// IMP=0x000000010024c0a4
- (_Bool)settingEnabled:(unsigned long long)arg1 forObject:(id)arg2;	// IMP=0x000000010024bffc
- (unsigned long long)settingsForObject:(id)arg1;	// IMP=0x000000010024bf64
- (unsigned long long)_defaultSettingsForDatabasePass:(id)arg1;	// IMP=0x000000010024c510
- (void)updateSettings:(unsigned long long)arg1 forDatabasePass:(id)arg2;	// IMP=0x000000010024c474
- (_Bool)settingEnabled:(unsigned long long)arg1 forDatabasePass:(id)arg2;	// IMP=0x000000010024c3cc
- (unsigned long long)settingsForDatabasePass:(id)arg1;	// IMP=0x000000010024c334

@end

