//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableSet, PDCardFileManager, PDDatabaseManager, PDFamilyCircleManager, PDPaymentWebServiceCoordinator, PDUserNotificationManager, PKSecureElement;
@protocol OS_dispatch_queue, OS_os_transaction;

@interface PDPushProvisioningManager : NSObject
{
    NSObject<OS_dispatch_queue> *_workQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_replyQueue;	// 16 = 0x10
    NSMutableSet *_availableSharingMetaData;	// 24 = 0x18
    _Bool _isUpdatingPushProvisioningSharingIdentifier;	// 32 = 0x20
    NSObject<OS_os_transaction> *_updatingPushProvisioningSharingIdentifierTransaction;	// 40 = 0x28
    NSMutableArray *_pendingPushProvisioningSharingIdentifierUpdateBlocks;	// 48 = 0x30
    PDDatabaseManager *_databaseManager;	// 56 = 0x38
    PDCardFileManager *_cardFileManager;	// 64 = 0x40
    PDPaymentWebServiceCoordinator *_webServiceCoordinator;	// 72 = 0x48
    PKSecureElement *_secureElement;	// 80 = 0x50
    PDUserNotificationManager *_userNotificationManager;	// 88 = 0x58
    PDFamilyCircleManager *_familyCircleManager;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x00000001000817d0
@property(retain, nonatomic) PDFamilyCircleManager *familyCircleManager; // @synthesize familyCircleManager=_familyCircleManager;
@property(retain, nonatomic) PDUserNotificationManager *userNotificationManager; // @synthesize userNotificationManager=_userNotificationManager;
@property(retain, nonatomic) PKSecureElement *secureElement; // @synthesize secureElement=_secureElement;
@property(retain, nonatomic) PDPaymentWebServiceCoordinator *webServiceCoordinator; // @synthesize webServiceCoordinator=_webServiceCoordinator;
@property(retain, nonatomic) PDCardFileManager *cardFileManager; // @synthesize cardFileManager=_cardFileManager;
@property(retain, nonatomic) PDDatabaseManager *databaseManager; // @synthesize databaseManager=_databaseManager;
- (id)_encryptProvisioningTarget:(id)arg1 devSigned:(_Bool)arg2 certificateChain:(id)arg3 error:(id *)arg4;	// IMP=0x00000001000814cc
- (void)redeemProvisioningSharingIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100080e38
- (void)redeemEncryptedProvisioningTarget:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100080744
- (void)prepareProvisioningTarget:(id)arg1 checkFamilyCircle:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010007f784
- (void)_redeemPushProvisioningSharingMetadata:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007ee3c
- (void)_queue_provisionAvailablePushProvisioningSharingIdentifiersWithCompletions:(id)arg1;	// IMP=0x000000010007e4e0
- (void)_queue_performProvisioningForNextProvisioningSharingIdentifierWithExistingTransaction:(id)arg1;	// IMP=0x000000010007e414
- (void)provisionAvailablePushProvisioningSharingIdentifiersWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007e2e8
- (void)_queue_insertOrUpdatePushProvisioningSharingMetadata:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007e180
- (void)pushProvisioningNoncesWithCredentialCount:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007dc1c
- (void)provideEncryptedPushProvisioningTarget:(id)arg1 sharingInstanceIdentifier:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010007da44
- (void)statusForShareableCredentials:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007d110
- (void)pushProvisioningSharingIdentifiers:(CDUnknownBlockType)arg1;	// IMP=0x000000010007cf38
- (void)isPushProvisioningSupportedForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007cb84
- (id)initWithDataBaseManager:(id)arg1 cardFileManager:(id)arg2 userNoticationManager:(id)arg3 paymentWebServiceCoordinator:(id)arg4 familyCircleManager:(id)arg5 secureElement:(id)arg6;	// IMP=0x000000010007c968

@end

