//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AKCAReporter.h"

@interface AKCATiburonInputUIReporter : AKCAReporter
{
}

- (void)_clearMutuallyExclusiveProperties:(_Bool)arg1;	// IMP=0x000000010001f75c
- (void)didComplete:(_Bool)arg1;	// IMP=0x000000010001f6f8
- (void)didModifyName:(_Bool)arg1;	// IMP=0x000000010001f69c
- (void)didSelectPasswordCredential:(_Bool)arg1;	// IMP=0x000000010001f62c
- (void)didSelectAppleID:(_Bool)arg1;	// IMP=0x000000010001f5bc
- (void)didSelectAnonymousEmail:(_Bool)arg1;	// IMP=0x000000010001f560
- (void)didShowAppleID:(_Bool)arg1;	// IMP=0x000000010001f504
- (void)setPasswordCredentialCount:(unsigned long long)arg1;	// IMP=0x000000010001f4a8
- (id)initWithRequestID:(id)arg1;	// IMP=0x000000010001f358

@end

