//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AKClient;

@interface AKSRPService : NSObject
{
    AKClient *_client;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010004de08
- (_Bool)_shouldClearCKForFailedMagicAuthWithError:(long long)arg1 authContextHelper:(id)arg2;	// IMP=0x000000010004dd40
- (void)_handleError:(struct __CFError *)arg1 withServerResponse:(id)arg2 context:(id)arg3 andCompletion:(CDUnknownBlockType)arg4;	// IMP=0x000000010004dae8
- (void)_doURLSwitchWithServerResponse:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010004d7bc
- (void)_reprovisionAnisetteWithServerResponse:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010004d3f8
- (void)_resyncAnisetteWithServerResponse:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010004d00c
- (id)_anisetteActionTargetForServerResponse:(id)arg1 andContext:(id)arg2;	// IMP=0x000000010004cf44
- (void)_parseFailedServerResponse:(id)arg1 withError:(struct __CFError *)arg2 context:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010004cc64
- (void)_continueSRPContractWithAuthURL:(id)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010004c9a8
- (void)performSRPContractWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010004c848
- (id)initWithClient:(id)arg1;	// IMP=0x000000010004c7d0

@end

