//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ADDeviceCircleManagerListening-Protocol.h"
#import "ADRapportLinkGenericMessageHandling-Protocol.h"
#import "ADRapportLinkListening-Protocol.h"
#import "ADRequestLifecycleListening-Protocol.h"
#import "AFContextSnapshotTransforming-Protocol.h"
#import "AFNotifyObserverDelegate-Protocol.h"

@class ADRapportLink, AFNotifyObserver, AFWatchdogTimer, NSDate, NSDictionary, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface ADDeviceProximityManager : NSObject <ADRapportLinkListening, ADRapportLinkGenericMessageHandling, ADDeviceCircleManagerListening, AFNotifyObserverDelegate, AFContextSnapshotTransforming, ADRequestLifecycleListening>
{
    NSMutableDictionary *_proximityObservations;	// 8 = 0x8
    NSMutableDictionary *_timersByDeviceIDPair;	// 16 = 0x10
    NSDictionary *_cachedAFProximityRelativeToLocalDevice;	// 24 = 0x18
    _Bool _localIsCollector;	// 32 = 0x20
    NSString *_localDeviceIDSIdentifier;	// 40 = 0x28
    ADRapportLink *_proximityDiscoveryLink;	// 48 = 0x30
    ADRapportLink *_messageLink;	// 56 = 0x38
    AFWatchdogTimer *_proximityScanningTimer;	// 64 = 0x40
    NSDate *_lastProximityScan;	// 72 = 0x48
    AFNotifyObserver *_heardVoiceTriggerObserver;	// 80 = 0x50
    AFNotifyObserver *_voiceTriggerFirstPassObserver;	// 88 = 0x58
    NSDate *_currentVoiceTriggerExpirationDate;	// 96 = 0x60
    NSObject<OS_dispatch_queue> *_queue;	// 104 = 0x68
}

+ (id)sharedManager;	// IMP=0x0000000100137e68
- (void).cxx_destruct;	// IMP=0x000000010013b8b4
- (void)_setMessageLink:(id)arg1;	// IMP=0x000000010013b8a8
- (id)_queue;	// IMP=0x000000010013b8a0
- (void)getRedactedContextForContextSnapshot:(id)arg1 metadata:(id)arg2 privacyPolicy:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010013b840
- (void)notifyObserver:(id)arg1 didReceiveNotificationWithToken:(int)arg2;	// IMP=0x000000010013b164
- (void)requestLifecycleObserver:(id)arg1 requestDidEndWithInfo:(id)arg2 origin:(long long)arg3 client:(id)arg4;	// IMP=0x000000010013b0b8
- (void)requestLifecycleObserver:(id)arg1 requestWasCancelledWithInfo:(id)arg2 origin:(long long)arg3 client:(id)arg4;	// IMP=0x000000010013b0b4
- (void)requestLifecycleObserver:(id)arg1 requestWillBeginWithInfo:(id)arg2 origin:(long long)arg3 client:(id)arg4;	// IMP=0x000000010013b0b0
- (void)contextCollectorChangedToDevicesWithIdentifiers:(id)arg1 localDeviceIsCollector:(_Bool)arg2;	// IMP=0x000000010013b044
- (void)rapportLink:(id)arg1 didReceiveMessage:(id)arg2 ofType:(id)arg3 fromDeviceWithIdentifier:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010013ad10
- (void)rapportLink:(id)arg1 didLoseDevice:(id)arg2;	// IMP=0x000000010013abbc
- (void)rapportLink:(id)arg1 didUpdateDevice:(id)arg2 changes:(unsigned int)arg3;	// IMP=0x000000010013ab28
- (void)rapportLink:(id)arg1 didFindDevice:(id)arg2;	// IMP=0x000000010013aa94
- (void)rapportLink:(id)arg1 didUpdateLocalDevice:(id)arg2;	// IMP=0x000000010013aa54
- (void)rapportLinkDidInvalidate:(id)arg1;	// IMP=0x000000010013a904
- (void)rapportLinkDidInterrupt:(id)arg1;	// IMP=0x000000010013a848
- (void)_fetchProximityObservationsFromCollectorsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010013a048
- (void)_pushProximityObservationToCollector:(id)arg1;	// IMP=0x0000000100139c3c
- (void)_recordProximityObservation:(id)arg1;	// IMP=0x000000010013986c
- (void)_insertProximityForRemoteDeviceID:(id)arg1 rpProximity:(int)arg2;	// IMP=0x0000000100139720
- (void)_updateProximityForDevice:(id)arg1;	// IMP=0x0000000100139660
- (void)_resetMessageLink;	// IMP=0x0000000100139614
- (void)_clearProximityDiscoveryLink;	// IMP=0x00000001001395e0
- (id)_proximityDiscoveryLink;	// IMP=0x000000010013940c
- (id)_messageLink;	// IMP=0x00000001001391d8
- (id)_rapportLinkMessageOptions;	// IMP=0x0000000100139154
- (void)_getAggregatedProximityObservationsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100138cf4
- (void)getDeviceProximityRelativeToLocalDeviceWithDeviceContexts:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001388fc
- (void)getDeviceProximityRelativeToLocalDeviceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100138758
- (void)_stopScanning;	// IMP=0x0000000100138474
- (void)performProximityScan;	// IMP=0x00000001001381f8
- (id)_init;	// IMP=0x0000000100137ee0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

