//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ADIntentPreferencesAndVocabularyUpdateService-Protocol.h"

@class NSString, _INVocabularyStoreManager;

@interface ADIntentVocabularyUpdateConnection : NSObject <ADIntentPreferencesAndVocabularyUpdateService>
{
    NSString *_appBundleID;	// 8 = 0x8
    NSString *_appPath;	// 16 = 0x10
    _INVocabularyStoreManager *_datastoreManager;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010025f870
- (void)fetchCurrentSiriLanguageCode:(CDUnknownBlockType)arg1;	// IMP=0x000000010025f758
- (void)verifyProcessCanDonateIntentWithName:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010025f6e8
- (void)requestSiriAuthorization:(CDUnknownBlockType)arg1;	// IMP=0x000000010025f5a4
- (void)fetchSiriAuthorization:(CDUnknownBlockType)arg1;	// IMP=0x000000010025f52c
- (oneway void)deleteEverything;	// IMP=0x000000010025f38c
- (oneway void)askToSyncSlot:(id)arg1;	// IMP=0x000000010025f224
- (void)_triggerUserVocabularySyncAttributingApp:(id)arg1 vocabType:(id)arg2;	// IMP=0x000000010025f11c
- (oneway void)recordVocabulary:(id)arg1 forIntentSlot:(id)arg2 withValidationCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010025ecc0
- (id)_datastoreManager;	// IMP=0x000000010025ec68
- (id)initWithBundleID:(id)arg1 path:(id)arg2;	// IMP=0x000000010025eb5c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

