//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ADSession.h"

#import "SiriCoreNetworkManagerObserver-Protocol.h"
#import "SiriCoreSiriConnectionDelegate-Protocol.h"

@class ADAuthenticator, ADRetryManager, NSData, NSDate, NSError, NSMutableArray, NSObject, NSString, NSURL;
@protocol OS_dispatch_group, OS_dispatch_queue, SiriCoreSiriConnection;

@interface ADSessionRemoteServer : ADSession <SiriCoreNetworkManagerObserver, SiriCoreSiriConnectionDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    id <SiriCoreSiriConnection> _serverConnection;	// 16 = 0x10
    NSURL *_currentConnectionURL;	// 24 = 0x18
    struct __CFDictionary *_commandMap;	// 32 = 0x20
    ADAuthenticator *_authenticator;	// 40 = 0x28
    NSDate *_cachedValidationDataExpiration;	// 48 = 0x30
    NSData *_cachedValidationData;	// 56 = 0x38
    _Bool _usingCachedCertificateData;	// 64 = 0x40
    _Bool _usingCachedValidationData;	// 65 = 0x41
    _Bool _forceValidationRefresh;	// 66 = 0x42
    _Bool _checkForWiFiTransitionOnRequestEnd;	// 67 = 0x43
    _Bool _prefersWWAN;	// 68 = 0x44
    _Bool _skipPeer;	// 69 = 0x45
    NSError *_skipPeerError;	// 72 = 0x48
    _Bool _forceReconnect;	// 80 = 0x50
    _Bool _hasCachedAuthDisabled;	// 81 = 0x51
    _Bool _cachedAuthDisabled;	// 82 = 0x52
    NSString *_peerType;	// 88 = 0x58
    NSString *_peerVersion;	// 96 = 0x60
    NSString *_productTypePrefix;	// 104 = 0x68
    _Bool _siriConnectionUsesPeerManagedSync;	// 112 = 0x70
    _Bool _useWiFiHint;	// 113 = 0x71
    _Bool _hasActiveRequest;	// 114 = 0x72
    double _aceHeaderTimeout;	// 120 = 0x78
    void *_dormancySuspendAssertion;	// 128 = 0x80
    _Bool _isAttemptingRetry;	// 136 = 0x88
    _Bool _waitingForDelayedRetry;	// 137 = 0x89
    double _requestStartTime;	// 144 = 0x90
    double _requestEndTime;	// 152 = 0x98
    double _lastRetryTimeOnQueue;	// 160 = 0xa0
    double _loadRetryStartTime;	// 168 = 0xa8
    NSString *_sessionInitCommandId;	// 176 = 0xb0
    NSString *_createSessionInfoRequestId;	// 184 = 0xb8
    ADRetryManager *_retryManager;	// 192 = 0xc0
    unsigned long long _badCachedCertRetryCounter;	// 200 = 0xc8
    unsigned long long _certificateFailureCounter;	// 208 = 0xd0
    NSMutableArray *_metricsCache;	// 216 = 0xd8
    NSString *_pairedWatchUniqueId;	// 224 = 0xe0
    NSObject<OS_dispatch_group> *_metricsGroup;	// 232 = 0xe8
    _Bool _isRequestRetry;	// 240 = 0xf0
}

+ (void)_getReportSymptomsBasedNetworkQualityMetrics:(CDUnknownBlockType)arg1;	// IMP=0x00000001002230c0
- (void).cxx_destruct;	// IMP=0x0000000100223880
- (id)currentConnectionPreCachedMetrics;	// IMP=0x00000001002237fc
- (void)getConnectionMetrics:(CDUnknownBlockType)arg1;	// IMP=0x0000000100223418
- (void)assistantDataManagerSiriServerLoggingSettingDidChange;	// IMP=0x0000000100223374
- (void)_generateAWDMetricsForConnectionError:(id)arg1;	// IMP=0x0000000100223370
- (void)_generateAWDMetricsForOpenedConnection:(id)arg1 type:(id)arg2;	// IMP=0x000000010022336c
- (void)_generateAWDMetricsForWillStartConnection:(id)arg1;	// IMP=0x0000000100223368
- (void)_generateAWDTransportMetrics:(id)arg1 moreComing:(_Bool)arg2 transportRecord:(id)arg3;	// IMP=0x0000000100223364
- (id)_generateAnalyticsContextWithError:(id)arg1;	// IMP=0x0000000100222a5c
- (void)_probeSessionIfIdle;	// IMP=0x000000010022293c
- (void)_createAssistant;	// IMP=0x000000010022259c
- (void)_adjustAceHeaderTimeout:(_Bool)arg1;	// IMP=0x0000000100222564
- (void)_resetConnectionPolicyBlacklisting;	// IMP=0x000000010022250c
- (void)_releaseDormancySuspension;	// IMP=0x00000001002224b0
- (void)_forceFastDormancy;	// IMP=0x0000000100222470
- (void)networkManagerNetworkUnreachable:(id)arg1;	// IMP=0x0000000100222450
- (void)_recheckForWiFiTransition;	// IMP=0x0000000100222278
- (void)networkManagerLostNonWWANConnectivity:(id)arg1;	// IMP=0x000000010022214c
- (void)networkManagerNonWWANDidBecomeAvailable:(id)arg1;	// IMP=0x0000000100221f30
- (void)_multiUsersDidChange:(id)arg1;	// IMP=0x0000000100221e18
- (void)_companionServiceStateDidChange:(id)arg1;	// IMP=0x0000000100221cd4
- (void)_homeInfoDidChange:(id)arg1;	// IMP=0x0000000100221b90
- (void)barrier:(CDUnknownBlockType)arg1;	// IMP=0x000000010022199c
- (void)_sendMultiUserInfo;	// IMP=0x00000001002218e0
- (void)sendRemoteGizmoDeviceToServer:(id)arg1;	// IMP=0x0000000100221820
- (void)_sendSetRemoteDevicesWithAccount:(id)arg1;	// IMP=0x0000000100221810
- (void)_sendSetRemoteDevicesWithAccount:(id)arg1 multiUserInfo:(id)arg2;	// IMP=0x0000000100220aa0
- (void)_sendLoadAssistantWithAccount:(id)arg1 validationData:(id)arg2;	// IMP=0x0000000100220340
- (void)_triggerABCForEmptyLocale;	// IMP=0x0000000100220184
- (void)_sendCreateSessionInfoRequestWithData:(id)arg1;	// IMP=0x000000010021ff6c
- (void)_sendGetSessionCertificateData;	// IMP=0x000000010021fdd4
- (void)_sendServerCommands:(id)arg1;	// IMP=0x000000010021f990
- (void)_sendServerCommand:(id)arg1;	// IMP=0x000000010021f608
- (void)_sendServerCommandLogErrorForCommand:(id)arg1 withContext:(id)arg2;	// IMP=0x000000010021f388
- (void)doSendPostProcessing:(id)arg1;	// IMP=0x000000010021f384
- (void)doSendPreProcessing:(id)arg1;	// IMP=0x000000010021f2d0
- (void)_saCommandFailed:(id)arg1;	// IMP=0x000000010021f048
- (void)_assistantFailedForReason:(id)arg1 error:(id)arg2;	// IMP=0x000000010021ec10
- (void)_saSetConnectionHeader:(id)arg1;	// IMP=0x000000010021e80c
- (void)_saAssistantNotReady:(id)arg1;	// IMP=0x000000010021e544
- (void)_saAssistantNotFound:(id)arg1;	// IMP=0x000000010021e450
- (void)_saAssistantDestroyed:(id)arg1;	// IMP=0x000000010021e278
- (void)_saAssistantLoaded:(id)arg1;	// IMP=0x000000010021df1c
- (void)_saAssistantCreated:(id)arg1;	// IMP=0x000000010021de78
- (void)_saCreateSessionInfoResponse:(id)arg1;	// IMP=0x000000010021db78
- (void)_saGetSessionCertificateResponse:(id)arg1;	// IMP=0x000000010021da78
- (void)_saSessionValidationFailed:(id)arg1;	// IMP=0x000000010021d6b4
- (void)_handleAceObject:(id)arg1;	// IMP=0x000000010021d488
- (void)delegateDidHandleCommand:(id)arg1 didRecognizeSpeech:(_Bool)arg2;	// IMP=0x000000010021d414
- (void)_eagerAuthDidComplete;	// IMP=0x000000010021d280
- (void)_connectionOpened;	// IMP=0x000000010021d148
- (void)_startSession;	// IMP=0x000000010021ceb4
- (void)refreshValidationData;	// IMP=0x000000010021cca4
- (void)_continueAuthentication;	// IMP=0x000000010021c714
- (void)_continueAuthWithCertificateData:(id)arg1;	// IMP=0x000000010021c51c
- (void)_continueSessionInitWithValidationData:(id)arg1;	// IMP=0x000000010021c344
- (void)_authenticationFailed;	// IMP=0x000000010021c22c
- (_Bool)sessionIsAttemptingTryOrRetry;	// IMP=0x000000010021c1cc
- (void)_retryForFailedConnection:(id)arg1 withType:(id)arg2 onError:(id)arg3;	// IMP=0x000000010021bb54
- (void)_reallyRetryPreferringWWAN:(_Bool)arg1 skipPeer:(_Bool)arg2 skipPeerError:(id)arg3 useWiFiHint:(_Bool)arg4 causedByError:(id)arg5 forceReconnect:(_Bool)arg6 useSecondary:(_Bool)arg7;	// IMP=0x000000010021b244
- (void)_retryWithParameters:(_Bool)arg1 skipPeer:(_Bool)arg2 skipPeerError:(id)arg3 causedByError:(id)arg4 useSecondary:(_Bool)arg5;	// IMP=0x000000010021b1c4
- (id)_authDataToSign;	// IMP=0x000000010021b0a8
- (_Bool)_persistValidationData:(id)arg1 withExpiration:(id)arg2;	// IMP=0x000000010021af4c
- (void)_setCachedValidationData:(id)arg1 withDuration:(double)arg2;	// IMP=0x000000010021adb0
- (id)_cachedValidationData;	// IMP=0x000000010021ab00
- (void)_setCachedServerCertificate:(id)arg1;	// IMP=0x000000010021a9cc
- (id)_cachedServerCertificate;	// IMP=0x000000010021a860
- (_Bool)_versionForCachedValidationDataMatchesCurrentVersion;	// IMP=0x000000010021a7ac
- (id)_authenticator;	// IMP=0x000000010021a6f4
- (_Bool)_authenticationDisabled;	// IMP=0x000000010021a67c
- (void)_informDelegateOfError:(id)arg1;	// IMP=0x000000010021a360
- (void)endRetryableRequestForCommandAceId:(id)arg1 refId:(id)arg2;	// IMP=0x000000010021a308
- (void)resetRetryManager;	// IMP=0x000000010021a230
- (void)startRetry;	// IMP=0x0000000100219f38
- (_Bool)_connectionErrorIsTimeout:(id)arg1;	// IMP=0x0000000100219e48
- (_Bool)_connectionErrorSuggestsConnectionPolicyReset:(id)arg1;	// IMP=0x0000000100219da8
- (_Bool)_connectionErrorIsRedirect:(id)arg1;	// IMP=0x0000000100219cac
- (void)_updateConnectionPolicyFailureCount:(id)arg1;	// IMP=0x0000000100219948
- (_Bool)_shouldRetry;	// IMP=0x0000000100219880
- (void)siriConnection:(id)arg1 didEncounterIntermediateError:(id)arg2;	// IMP=0x0000000100219868
- (void)_siriConnection:(id)arg1 didEncounterError:(id)arg2 analysisInfo:(id)arg3;	// IMP=0x0000000100218b04
- (void)siriConnection:(id)arg1 didEncounterError:(id)arg2 analysisInfo:(id)arg3;	// IMP=0x00000001002189e8
- (void)siriConnectionDidClose:(id)arg1;	// IMP=0x0000000100218718
- (void)siriConnection:(id)arg1 didReceiveAceObject:(id)arg2;	// IMP=0x0000000100218568
- (void)siriConnection:(id)arg1 didOpenWithConnectionType:(id)arg2 routeId:(id)arg3 delay:(double)arg4 method:(id)arg5;	// IMP=0x00000001002180a0
- (void)siriConnection:(id)arg1 willStartWithConnectionType:(id)arg2;	// IMP=0x0000000100217efc
- (void)_cancelSynchronously:(_Bool)arg1;	// IMP=0x0000000100217e48
- (void)_startConnectionPreferringWWAN:(_Bool)arg1 skipPeer:(_Bool)arg2 skipPeerError:(id)arg3 useWiFiHint:(_Bool)arg4 forceReconnect:(_Bool)arg5;	// IMP=0x0000000100217370
- (void)setHasActiveRequest:(_Bool)arg1;	// IMP=0x00000001002170a4
- (id)_networkManager;	// IMP=0x0000000100217090
- (_Bool)_connectionIsWWAN;	// IMP=0x0000000100217044
- (void)_resetServerConnectionSynchronously:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100216984
- (void)_resetServerConnection;	// IMP=0x0000000100216970
- (id)_serverConnection;	// IMP=0x0000000100216598
- (void)_startConnection;	// IMP=0x00000001002163d0
- (id)_connectionURL;	// IMP=0x0000000100216198
- (void)beginRetryableRequest:(id)arg1;	// IMP=0x000000010021612c
- (void)retryNakedCommandsIfNeeded;	// IMP=0x0000000100215ff0
- (id)_retryManager;	// IMP=0x0000000100215fa4
- (void)setCoreSiriConnection:(id)arg1;	// IMP=0x0000000100215f04
- (_Bool)supportsSync;	// IMP=0x0000000100215efc
- (void)dealloc;	// IMP=0x0000000100215d58
- (id)initOnQueue:(id)arg1 withAccount:(id)arg2 languageCode:(id)arg3 connectionMode:(id)arg4 sharedUserIdentifier:(id)arg5 loggingSharedUserIdentifier:(id)arg6;	// IMP=0x0000000100215974

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

