//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AFUserNotificationService-Protocol.h"
#import "UNUserNotificationCenterDelegate-Protocol.h"

@class FBSDisplayLayoutMonitor, NSMutableDictionary, NSString, NSXPCConnection, UNUserNotificationCenter;
@protocol OS_dispatch_queue;

@interface ADUserNotificationServiceProvider : NSObject <UNUserNotificationCenterDelegate, AFUserNotificationService>
{
    UNUserNotificationCenter *_notificationCenter;	// 8 = 0x8
    NSMutableDictionary *_responseHandlersByNotificationID;	// 16 = 0x10
    NSXPCConnection *_connection;	// 24 = 0x18
    NSMutableDictionary *_notificationsToBeSnoozed;	// 32 = 0x20
    FBSDisplayLayoutMonitor *_layoutMonitor;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
}

+ (id)sharedProviderInDaemon;	// IMP=0x0000000100249ebc
- (void).cxx_destruct;	// IMP=0x000000010024a27c
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100249f34
- (void)_clearNotificationWithIdentifier:(id)arg1;	// IMP=0x0000000100249e28
- (void)_snoozeNotifications;	// IMP=0x0000000100249ba0
- (void)_stopMonitoringUnlockActivity;	// IMP=0x0000000100249b6c
- (void)_startMonitoringUnlockActivity;	// IMP=0x000000010024981c
- (_Bool)_isMonitoringUnlockActivity;	// IMP=0x000000010024980c
- (void)withdrawNotificationRequestWithIdentifier:(id)arg1;	// IMP=0x00000001002496b4
- (void)postNotificationRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100249664
- (void)postNotificationRequest:(id)arg1 options:(unsigned long long)arg2 responseHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100249258
- (id)_init;	// IMP=0x000000010024913c
- (id)initWithConnection:(id)arg1;	// IMP=0x00000001002490d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

