//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface W5DebugManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

+ (void)__airplayLoggingEnabledWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c5dc
+ (void)__setAirPlayLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001c5ac
+ (void)__disableAirPlayLoggingWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c584
+ (void)__enableAirPlayLoggingWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c44c
+ (void)__ios_setBluetoothLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001c280
+ (void)__ios_bluetoothLoggingEnabledWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c0e4
+ (void)__setValue:(id)arg1 key:(id)arg2 domain:(id)arg3;	// IMP=0x000000010001c0b4
+ (id)__valueForKey:(id)arg1 domain:(id)arg2;	// IMP=0x000000010001c08c
+ (void)__setOpenDirectoryLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001bfc8
+ (void)__openDirectoryLoggingEnabledWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001bd98
+ (void)__mostRecentLogWithSuffix:(id)arg1 logPath:(id)arg2 queue:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x000000010001b934
+ (void)__setDHCPLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001b858
+ (void)__setDNSLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001b76c
+ (void)__dnsLoggingEnabledWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001b5c8
+ (void)__toggleDNSLoggingWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001b5a0
+ (void)__setEAPOLLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001b418
+ (void)__eapolLoggingEnabledWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001b2f4
+ (_Bool)__getEAPOLDebugFlagsEnabled;	// IMP=0x000000010001b264
+ (_Bool)__setEAPOLDebugFlagsEnabled:(_Bool)arg1 error:(id *)arg2;	// IMP=0x000000010001b130
+ (void)__ios__setWiFiLoggingEnabled:(_Bool)arg1 queue:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001b028
+ (void)__ios_wifiLoggingEnabledWithQueue:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001af14
+ (void)setOSLogPreferenceLevel:(id)arg1 enableOvserizeMessages:(_Bool)arg2 subsystem:(id)arg3;	// IMP=0x000000010001ad20
- (void)__setNoLoggingWiFiProfileInstalled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001caec
- (void)__queryNoLoggingWiFiProfileInstalledAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001c9d0
- (void)__setMegaWiFiProfileInstalled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c850
- (void)__queryMegaWiFiProfileInstalledAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001c734
- (void)setOpenDirectoryDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ad04
- (void)queryOpenDirectoryDebugLoggingAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001ace8
- (void)setAirPlayDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001accc
- (void)queryAirPlayDebugLoggingAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001acb0
- (void)setDNSDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ac94
- (void)queryDNSDebugLoggingAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001ac78
- (void)setDHCPDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ac5c
- (void)setEAPOLDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ac40
- (void)queryEAPOLDebugLoggingAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001ac24
- (void)setBluetoothDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ac08
- (void)queryBluetoothDebugLoggingAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001abec
- (void)setWiFiDebugLoggingEnabled:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001abd0
- (void)queryWiFiDebugLoggingAndReply:(CDUnknownBlockType)arg1;	// IMP=0x000000010001abb4
- (void)setDebugConfiguration:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a484
- (id)queryDebugConfigurationAndReturnError:(out id *)arg1;	// IMP=0x000000010001a234
- (void)queryDebugConfigurationAndReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100019a20
- (void)dealloc;	// IMP=0x00000001000199d4
- (id)init;	// IMP=0x0000000100019968

@end

