//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol OS_dispatch_queue;

@interface VSServerKeepAliveManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSMutableSet *_activeKeepAlives;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100014880
- (void)cancelKeepAlive:(id)arg1;	// IMP=0x000000010001479c
- (void)maintainKeepAlive:(id)arg1;	// IMP=0x000000010001466c
- (_Bool)hasActiveKeepAlives;	// IMP=0x0000000100014598
- (id)init;	// IMP=0x0000000100014530

@end

