//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSTimer;

@interface MSDDemoUpdateTimeKeeper : NSObject
{
    _Bool _canceled;	// 8 = 0x8
    NSDate *_date;	// 16 = 0x10
    NSTimer *_timer;	// 24 = 0x18
    long long _timeIntervalReservedForCleanup;	// 32 = 0x20
    NSTimer *_timerForFatalError;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x000000010003b320
- (void).cxx_destruct;	// IMP=0x000000010003bd50
@property(retain, nonatomic) NSTimer *timerForFatalError; // @synthesize timerForFatalError=_timerForFatalError;
@property long long timeIntervalReservedForCleanup; // @synthesize timeIntervalReservedForCleanup=_timeIntervalReservedForCleanup;
@property _Bool canceled; // @synthesize canceled=_canceled;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
- (void)forceSwitchToDemoMode:(id)arg1;	// IMP=0x000000010003bc5c
- (_Bool)shouldCleanUp:(id *)arg1;	// IMP=0x000000010003bb48
- (void)canceledByUser;	// IMP=0x000000010003bb04
- (id)setCompletionTimeForFatalError:(int)arg1;	// IMP=0x000000010003b88c
- (id)setCompletionTime:(int)arg1 reserveTimeForCleanup:(_Bool)arg2;	// IMP=0x000000010003b38c

@end

