//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSDHelperAgent, NSData, NSDate, NSDictionary, NSNumber, NSString, NSTimer;

@interface MSDTargetDevice : NSObject
{
    _Bool _aboutToReboot;	// 8 = 0x8
    NSString *_localHubFailuareReason;	// 16 = 0x10
    NSTimer *_snapshotRevertTimer;	// 24 = 0x18
    NSTimer *_waitForCommandTimer;	// 32 = 0x20
    CDUnknownBlockType _buddyCompletionHandler;	// 40 = 0x28
    NSNumber *_modeLock;	// 48 = 0x30
    NSNumber *_buddyCompletionHandlerLock;	// 56 = 0x38
    MSDHelperAgent *_helperAgent;	// 64 = 0x40
}

+ (id)sharedInstance;	// IMP=0x000000010005cef0
- (void).cxx_destruct;	// IMP=0x0000000100068260
@property(retain, nonatomic) MSDHelperAgent *helperAgent; // @synthesize helperAgent=_helperAgent;
@property(retain, nonatomic) NSNumber *buddyCompletionHandlerLock; // @synthesize buddyCompletionHandlerLock=_buddyCompletionHandlerLock;
@property(retain, nonatomic) NSNumber *modeLock; // @synthesize modeLock=_modeLock;
@property(copy, nonatomic) CDUnknownBlockType buddyCompletionHandler; // @synthesize buddyCompletionHandler=_buddyCompletionHandler;
@property(retain, nonatomic) NSTimer *waitForCommandTimer; // @synthesize waitForCommandTimer=_waitForCommandTimer;
@property(retain, nonatomic) NSTimer *snapshotRevertTimer; // @synthesize snapshotRevertTimer=_snapshotRevertTimer;
@property(retain) NSString *localHubFailuareReason; // @synthesize localHubFailuareReason=_localHubFailuareReason;
@property _Bool aboutToReboot; // @synthesize aboutToReboot=_aboutToReboot;
- (id)retrieveSignedManifest;	// IMP=0x0000000100067e54
@property(readonly) unsigned int rebootDelayForStaging;
- (id)readValueFromTestPreferencesForKey:(id)arg1;	// IMP=0x0000000100067bd4
- (void)delayRebootForTesting;	// IMP=0x0000000100067b24
@property(retain) NSDictionary *wifiSettings;
- (void)cleanUpBackgroundState:(_Bool)arg1;	// IMP=0x000000010006785c
@property _Bool proceeded;
@property(retain, nonatomic) NSString *hubProtocolVersion;
@property unsigned long long backgroundDownloadState;
@property _Bool backgroundDownloadActive;
- (_Bool)canEraseOrUnpair;	// IMP=0x0000000100066fe0
- (_Bool)canDeviceUnenroll;	// IMP=0x0000000100066f54
- (id)getDemoEnrollmentFlag;	// IMP=0x0000000100066ef0
- (_Bool)setDemoEnrollmentFlag:(id)arg1;	// IMP=0x0000000100066e6c
- (id)getDeviceOptions;	// IMP=0x0000000100066bc0
- (void)saveDeviceOptions:(id)arg1;	// IMP=0x0000000100066b48
@property(readonly, getter=getFreeSpace) long long freeSpace;
- (void)waitUntilNetworkInterfaceIsUpFor:(unsigned long long)arg1 withTimeout:(unsigned long long)arg2;	// IMP=0x00000001000666f8
- (void)waitForNetworkInterfaceWithTimeout:(unsigned long long)arg1;	// IMP=0x0000000100066678
- (void)waitForNetworkInterface;	// IMP=0x0000000100066668
- (void)restoreNetworkInterfaceConfiguration;	// IMP=0x00000001000665c8
- (void)configureNetworkInterface;	// IMP=0x00000001000664fc
- (_Bool)allowAccountSetup;	// IMP=0x0000000100066494
- (void)terminateConfigurationApp;	// IMP=0x00000001000662bc
- (void)invokeHandler:(_Bool)arg1;	// IMP=0x00000001000661f8
- (void)waitForBuddyWithTimeout;	// IMP=0x00000001000660b8
- (void)waitForBuddy:(CDUnknownBlockType)arg1;	// IMP=0x0000000100066080
- (void)startWaitingForCommandTimer;	// IMP=0x0000000100065ee4
@property _Bool waitingForCommand;
- (void)clearOSUpdateRequest;	// IMP=0x0000000100065c7c
- (id)getOSUpdateRequest;	// IMP=0x0000000100065c18
- (void)saveOSUpdateRequest:(id)arg1;	// IMP=0x0000000100065ba0
- (void)clearMinOSVersionAvailable;	// IMP=0x0000000100065b50
- (void)saveMinOSVersionAvailable:(id)arg1;	// IMP=0x0000000100065ad8
- (id)minOSVersionAvailable;	// IMP=0x0000000100065a74
- (_Bool)clearCurrentiOSBuild;	// IMP=0x0000000100065a18
- (_Bool)saveCurrentiOSBuild;	// IMP=0x0000000100065984
- (id)previousiOSBuild;	// IMP=0x0000000100065920
- (void)setupSnapshotRevertTimerWithNewSettings:(_Bool)arg1;	// IMP=0x0000000100065480
- (void)setupSnapshotRevertTimer;	// IMP=0x0000000100065308
- (void)snapshotRevertTimerHandler:(id)arg1;	// IMP=0x0000000100065140
- (void)clearUpNvramIfNeeded;	// IMP=0x0000000100065038
- (_Bool)createMobileStoreDemoCache;	// IMP=0x0000000100064e7c
- (_Bool)preventSleep;	// IMP=0x0000000100064de8
- (void)markContentInstallingInstalled;	// IMP=0x0000000100064da0
- (_Bool)deleteConfigurationApp;	// IMP=0x0000000100064c98
- (void)destroyWorkFolderForBootTask;	// IMP=0x0000000100064bb4
- (void)setupWorkFolderForBootTask;	// IMP=0x0000000100064ac8
- (void)disableSUAutoDownloadForWatch;	// IMP=0x00000001000649b4
- (void)disableLaunchdServicesForWatch;	// IMP=0x0000000100064974
- (void)manageDemoVolume:(id)arg1;	// IMP=0x0000000100064908
- (void)manageDeviceSnapshot:(id)arg1;	// IMP=0x000000010006489c
- (void)enableSnapshotMode:(_Bool)arg1;	// IMP=0x0000000100064844
- (void)syncStoreDemoMode:(int)arg1;	// IMP=0x00000001000646fc
- (void)setStoreDemoMode:(_Bool)arg1;	// IMP=0x00000001000645d8
- (_Bool)storeDemoMode;	// IMP=0x0000000100064464
- (_Bool)allowSnapshotMode;	// IMP=0x0000000100064458
- (_Bool)turnOnStoreDemoMode;	// IMP=0x00000001000642cc
- (_Bool)deleteNVRam:(id)arg1;	// IMP=0x0000000100064254
- (id)readNVRam:(id)arg1;	// IMP=0x0000000100064144
- (void)installAndWaitForSystemApps;	// IMP=0x0000000100063c9c
- (id)installedDeletableSystemApps;	// IMP=0x0000000100063a10
- (id)requiredDeletableSystemApps;	// IMP=0x00000001000639ac
- (void)saveRequiredDeletableSystemApps;	// IMP=0x00000001000637bc
- (id)demoUserName;	// IMP=0x0000000100063758
- (void)saveDemoUserName:(id)arg1;	// IMP=0x00000001000636e0
- (_Bool)saveHubSuppliedSettings:(id)arg1;	// IMP=0x0000000100063540
- (id)hubSuppliedSettings;	// IMP=0x00000001000633e4
- (void)saveLastSettingsUpdatedTime:(id)arg1;	// IMP=0x0000000100063358
- (id)lastSettingsUpdatedTime;	// IMP=0x00000001000632bc
- (void)saveLastSnapshotRevertTime:(id)arg1;	// IMP=0x0000000100063230
- (id)lastSnapshotRevertTime;	// IMP=0x0000000100063194
- (void)saveHubLastOnlineTime:(long long)arg1;	// IMP=0x00000001000630d8
- (long long)hubLastOnlineTime;	// IMP=0x000000010006304c
- (void)saveLogicSyncTriggeringTime:(long long)arg1;	// IMP=0x0000000100062f90
- (long long)logicSyncTriggeringTime;	// IMP=0x0000000100062f04
- (void)saveHubMigrationRequested:(_Bool)arg1;	// IMP=0x0000000100062e84
- (_Bool)hubMigrationRequested;	// IMP=0x0000000100062df8
- (_Bool)saveHubPort:(id)arg1;	// IMP=0x0000000100062d60
- (id)hubPort;	// IMP=0x0000000100062cfc
- (_Bool)saveHubHostNameList:(id)arg1;	// IMP=0x0000000100062c50
- (id)hubHostNameList;	// IMP=0x0000000100062b6c
- (_Bool)saveHubHostName:(id)arg1;	// IMP=0x0000000100062ad4
- (id)hubHostName;	// IMP=0x0000000100062a70
- (_Bool)saveHubBonjourName:(id)arg1;	// IMP=0x00000001000629ec
- (id)hubBonjourName;	// IMP=0x0000000100062988
- (_Bool)saveHubIsLocal:(_Bool)arg1;	// IMP=0x00000001000628ec
- (_Bool)hubIsLocal;	// IMP=0x0000000100062860
- (_Bool)saveHubCertificateIdentifer:(id)arg1;	// IMP=0x00000001000627a8
- (id)hubCertificateIdentifier;	// IMP=0x0000000100062744
@property(readonly, getter=certificateHash) NSData *certificateHash;
- (_Bool)deactivateDevice;	// IMP=0x0000000100062614
- (_Bool)isContentFrozen;	// IMP=0x00000001000625f0
- (_Bool)isVerifiedPOSDevice;	// IMP=0x00000001000625d0
- (_Bool)isVerifiedDemoDevice;	// IMP=0x00000001000625b0
- (int)activationConfigurationFlags;	// IMP=0x0000000100062404
- (_Bool)demoSetup;	// IMP=0x00000001000623a8
@property(readonly, getter=packageVersion) NSString *pkgVersion;
@property(readonly, getter=demodVersion) NSString *demodVersion;
@property(readonly, getter=OSBuild) NSString *OSBuild;
@property(readonly, getter=OSVersion) NSString *OSVersion;
@property(readonly, getter=nandSize) NSNumber *nandSize;
@property(readonly, getter=lastRebootTime) NSDate *lastRebootTime;
- (int)getSavedCompleteByInterval;	// IMP=0x0000000100061f8c
- (int)getSavedFlag;	// IMP=0x0000000100061ebc
- (id)getSavedPort;	// IMP=0x0000000100061dc0
- (id)getSavedServer;	// IMP=0x0000000100061cc4
- (id)getSavedRequest;	// IMP=0x0000000100061b24
- (_Bool)deleteOperationRequestAndQuitHelper;	// IMP=0x0000000100061a50
- (_Bool)deleteOperationRequest;	// IMP=0x00000001000619b4
- (_Bool)saveOperationRequest:(id)arg1 server:(id)arg2 port:(id)arg3 requestFlag:(int)arg4 completeBy:(int)arg5;	// IMP=0x0000000100061848
@property(getter=criticalUpdatePrioritized, setter=setCriticalUpdatePrioritized:) _Bool criticalUpdatePrioritized;
@property(readonly, getter=manifestAndFileDownloadInfoPath) NSString *manifestAndFileDownloadInfoPath;
@property(readonly, getter=destinationRootPath) NSString *destinationRootPath;
@property(readonly, getter=stagingRootPath) NSString *stagingRootPath;
@property(readonly, getter=manifestPath) NSString *manifestPath;
- (id)getCachingHubFailureEventForPing;	// IMP=0x0000000100061350
- (id)deviceInformation:(id)arg1 appendPingInfo:(_Bool)arg2;	// IMP=0x0000000100060604
- (id)deviceInformationForPing:(id)arg1;	// IMP=0x00000001000605f4
- (id)deviceInformation:(id)arg1;	// IMP=0x00000001000605e4
- (void)manualUpdateMode:(_Bool *)arg1 allowChange:(_Bool *)arg2;	// IMP=0x0000000100060538
- (void)rebootForSnapshotRevert;	// IMP=0x00000001000604b4
- (void)rebootForStage:(int)arg1;	// IMP=0x000000010006019c
- (void)kickOffHubMigrationProcess;	// IMP=0x0000000100060030
- (void)patchBackupFolder;	// IMP=0x000000010005fc78
- (_Bool)moveFilesToFinalDst:(id)arg1 finalPath:(id)arg2;	// IMP=0x000000010005fb38
- (id)pathForDummyPreferenceFile;	// IMP=0x000000010005facc
- (_Bool)setupDemoDeviceMetadataFolder;	// IMP=0x000000010005f8c8
- (void)migrateNvramToDemoVolume;	// IMP=0x000000010005f5f0
- (_Bool)migratePreferenceAndWifiSettingsToDemoVolume;	// IMP=0x000000010005f198
- (_Bool)migrateDemoDeviceToDemoVolume;	// IMP=0x000000010005f120
- (_Bool)removePerHubInfoFromPreferencesForMigration;	// IMP=0x000000010005f0c4
- (void)backToVirgin:(int)arg1;	// IMP=0x000000010005ec8c
- (void)createCookieFileForSkippingBuddy;	// IMP=0x000000010005ea60
- (void)obliterateDevice;	// IMP=0x000000010005e960
- (_Bool)setPOSDeviceFlag;	// IMP=0x000000010005e86c
- (_Bool)setDemoDeviceFlag;	// IMP=0x000000010005e778
- (void)forceSwitchToDemoUpdateModeIfNeeded;	// IMP=0x000000010005e5c8
- (void)forceSwitchToDemoModeIfNeeded;	// IMP=0x000000010005e160
- (void)waitForPricing:(int)arg1 forReboot:(_Bool)arg2;	// IMP=0x000000010005defc
- (_Bool)allowCommand:(id)arg1;	// IMP=0x000000010005dc7c
- (_Bool)switchModeImmediately:(int)arg1;	// IMP=0x000000010005d4dc
@property(retain, nonatomic) NSString *request;
- (_Bool)removeKeyFromPreferenceFile:(id)arg1;	// IMP=0x000000010005d2f8
- (void)setMode:(int)arg1;	// IMP=0x000000010005d270
- (unsigned long long)typeOfDemoDevice;	// IMP=0x000000010005d1a0
@property(readonly, getter=mode) int mode;
@property(readonly, getter=serialNumber) NSString *serialNumber;
@property(readonly, getter=udid) NSString *udid;
- (id)init;	// IMP=0x000000010005cf94

@end

