//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NEPlugin.h"

#import "NEAppPushPluginManager-Protocol.h"

@interface NEAppPushPlugin : NEPlugin <NEAppPushPluginManager>
{
}

- (void)handleProviderStopped;	// IMP=0x00000001000165b4
- (void)sendExtensionFailed;	// IMP=0x00000001000164ec
- (void)reportIncomingCall:(id)arg1;	// IMP=0x00000001000163ec
- (void)handleProviderError:(id)arg1 forMessageID:(id)arg2;	// IMP=0x00000001000162b8
- (void)handleProviderError:(id)arg1;	// IMP=0x00000001000161b8
- (id)managerInterface;	// IMP=0x000000010001619c
- (id)remotePluginInterface;	// IMP=0x0000000100016180
- (void)sendTimerEvent;	// IMP=0x0000000100016140
- (void)sendOutgoingCallMessage:(id)arg1 andMessageID:(id)arg2;	// IMP=0x00000001000160b8
- (void)setProviderConfiguration:(id)arg1;	// IMP=0x000000010001604c
- (void)stopWithReason:(int)arg1;	// IMP=0x0000000100016004
- (void)startConnectionWithProviderConfig:(id)arg1;	// IMP=0x0000000100015f98

@end

