//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@interface ASCOfferMetadata : NSObject <NSSecureCoding, NSCopying>
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010000d2a8
+ (id)progressMetadataWithValue:(double)arg1;	// IMP=0x000000010000d270
+ (id)indeterminateProgressMetadata;	// IMP=0x000000010000d248
+ (id)redownloadMetadata;	// IMP=0x000000010000d22c
+ (id)placeholderMetadata;	// IMP=0x000000010000d210
+ (id)iconMetadataWithImageName:(id)arg1 animationName:(id)arg2;	// IMP=0x000000010000d198
+ (id)textMetadataWithTitle:(id)arg1 subtitle:(id)arg2;	// IMP=0x000000010000d120
+ (id)emptyMetadata;	// IMP=0x000000010000d104
@property(readonly, nonatomic, getter=isPlaceholder) _Bool placeholder;
@property(readonly, nonatomic, getter=isProgress) _Bool progress;
@property(readonly, nonatomic, getter=isIcon) _Bool icon;
@property(readonly, nonatomic, getter=isText) _Bool text;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010000d2e8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010000d2e4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010000d2b0
- (id)init;	// IMP=0x000000010000d0cc
- (id)_init;	// IMP=0x000000010000d098

@end

