//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SiriUI/SiriUISnippetViewController.h>

@class SAUIButton, SRBigButtonView;

@interface SRBigButtonController : SiriUISnippetViewController
{
    SRBigButtonView *_buttonView;	// 8 = 0x8
    SAUIButton *_buttonObject;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100028bdc
- (void)_bigButtonHit:(id)arg1;	// IMP=0x0000000100028b58
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x0000000100028af4
- (void)loadView;	// IMP=0x0000000100028868
- (_Bool)usePlatterStyle;	// IMP=0x0000000100028860
- (struct UIEdgeInsets)defaultViewInsets;	// IMP=0x000000010002884c
- (id)snippet;	// IMP=0x0000000100028844
- (void)setAceObject:(id)arg1;	// IMP=0x00000001000287e0
- (void)dealloc;	// IMP=0x0000000100028758

@end

