//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SRCompactEditableUtteranceViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class AFUserUtterance, NSArray, NSString, SRCompactEditableUtteranceView, SRPreferences, UITableView, UITextView;
@protocol SRCompactEditableUtteranceViewControllerDataSource, SRCompactEditableUtteranceViewControllerDelegate;

@interface SRCompactEditableUtteranceViewController : UIViewController <SRCompactEditableUtteranceViewDelegate, UITableViewDelegate, UITableViewDataSource, UITextViewDelegate>
{
    SRCompactEditableUtteranceView *_editableUtteranceView;	// 8 = 0x8
    AFUserUtterance *_userUtterance;	// 16 = 0x10
    NSArray *_alternativeUtterances;	// 24 = 0x18
    id <SRCompactEditableUtteranceViewControllerDataSource> _dataSource;	// 32 = 0x20
    SRPreferences *_userPreferences;	// 40 = 0x28
    UITextView *_textViewForFooterText;	// 48 = 0x30
    _Bool _shouldShowTip;	// 56 = 0x38
    _Bool _didUpdateShowTipCount;	// 57 = 0x39
    id <SRCompactEditableUtteranceViewControllerDelegate> _delegate;	// 64 = 0x40
    UITableView *_alternativesTableView;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0000000100086134
@property(nonatomic, getter=_didUpdateShowTipCount, setter=_setDidUpdateShowTipCount:) _Bool didUpdateShowTipCount; // @synthesize didUpdateShowTipCount=_didUpdateShowTipCount;
@property(nonatomic, getter=_shouldShowTip, setter=_setShouldShowTip:) _Bool shouldShowTip; // @synthesize shouldShowTip=_shouldShowTip;
@property(retain, nonatomic, getter=_alternativesTableView, setter=_setAlternativesTableView:) UITableView *alternativesTableView; // @synthesize alternativesTableView=_alternativesTableView;
@property(nonatomic, getter=_delegate, setter=_setDelegate:) __weak id <SRCompactEditableUtteranceViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_didShowTip;	// IMP=0x0000000100086024
- (id)_attributedStringForTip;	// IMP=0x0000000100085e78
- (_Bool)_shouldShowAlternativesTableView;	// IMP=0x0000000100085e48
- (void)_setupAlternativesTableView;	// IMP=0x0000000100085b28
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;	// IMP=0x0000000100085ab0
- (_Bool)_canShowWhileLocked;	// IMP=0x0000000100085aac
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100085a24
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;	// IMP=0x0000000100085998
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;	// IMP=0x00000001000856ec
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;	// IMP=0x0000000100085640
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x000000010008554c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100085354
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010008534c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100085318
- (void)editableUtteranceView:(id)arg1 didFinishEditingWithText:(id)arg2;	// IMP=0x00000001000852a8
- (void)didResignFirstResponderFromUtteranceView:(id)arg1;	// IMP=0x0000000100085260
- (void)willBeginEditingFromUtteranceView:(id)arg1;	// IMP=0x0000000100085218
- (void)editableUtteranceView:(id)arg1 requestsKeyboardWithCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000851a8
- (void)loadView;	// IMP=0x0000000100084eb8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100084e60
- (id)initWithUserUtterance:(id)arg1 delegate:(id)arg2 dataSource:(id)arg3 preferences:(id)arg4;	// IMP=0x0000000100084d10
- (id)initWithUserUtterance:(id)arg1 delegate:(id)arg2 dataSource:(id)arg3;	// IMP=0x0000000100084c5c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

