//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SiriUI/SiriUISnippetCollectionViewController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSCache, NSDate, NSMutableArray, NSMutableSet, NSOperationQueue, NSSet, NSString, SAGuidanceGuideSnippet, SRBigButtonController, UIImage;

@interface SRGuideViewController : SiriUISnippetCollectionViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
    NSCache *_domainIconCache;	// 8 = 0x8
    NSDate *_startViewingTime;	// 16 = 0x10
    _Bool _showingDetails;	// 24 = 0x18
    NSSet *_siriEnabledAppList;	// 32 = 0x20
    SRBigButtonController *_bigButtonController;	// 40 = 0x28
    NSOperationQueue *_guideImageOperationQueue;	// 48 = 0x30
    NSMutableSet *_spawnedGuideImageFetches;	// 56 = 0x38
    UIImage *_fallbackImage;	// 64 = 0x40
    NSMutableArray *_enabledIntentSupportedAppSnippets;	// 72 = 0x48
    SAGuidanceGuideSnippet *_guideSnippet;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x00000001000260cc
@property(retain, nonatomic, getter=_guideSnippet) SAGuidanceGuideSnippet *guideSnippet; // @synthesize guideSnippet=_guideSnippet;
- (_Bool)_canShowWhileLocked;	// IMP=0x00000001000260b4
- (void)_prepareSiriEnabledAppList;	// IMP=0x0000000100025e70
- (_Bool)_hasTitle;	// IMP=0x0000000100025df8
- (id)_fallbackImage;	// IMP=0x0000000100025d50
- (id)_iconImageForGuideDomainSnippet:(id)arg1;	// IMP=0x00000001000259d4
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x00000001000259c4
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010002588c
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100025690
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100025688
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;	// IMP=0x0000000100025680
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000255c4
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100024f0c
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100024e1c
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100024e14
- (double)_heightOfRowForDomainSnippet:(id)arg1;	// IMP=0x0000000100024d28
- (id)_domainSnippetForIndexPath:(id)arg1;	// IMP=0x0000000100024c98
- (id)_domainSnippetForEnabledIntentSupportedAppAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100024c80
- (id)_domainSnippetForHelpDomainAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100024bfc
- (long long)_numberOfIntentEnabledApps;	// IMP=0x0000000100024be4
- (long long)_numberOfIntentSupportedApps;	// IMP=0x0000000100024b70
- (long long)_numberOfHelpDomains;	// IMP=0x0000000100024afc
- (long long)_pinAnimationType;	// IMP=0x0000000100024ae0
- (_Bool)usePlatterStyle;	// IMP=0x0000000100024ad8
- (_Bool)wantsToManageBackgroundColor;	// IMP=0x0000000100024ad0
- (double)desiredHeightForTransparentHeaderView;	// IMP=0x00000001000249fc
- (void)configureReusableTransparentHeaderView:(id)arg1;	// IMP=0x000000010002496c
- (Class)transparentHeaderViewClass;	// IMP=0x0000000100024938
- (void)_endTrackingGuideShowTimeIfNecessary;	// IMP=0x00000001000247b0
- (double)desiredTopPaddingBelowController:(id)arg1;	// IMP=0x0000000100024688
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x00000001000244b0
- (void)siriDidDeactivate;	// IMP=0x00000001000244a4
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100024378
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010002421c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100024080
- (void)loadView;	// IMP=0x0000000100023eb4
- (id)_bigButtonViewController;	// IMP=0x0000000100023dc0
- (void)setDelegate:(id)arg1;	// IMP=0x0000000100023d70
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100023d18
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100023c04

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

