//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVPlayerItem, AVPlayerLooper, AVQueuePlayer, NSArray, NSString;

@interface SSPlaybackEngine : NSObject
{
    NSString *_lastPlayedAsset;	// 8 = 0x8
    AVQueuePlayer *_audioScapesPlayer;	// 16 = 0x10
    AVPlayerItem *_playerItem;	// 24 = 0x18
    AVPlayerLooper *_avPlayerLooper;	// 32 = 0x20
    NSArray *_songs;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x000000010000ec60
@property(retain) NSArray *songs; // @synthesize songs=_songs;
@property(retain) AVPlayerLooper *avPlayerLooper; // @synthesize avPlayerLooper=_avPlayerLooper;
@property(retain) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain) AVQueuePlayer *audioScapesPlayer; // @synthesize audioScapesPlayer=_audioScapesPlayer;
@property(copy, nonatomic) NSString *lastPlayedAsset; // @synthesize lastPlayedAsset=_lastPlayedAsset;
- (void)resume;	// IMP=0x000000010000eaec
- (id)description;	// IMP=0x000000010000eae0
- (void)stop;	// IMP=0x000000010000ead4
- (void)pause;	// IMP=0x000000010000e9c4
- (void)play:(id)arg1;	// IMP=0x000000010000e708
- (id)init;	// IMP=0x000000010000e61c

@end

