//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ACCConnectionInfoDelegateProtocol-Protocol.h"
#import "tGraphDataSource-Protocol.h"

@class ACCConnectionInfo, CommonProduct, NSMutableDictionary, NSString;

@interface AccessoryHelper : NSObject <ACCConnectionInfoDelegateProtocol, tGraphDataSource>
{
    CommonProduct *_product;	// 8 = 0x8
    _Bool _accessoryAttached;	// 16 = 0x10
    _Bool _previousAttachedState;	// 17 = 0x11
    int _filteredAttachValue;	// 20 = 0x14
    int _filterCount;	// 24 = 0x18
    ACCConnectionInfo *_accConnectionInfo;	// 32 = 0x20
    NSMutableDictionary *_connectedEndpoints;	// 40 = 0x28
}

@property NSMutableDictionary *connectedEndpoints; // @synthesize connectedEndpoints=_connectedEndpoints;
@property ACCConnectionInfo *accConnectionInfo; // @synthesize accConnectionInfo=_accConnectionInfo;
- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x0000000100030bb8
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x0000000100030b94
- (int)numberOfFields;	// IMP=0x0000000100030b8c
- (void)accessoryEndpointDetached:(id)arg1 forConnection:(id)arg2;	// IMP=0x00000001000309b8
- (void)accessoryEndpointAttached:(id)arg1 transportType:(int)arg2 protocol:(int)arg3 properties:(id)arg4 forConnection:(id)arg5;	// IMP=0x0000000100030828
- (void)handleAccessoryEventForEndpointUUID:(id)arg1 andAttachedState:(_Bool)arg2;	// IMP=0x0000000100030694
- (_Bool)isAccessoryAttached;	// IMP=0x000000010003068c
- (void)applyUpdatedAccessoryState:(int)arg1;	// IMP=0x00000001000305ac
- (void)initializeFilteredAttachedState:(_Bool)arg1;	// IMP=0x00000001000304b0
- (void)updateFilter:(_Bool)arg1;	// IMP=0x0000000100030428
- (id)initWithProduct:(id)arg1;	// IMP=0x0000000100030214

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

