//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface AWDThermalMonitorChargerType : PBCodable <NSCopying>
{
    unsigned long long _timestamp;	// 8 = 0x8
    unsigned int _chargerType;	// 16 = 0x10
    struct {
        unsigned int timestamp:1;
        unsigned int chargerType:1;
    } _has;	// 20 = 0x14
}

@property(nonatomic) unsigned int chargerType; // @synthesize chargerType=_chargerType;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100004ea8
- (unsigned long long)hash;	// IMP=0x0000000100004e54
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100004dac
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100004d1c
- (void)copyTo:(id)arg1;	// IMP=0x0000000100004cc0
- (void)writeTo:(id)arg1;	// IMP=0x0000000100004c44
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100004c3c
- (id)dictionaryRepresentation;	// IMP=0x0000000100004894
- (id)description;	// IMP=0x0000000100004814
@property(nonatomic) _Bool hasChargerType;
@property(nonatomic) _Bool hasTimestamp;

@end

