//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BackLightCC.h"

#import "tGraphDataSource-Protocol.h"

@interface BackLightCCSingle : BackLightCC <tGraphDataSource>
{
    unsigned int gPowerServiceBL;	// 304 = 0x130
    int _brightnessMilliNitsCurrent;	// 308 = 0x134
    int _brightnessMilliNitsMaximum;	// 312 = 0x138
}

- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x00000001000322ec
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x000000010003223c
- (int)numberOfFields;	// IMP=0x0000000100032204
- (void)refreshFunctionalTelemetry;	// IMP=0x0000000100031f64
- (_Bool)findBacklightServices;	// IMP=0x0000000100031ee4
- (id)initWithParams:(struct __CFDictionary *)arg1;	// IMP=0x0000000100031e58

@end

