//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_DASActivityPolicy-Protocol.h"

@class NSArray, NSString;

@interface _DASPhotosPolicy : NSObject <_DASActivityPolicy>
{
    _Bool _photosIsForeground;	// 8 = 0x8
    NSString *_policyName;	// 16 = 0x10
    NSArray *_triggers;	// 24 = 0x18
}

+ (_Bool)isActivity:(id)arg1 consideredNonDiscretionary:(id)arg2;	// IMP=0x0000000100029bbc
+ (_Bool)isPhotosMessagesAppForegroundWithContext:(id)arg1;	// IMP=0x0000000100029b64
+ (_Bool)isPhotosForegroundWithContext:(id)arg1;	// IMP=0x0000000100029ab8
+ (_Bool)isCMMActivity:(id)arg1;	// IMP=0x0000000100029764
+ (_Bool)isiCPLActivity:(id)arg1;	// IMP=0x00000001000295e8
+ (id)keyPathForBlockedStartDate;	// IMP=0x00000001000295dc
+ (id)keyPathForPhotosIsBlocked;	// IMP=0x00000001000295d0
+ (id)keyPathForPhotosBudgetOverride;	// IMP=0x00000001000295c4
+ (id)keyPathForSignificantWorkRemaining;	// IMP=0x00000001000295b8
+ (id)policyInstance;	// IMP=0x0000000100029518
+ (void)initialize;	// IMP=0x0000000100029174
+ (id)photosFocalAppStateChangedPredicate;	// IMP=0x0000000100029100
- (void).cxx_destruct;	// IMP=0x000000010002a0c0
@property(nonatomic) _Bool photosIsForeground; // @synthesize photosIsForeground=_photosIsForeground;
@property(retain, nonatomic) NSArray *triggers; // @synthesize triggers=_triggers;
@property(retain, nonatomic) NSString *policyName; // @synthesize policyName=_policyName;
- (id)responseForActivity:(id)arg1 withState:(id)arg2;	// IMP=0x0000000100029c8c
- (_Bool)isEnergyBudgetAvailableForPhotos:(id)arg1;	// IMP=0x0000000100029c84
- (_Bool)isDataBudgetAvailableForPhotos:(id)arg1;	// IMP=0x0000000100029c7c
- (double)weightForActivity:(id)arg1;	// IMP=0x0000000100029ab0
- (_Bool)appliesToActivity:(id)arg1;	// IMP=0x0000000100029a3c
- (_Bool)shouldIgnoreTrigger:(id)arg1 withState:(id)arg2;	// IMP=0x0000000100029958
- (_Bool)shouldOverrideSignificantWork:(id)arg1;	// IMP=0x00000001000298b4
- (_Bool)shouldOverrideBudgets:(id)arg1;	// IMP=0x000000010002985c
- (_Bool)haveSignificantWorkRemaining:(id)arg1;	// IMP=0x0000000100029804
- (id)init;	// IMP=0x0000000100029494
- (id)initializeTriggers;	// IMP=0x0000000100029254

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

