//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PBAttentionMonitorStateMachine.h"

@interface NowPlayingSM : PBAttentionMonitorStateMachine
{
}

- (void)_enterOffStateForced;	// IMP=0x0000000100010900
- (void)_enterOnStateForced;	// IMP=0x0000000100010890
- (void)_enterOffStateAutomatically;	// IMP=0x000000010001087c
- (void)_enterOnStateAutomatically;	// IMP=0x00000001000107bc
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x000000010000feb8
- (id)init;	// IMP=0x000000010000fb9c

@end

