//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import "PBAppInfoControllerDelegate-Protocol.h"

@class BSBlockSentinel, BSWatchdog, NSObject, NSSet, NSString, PBAppInfoController;
@protocol OS_dispatch_queue;

@interface PBWaitForApplicationPersonaChangesOperation : NSOperation <PBAppInfoControllerDelegate>
{
    _Bool _executing;	// 8 = 0x8
    _Bool _finished;	// 9 = 0x9
    NSSet *_personaEnabledApplicationIdentifiers;	// 16 = 0x10
    NSString *_selectedPersonaUniqueString;	// 24 = 0x18
    CDUnknownBlockType _waitForApplicationPesonaChangesCompletionHandler;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_workQueue;	// 40 = 0x28
    BSBlockSentinel *_completionHandlerSentinel;	// 48 = 0x30
    PBAppInfoController *_appInfoController;	// 56 = 0x38
    BSWatchdog *_watchdog;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000f56c0
@property(readonly, nonatomic) BSWatchdog *watchdog; // @synthesize watchdog=_watchdog;
@property(readonly, nonatomic) PBAppInfoController *appInfoController; // @synthesize appInfoController=_appInfoController;
@property(readonly, nonatomic) BSBlockSentinel *completionHandlerSentinel; // @synthesize completionHandlerSentinel=_completionHandlerSentinel;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(copy, nonatomic) CDUnknownBlockType waitForApplicationPesonaChangesCompletionHandler; // @synthesize waitForApplicationPesonaChangesCompletionHandler=_waitForApplicationPesonaChangesCompletionHandler;
@property(readonly, nonatomic) NSString *selectedPersonaUniqueString; // @synthesize selectedPersonaUniqueString=_selectedPersonaUniqueString;
@property(readonly, nonatomic) NSSet *personaEnabledApplicationIdentifiers; // @synthesize personaEnabledApplicationIdentifiers=_personaEnabledApplicationIdentifiers;
- (void)appInfoController:(id)arg1 didUpdate:(id)arg2;	// IMP=0x00000001000f5398
- (CDUnknownBlockType)_watchdogBlock;	// IMP=0x00000001000f51cc
- (CDUnknownBlockType)_completionHandlerSentinelBlock;	// IMP=0x00000001000f4c9c
- (id)_workQueue_updatingApplicationIdentifiers;	// IMP=0x00000001000f49e8
- (CDUnknownBlockType)_personaEnabledApplicationsFilter;	// IMP=0x00000001000f4778
- (void)start;	// IMP=0x00000001000f3fe8
- (_Bool)isFinished;	// IMP=0x00000001000f3f78
- (_Bool)isExecuting;	// IMP=0x00000001000f3f08
- (_Bool)isAsynchronous;	// IMP=0x00000001000f3ee8
- (id)initWithPersonaEnabledApplicationIdentifiers:(id)arg1 selectedPesonaUniqueString:(id)arg2;	// IMP=0x00000001000f3d4c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

