//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface WiFiLOIManager : NSObject
{
    _Bool _deviceIsAssociated;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    double _bestLatitudeReading;	// 24 = 0x18
    double _bestLongitudeReading;	// 32 = 0x20
    double _accuracyOfBestReading;	// 40 = 0x28
}

+ (id)sharedWiFiLOIManager;	// IMP=0x0000000100002ba0
@property _Bool deviceIsAssociated; // @synthesize deviceIsAssociated=_deviceIsAssociated;
@property(nonatomic) double accuracyOfBestReading; // @synthesize accuracyOfBestReading=_accuracyOfBestReading;
@property(nonatomic) double bestLongitudeReading; // @synthesize bestLongitudeReading=_bestLongitudeReading;
@property(nonatomic) double bestLatitudeReading; // @synthesize bestLatitudeReading=_bestLatitudeReading;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (_Bool)ingestLocationUpdateWithLat:(double)arg1 andLon:(double)arg2 andAccuracy:(double)arg3;	// IMP=0x0000000100003878
- (void)_locationUpdateNotificationHandler:(id)arg1;	// IMP=0x0000000100003874
- (int)query:(id)arg1 andMaximumDistanceInMeters:(double)arg2;	// IMP=0x00000001000030dc
- (void)asyncQueryLOITypeAtLatestLocationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100002fa0
- (int)queryLOITypeAtLocationAndMaxDistance:(id)arg1 andMaximumDistanceInMeters:(double)arg2;	// IMP=0x0000000100002ee4
- (int)queryLOITypeAtLastLocation;	// IMP=0x0000000100002edc
- (int)queryLOITypeAtLatestLocation;	// IMP=0x0000000100002d84
- (void)dealloc;	// IMP=0x0000000100002d38
- (id)init;	// IMP=0x0000000100002c30

@end

