//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATModernMenuGesturesSheetBase.h"

@protocol SCATMenuFlickItemsViewDelegate;

@interface SCATModernMenuGestureFlickSheet : SCATModernMenuGesturesSheetBase
{
    id <SCATMenuFlickItemsViewDelegate> _delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100089a50
@property(nonatomic) __weak id <SCATMenuFlickItemsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)menuItemWasActivated:(id)arg1;	// IMP=0x0000000100089848
- (id)makeMenuItemsIfNeeded;	// IMP=0x00000001000895ac

@end

