//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATElementManager.h"

@class NSArray, SCATAppleTVRemoteViewController;
@protocol SCATAppleTVRemoteDelegate;

@interface SCATAppleTVRemote : SCATElementManager
{
    id <SCATAppleTVRemoteDelegate> _delegate;	// 8 = 0x8
    SCATAppleTVRemoteViewController *_appleTVRemoteViewController;	// 16 = 0x10
    NSArray *_remoteGroups;	// 24 = 0x18
    NSArray *_remoteElements;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100033078
@property(retain, nonatomic) NSArray *remoteElements; // @synthesize remoteElements=_remoteElements;
@property(retain, nonatomic) NSArray *remoteGroups; // @synthesize remoteGroups=_remoteGroups;
@property(retain, nonatomic) SCATAppleTVRemoteViewController *appleTVRemoteViewController; // @synthesize appleTVRemoteViewController=_appleTVRemoteViewController;
@property(nonatomic) __weak id <SCATAppleTVRemoteDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)containsElement:(id)arg1;	// IMP=0x0000000100032e48
- (void)didFinishProvidingElements;	// IMP=0x0000000100032e44
- (void)willBeginProvidingElements;	// IMP=0x0000000100032e40
- (id)elementAfter:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x0000000100032d30
- (id)elementBefore:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x0000000100032c20
- (id)lastElementWithOptions:(int *)arg1;	// IMP=0x0000000100032ba0
- (id)firstElementWithOptions:(int *)arg1;	// IMP=0x0000000100032b20
- (_Bool)providesElements;	// IMP=0x0000000100032b18
- (_Bool)canBeActiveElementManager;	// IMP=0x0000000100032b10
- (id)identifier;	// IMP=0x0000000100032b00
- (id)viewController;	// IMP=0x0000000100032874
- (id)_groupForElement:(id)arg1;	// IMP=0x000000010003269c
- (_Bool)_isGroupingEnabled;	// IMP=0x0000000100031f04
- (id)init;	// IMP=0x0000000100031ed0

@end

