//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIBezierPath.h>

@interface UIBezierPath (SCATModernMenuAdditions)
- (void)ax_addArcWithFirstPoint:(struct CGPoint)arg1 secondPoint:(struct CGPoint)arg2 cornerRadius:(double)arg3;	// IMP=0x0000000100025190
- (id)convertPathToView:(id)arg1;	// IMP=0x000000010002e494
- (id)offsetPathByPoint:(struct CGPoint)arg1;	// IMP=0x000000010002e424
- (id)_convertPointInPathWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010002e21c
- (void)enumerateElementsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010002e1d4
@end

