//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCMSQLiteDB, MCMUserIdentityCache;
@protocol MCMManagedPath, OS_dispatch_queue;

@interface MCMCodeSigningMapping : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    MCMSQLiteDB *_codeSigningMappingDB;	// 16 = 0x10
    MCMUserIdentityCache *_userIdentityCache;	// 24 = 0x18
    id <MCMManagedPath> _library;	// 32 = 0x20
}

+ (id)systemGroupIdentifiersForIdentifier:(id)arg1 entitlements:(id)arg2;	// IMP=0x000000010004ad98
+ (id)appGroupIdentifiersForIdentifier:(id)arg1 entitlements:(id)arg2;	// IMP=0x000000010004ad34
+ (id)copyGroupEntitlementForIdentifier:(id)arg1 entitlements:(id)arg2 groupKey:(id)arg3;	// IMP=0x000000010004a96c
+ (id)codeSignMappingWithError:(id *)arg1;	// IMP=0x000000010004a55c
- (void).cxx_destruct;	// IMP=0x0000000100048220
@property(readonly, nonatomic) id <MCMManagedPath> library; // @synthesize library=_library;
@property(readonly, nonatomic) MCMUserIdentityCache *userIdentityCache; // @synthesize userIdentityCache=_userIdentityCache;
@property(retain, nonatomic) MCMSQLiteDB *codeSigningMappingDB; // @synthesize codeSigningMappingDB=_codeSigningMappingDB;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (_Bool)_onQueue_registerKernelProvidedReferencesForIdentifier:(id)arg1 withAppGroupContainers:(id)arg2 systemGroupContainers:(id)arg3 error:(unsigned long long *)arg4;	// IMP=0x0000000100047a34
- (_Bool)registerKernelProvidedReferencesForIdentifier:(id)arg1 withAppGroupContainers:(id)arg2 systemGroupContainers:(id)arg3 error:(unsigned long long *)arg4;	// IMP=0x00000001000478b8
- (_Bool)_onQueue_removeAllAdvanceCopiesWithError:(id *)arg1;	// IMP=0x0000000100047830
- (_Bool)removeAllAdvanceCopiesWithError:(id *)arg1;	// IMP=0x0000000100047758
- (void)_onQueue_removeGroupContainersIfNeededforUserIdentity:(id)arg1 groupContainerClass:(unsigned long long)arg2 identifiers:(id)arg3 referenceCounts:(id)arg4 commandQueue:(id)arg5;	// IMP=0x000000010004737c
- (void)_onQueue_removeReferenceForGroupIdentifiers:(id)arg1 ofType:(long long)arg2 commandQueue:(id)arg3;	// IMP=0x0000000100047038
- (void)_onQueue_handleChangeFromOldGroupContainerIds:(id)arg1 toNewGroupContainerIds:(id)arg2 ofType:(long long)arg3 commandQueue:(id)arg4;	// IMP=0x0000000100046ee0
- (id)_onQueue_copyReferenceCountSetOfType:(long long)arg1;	// IMP=0x0000000100046de8
- (id)copyReferenceCountSetOfType:(long long)arg1;	// IMP=0x0000000100046cec
- (_Bool)invalidateCodeSigningInfoForIdentifier:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100046bdc
- (_Bool)invalidateCodeSigningInfoForIdentifierAndItsChildren:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100046a90
- (id)_onQueue_identifiersWithError:(id *)arg1;	// IMP=0x0000000100046a00
- (id)identifiersWithError:(id *)arg1;	// IMP=0x00000001000468ac
- (unsigned long long)invalidateCodeSigningInfoForAppsWithoutBundleContainer;	// IMP=0x0000000100045ff0
- (id)entitlementsForIdentifier:(id)arg1;	// IMP=0x0000000100045a64
- (id)getCodeSigningInfoForIdentifier:(id)arg1;	// IMP=0x0000000100045910
- (unsigned long long)processCodeSigningInfo:(id)arg1 forIdentifier:(id)arg2 withOptions:(id)arg3 commandQueue:(id)arg4;	// IMP=0x0000000100045724
- (unsigned long long)processCallerRegisteredEntitlements:(id)arg1 forIdentifier:(id)arg2 commandQueue:(id)arg3;	// IMP=0x00000001000453a8
- (id)systemGroupIdentifiersForIdentifier:(id)arg1;	// IMP=0x0000000100045318
- (id)appGroupIdentifiersForIdentifier:(id)arg1;	// IMP=0x0000000100045288
- (unsigned long long)dataContainerTypeForIdentifier:(id)arg1;	// IMP=0x0000000100045184
- (_Bool)identifierHasSystemContainer:(id)arg1;	// IMP=0x000000010004512c
- (_Bool)identifierHasCallerRegisteredEntitlements:(id)arg1;	// IMP=0x0000000100045028
- (id)codeSigningEntryForIdentifier:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100044ef4
- (id)parentIdentifierForChildIdentifier:(id)arg1;	// IMP=0x0000000100044dcc
- (id)childBundleIdentifiersForParentIdentifier:(id)arg1;	// IMP=0x0000000100044ca4
- (void)removeCodeSigningDictionariesForIdentifierAndItsChildren:(id)arg1 commandQueue:(id)arg2;	// IMP=0x0000000100044970
- (void)_onQueue_iterateGroupIdsWithKey:(id)arg1 fallBackKey:(id)arg2 forAllIdentifiersUsingBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010004470c
- (_Bool)_onQueue_invalidateCodeSigningInfoForIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100044664
- (id)_onQueue_invalidateCodeSigningInfoForIdentifierAndItsChildren:(id)arg1;	// IMP=0x00000001000445ac
- (unsigned long long)_onQueue_processCodeSigningInfo:(id)arg1 forIdentifier:(id)arg2 withOptions:(id)arg3 oldEntitlements:(id)arg4 commandQueue:(id)arg5;	// IMP=0x000000010004333c
- (unsigned long long)_onQueue_dataContainerTypeForIdentifier:(id)arg1;	// IMP=0x00000001000430dc
- (_Bool)_entitlementsHasSystemContainer:(id)arg1;	// IMP=0x0000000100043084
- (_Bool)_onQueue_identifierHasCallerRegisteredEntitlements:(id)arg1;	// IMP=0x0000000100042e24
- (id)_onQueue_codeSigningEntryForIdentifier:(id)arg1 withError:(id *)arg2;	// IMP=0x0000000100042bd0
- (id)_entitlementsFromCodeSigningEntry:(id)arg1;	// IMP=0x0000000100042b70
- (id)_onQueue_entitlementsForIdentifier:(id)arg1;	// IMP=0x0000000100042ab8
- (id)_codeSigningInfoForCodeSigningEntry:(id)arg1 externalRequest:(_Bool)arg2;	// IMP=0x0000000100042a0c
- (id)_onQueue_codeSigningInfoForIdentifier:(id)arg1 externalRequest:(_Bool)arg2;	// IMP=0x0000000100042790
- (id)_onQueue_parentIdentifierForChildIdentifier:(id)arg1;	// IMP=0x0000000100042554
- (id)_onQueue_childBundleIdentifiersForParentIdentifier:(id)arg1;	// IMP=0x0000000100042318
- (id)_onQueue_setCodeSigningDictionaryValues:(id)arg1 forIdentifiers:(id)arg2;	// IMP=0x0000000100041b58
- (id)_readCodeSigningMappingFromDiskAtURL:(id)arg1;	// IMP=0x000000010004178c
- (void)performAllCodeSigningMigrationAndReconciliationWithCommandQueue:(id)arg1;	// IMP=0x0000000100041658
- (void)_onQueue_reconcileSystemContainersWithCommandQueue:(id)arg1;	// IMP=0x0000000100040f04
- (void)_onQueue_migrateCachedCodeSigningInfoFromBundleContainersToMappingWithContainers:(id)arg1 containerClass:(unsigned long long)arg2;	// IMP=0x000000010004059c
- (void)migrateCachedCodeSigningInfoFromBundleContainersToMapping;	// IMP=0x0000000100040294
- (void)_onQueue_migrateDataFromLegacyEntitlementsFileToCodeSigningFile;	// IMP=0x000000010003fa9c
- (void)_onQueue_migrateAppGroupIdsFromDataContainersToFileUsingContainers:(id)arg1;	// IMP=0x000000010003f128
- (void)migrateAppGroupIdsFromDataContainersToFile;	// IMP=0x000000010003eacc
- (void)_onQueue_migrateFromMappingFileToDBIfNecessary;	// IMP=0x000000010003e4e0
- (id)initWithUserIdentityCache:(id)arg1 queue:(id)arg2 mappingDB:(id)arg3 library:(id)arg4;	// IMP=0x000000010003e398

@end

