//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore36SearchResultsContainerViewController : UIViewController
{
    MISSING_TYPE *objectGraph;	// 8 = 0x8
    MISSING_TYPE *storeDataProvider;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 32 = 0x20
    MISSING_TYPE *searchTrendingAppsViewController;	// 40 = 0x28
    MISSING_TYPE *searchResultsDelegate;	// 48 = 0x30
    MISSING_TYPE *activeSection;	// 64 = 0x40
    MISSING_TYPE *activeViewController;	// 88 = 0x58
    MISSING_TYPE *forcedTraitCollection;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x0000000100094050
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000940f0
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100093ea0
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x0000000100093d14
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100093c9c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100093c1c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100093b80
- (void)viewDidLoad;	// IMP=0x0000000100093b54
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100093674

@end

