//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore27TopChartsPageViewController : UIViewController
{
    MISSING_TYPE *objectGraph;	// 8 = 0x8
    MISSING_TYPE *presenter;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 24 = 0x18
    MISSING_TYPE *overlayView;	// 32 = 0x20
    MISSING_TYPE *activeViewController;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001000d8a30
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000d89c8
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000d8488
- (void)viewDidLoad;	// IMP=0x00000001000d82e8
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000d8290

@end

