//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore19ErrorViewController : UIViewController
{
    MISSING_TYPE *previouslySelectedTab;	// 8 = 0x8
}

- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100114c7c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100114b88
- (void)loadView;	// IMP=0x00000001001148c4

@end

