//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore29FullScreenVideoViewController : UIViewController
{
    MISSING_TYPE *videoView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010002120c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010002121c
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010002116c
- (id)init;	// IMP=0x00000001000210f8

@end

