//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSXPCListener.h>

#import "NSXPCListenerDelegate-Protocol.h"
#import "_DKDaemonInterface-Protocol.h"

@class NSString, _DKDataProtectionStateMonitor, _DKKnowledgeStorage, _DKPrivacyPolicyEnforcer, _DKRateLimitPolicyEnforcer;
@protocol _DKSyncCoordinator;

@interface CDKnowledgeDaemon : NSXPCListener <NSXPCListenerDelegate, _DKDaemonInterface>
{
    _DKDataProtectionStateMonitor *_dataProtection;	// 8 = 0x8
    _DKRateLimitPolicyEnforcer *_rateLimitEnforcer;	// 16 = 0x10
    _DKPrivacyPolicyEnforcer *_privacyEnforcer;	// 24 = 0x18
    _DKKnowledgeStorage *_storage;	// 32 = 0x20
    id <_DKSyncCoordinator> _syncCoordinator;	// 40 = 0x28
}

+ (id)defaultUserDaemon;	// IMP=0x000000010001f430
+ (id)defaultDaemon;	// IMP=0x000000010001f140
- (void).cxx_destruct;	// IMP=0x0000000100021c14
@property(retain, nonatomic) id <_DKSyncCoordinator> syncCoordinator; // @synthesize syncCoordinator=_syncCoordinator;
@property(readonly, nonatomic) _DKKnowledgeStorage *storage; // @synthesize storage=_storage;
- (void)deviceUUIDWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021acc
- (void)sourceDeviceIdentityWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000219b8
- (void)deleteRemoteState:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021840
- (void)synchronizeWithUrgency:(unsigned long long)arg1 client:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010002169c
- (void)synchronizeWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021514
- (void)registerARPHomeControlNotificationTask;	// IMP=0x0000000100021510
- (void)registerCloudFamilyPredictionTask;	// IMP=0x000000010002150c
- (void)macSleepModelingDataCollectionTasks;	// IMP=0x0000000100021508
- (void)registerCloudPETDataCollectionTask;	// IMP=0x0000000100021504
- (void)registerAirPlayTasks;	// IMP=0x0000000100021500
- (void)registerHomeControlDataCollectionTask;	// IMP=0x00000001000214fc
- (void)registerCDInteractionDataCollectionTask;	// IMP=0x00000001000214f8
- (void)registerDataCollectionTasks;	// IMP=0x00000001000214b4
- (void)confirmDatabaseConnectionWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100021398
- (id)confirmDatabaseConnectionError;	// IMP=0x00000001000212c8
- (void)reportEventStatistics;	// IMP=0x0000000100020fd4
- (void)logSizeOfStorage:(id)arg1;	// IMP=0x0000000100020b20
- (void)maintainPrivacyWithActivity:(id)arg1;	// IMP=0x0000000100020854
- (void)executeQuery:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000206dc
- (void)deleteAllEventsMatchingPredicate:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000205cc
- (void)deleteAllEventsInEventStreamNamed:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010002052c
- (void)deleteObjects:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100020330
- (void)saveObjects:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000200e8
- (id)classCError;	// IMP=0x0000000100020018
- (void)handleError:(id)arg1;	// IMP=0x000000010001ff44
- (_Bool)isClassCLocked;	// IMP=0x000000010001ff0c
- (id)initWithMachServiceName:(id)arg1 storePath:(id)arg2;	// IMP=0x000000010001f9fc
- (id)initWithMachServiceName:(id)arg1;	// IMP=0x000000010001f974
- (id)init;	// IMP=0x000000010001f95c
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010001f6f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

