//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CPLPrequeliteStorage.h"

#import "CPLEngineInitialQueryTrackerImplementation-Protocol.h"

@class NSString;

@interface CPLPrequeliteInitialQueryTracker : CPLPrequeliteStorage <CPLEngineInitialQueryTrackerImplementation>
{
}

- (_Bool)recordInitialQueryForClassFinished:(Class)arg1 scope:(id)arg2 finishedState:(long long)arg3 error:(id *)arg4;	// IMP=0x0000000100059530
- (_Bool)recordQueryBatchForClass:(Class)arg1 scope:(id)arg2 cursor:(id)arg3 count:(unsigned long long)arg4 error:(id *)arg5;	// IMP=0x00000001000593b4
- (_Bool)recordInitialQueryForClassStarted:(Class)arg1 scope:(id)arg2 cursor:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100059240
- (_Bool)deleteRecordsForScopeIndex:(long long)arg1 maxCount:(long long)arg2 deletedCount:(long long *)arg3 error:(id *)arg4;	// IMP=0x0000000100059128
- (_Bool)fixStorageAfterAnyVersionChange;	// IMP=0x00000001000590b8
- (_Bool)initializeStorage;	// IMP=0x0000000100058fd8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isEmpty;
@property(readonly) Class superclass;

@end

