//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSDDeviceInfo : NSObject
{
}

+ (_Bool)isDeviceAudioAccessory;	// IMP=0x0000000100018d18
+ (_Bool)isDeviceAppleTV;	// IMP=0x0000000100018cf0
+ (_Bool)isDeviceiPad;	// IMP=0x0000000100018cc8
+ (_Bool)isDeviceiPhone;	// IMP=0x0000000100018ca0

@end

