//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MobileInstallerProtocol-Protocol.h"

@class NSString, NSXPCConnection;

@interface MIClientConnection : NSObject <MobileInstallerProtocol>
{
    unsigned int _percentComplete;	// 8 = 0x8
    NSXPCConnection *_xpcConnection;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010000ed48
@property(readonly, nonatomic) unsigned int percentComplete; // @synthesize percentComplete=_percentComplete;
@property(nonatomic) __weak NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
- (void)getTestModeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000ec28
- (void)endTestModeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000eb40
- (void)setTestModeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000ea58
- (void)dieForTesting;	// IMP=0x000000010000e9b4
- (void)getPidForTestingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000e974
- (void)systemAppMigratorHasCompleted:(CDUnknownBlockType)arg1;	// IMP=0x000000010000e714
- (void)waitForSystemAppMigratorToComplete:(CDUnknownBlockType)arg1;	// IMP=0x000000010000e4c0
- (void)setSystemAppMigrationComplete:(CDUnknownBlockType)arg1;	// IMP=0x000000010000e26c
- (void)getAppMetadataForApp:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000db44
- (void)updatePlaceholderMetadataForApp:(id)arg1 installType:(unsigned long long)arg2 failureReason:(unsigned long long)arg3 underlyingError:(id)arg4 failureSource:(unsigned long long)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x000000010000d68c
- (void)checkCapabilities:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000d220
- (void)listSafeHarborsOfType:(long long)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000ce20
- (void)removeSafeHarborForIdentifier:(id)arg1 ofType:(long long)arg2 withOptions:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010000c990
- (void)registerSafeHarborAtPath:(id)arg1 forIdentifier:(id)arg2 ofType:(long long)arg3 withOptions:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010000c404
- (void)processRestoredContainerWithIdentifier:(id)arg1 ofType:(long long)arg2 options:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010000bf04
- (void)fetchDiskUsageForIdentifiers:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000bae0
- (void)updateiTunesMetadataForLSWithIdentifier:(id)arg1 options:(id)arg2 plistData:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010000b770
- (void)updateSinfForLSWithIdentifier:(id)arg1 withOptions:(id)arg2 sinfData:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010000b350
- (_Bool)_validateArgsForMethodWithName:(const char *)arg1 bundleIdentifier:(id)arg2 data:(id)arg3 optionalOptions:(id)arg4 error:(id *)arg5;	// IMP=0x000000010000b124
- (void)fetchInfoForContainerizedAppWithBundleID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000abd0
- (void)fetchInfoForFrameworkAtURL:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000a3f8
- (void)enumerateInstalledAppsWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100009b24
- (void)fetchInstalledDeveloperAppsWithMountPath:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000097a4
- (void)updateSystemAppStateForIdentifier:(id)arg1 appState:(int)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000093ac
- (void)lookupSystemAppStateWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100008fd4
- (void)clearUninstalledIdentifiers:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008bf0
- (void)lookupUninstalledWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000885c
- (void)uninstallIdentifiers:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008168
- (void)installURL:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100007764
- (void)_doInstallationForURL:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000070c0
- (void)_callBlockAfterDelegateMessagesSend:(const char *)arg1 dispatchBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006f88
- (void)sendDelegateMessagesComplete;	// IMP=0x0000000100006e54
- (void)sendProgressWithStatus:(id)arg1;	// IMP=0x0000000100006e44
- (void)sendProgressWithStatus:(id)arg1 percentComplete:(unsigned int)arg2;	// IMP=0x0000000100006d24
- (void)sendProgressWithDictionary:(id)arg1;	// IMP=0x0000000100006bec
@property(readonly, copy, nonatomic) NSString *clientName;

@end

