//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AppInstallPipeline-Protocol.h"
#import "CoordinatorPromiseDataConsumerDelegate-Protocol.h"

@class AppInstallsDatabaseStore, AssetSession, NSMutableDictionary, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface AppInstallQueue : NSObject <CoordinatorPromiseDataConsumerDelegate, AppInstallPipeline>
{
    AssetSession *_assetSession;	// 8 = 0x8
    AppInstallsDatabaseStore *_databaseStore;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 24 = 0x18
    NSOperationQueue *_operationQueue;	// 32 = 0x20
    NSMutableDictionary *_requestLookup;	// 40 = 0x28
}

+ (long long)_computedPhaseForCoordinatorState:(unsigned long long)arg1 allowResume:(_Bool *)arg2;	// IMP=0x0000000100260f14
+ (id)sharedInstance;	// IMP=0x0000000100260d60
- (void).cxx_destruct;	// IMP=0x0000000100266bd0
- (void)_releaseTerminationAssertionUsingInstallInfo:(id)arg1;	// IMP=0x0000000100266bcc
- (_Bool)_isRecoverableNetworkError:(id)arg1;	// IMP=0x0000000100266b24
- (void)_endEventServiceInstallationEventForInstallInfo:(id)arg1;	// IMP=0x0000000100266b20
- (void)_postEventServiceInstallationEventWithPhase:(long long)arg1 forInstallInfo:(id)arg2 entity:(id)arg3;	// IMP=0x0000000100266b1c
- (void)_handleRecoveryResult:(_Bool)arg1 error:(id)arg2 usingInstallInfo:(id)arg3;	// IMP=0x0000000100266870
- (void)_handleAssetResult:(id)arg1 error:(id)arg2 usingInstallInfo:(id)arg3;	// IMP=0x0000000100265468
- (void)_finishPostambleTaskWithInstallInfo:(id)arg1;	// IMP=0x00000001002652a4
- (void)_finishPreambleTaskWithResponse:(id)arg1;	// IMP=0x0000000100264828
- (void)_finishInstallingOperationWithResponse:(id)arg1;	// IMP=0x0000000100264424
- (void)_finishDownloadingOperationWithResponse:(id)arg1;	// IMP=0x0000000100263bd8
- (void)_beginPreambleWithTask:(id)arg1 transaction:(id)arg2;	// IMP=0x00000001002637bc
- (void)_beginPreambleForInstallsMatchingPredicate:(id)arg1 transaction:(id)arg2;	// IMP=0x0000000100263428
- (void)_beginPostambleUsingInstallInfo:(id)arg1 transaction:(id)arg2;	// IMP=0x00000001002630a0
- (void)_beginInstallingUsingInstallInfo:(id)arg1 transaction:(id)arg2;	// IMP=0x0000000100262c44
- (void)_beginDownloadingUsingInstallInfo:(id)arg1 transaction:(id)arg2;	// IMP=0x0000000100262814
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010026256c
- (void)coordinatorPromiseDataConsumer:(id)arg1 willBeginUsingPromise:(id)arg2 forReference:(id)arg3;	// IMP=0x0000000100262374
- (void)stopInstallIDs:(id)arg1 withReason:(long long)arg2 transaction:(id)arg3;	// IMP=0x000000010026214c
- (void)startInstallIDs:(id)arg1 transaction:(id)arg2;	// IMP=0x0000000100261ea4
- (void)finishInstallIDs:(id)arg1 transaction:(id)arg2;	// IMP=0x0000000100261bec
- (void)validateActiveInstallations;	// IMP=0x0000000100260f60
- (id)init;	// IMP=0x0000000100260dcc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

