//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteMemoryEntity.h"

@class AppInstallPolicy, NSArray, NSString;

@interface AppInstall : SQLiteMemoryEntity
{
    NSString *_logKey;	// 8 = 0x8
    NSArray *_packages;	// 16 = 0x10
}

+ (id)_valueDictionaryWithStoreItem:(id)arg1;	// IMP=0x00000001002b4df4
+ (id)defaultProperties;	// IMP=0x00000001002b4c9c
+ (id)legacy_installForActivity:(id)arg1 error:(id *)arg2;	// IMP=0x000000010013471c
+ (id)purchase_installForStoreItem:(id)arg1 usingPurchaseInfo:(id)arg2 error:(id *)arg3;	// IMP=0x00000001002807f4
- (void).cxx_destruct;	// IMP=0x00000001002b5504
@property(copy) NSArray *packages; // @synthesize packages=_packages;
- (id)storeMetadataWithError:(id *)arg1;	// IMP=0x00000001002b4b44
- (void)setValuesWithStoreItem:(id)arg1;	// IMP=0x00000001002b49ac
- (long long)assetRequestReason;	// IMP=0x00000001002b48bc
- (id)cellularDownloadForPackage:(id)arg1;	// IMP=0x00000001002b4730
- (id)bestPackageOnConnection:(id)arg1 withProperties:(id)arg2;	// IMP=0x00000001002b4668
- (id)bestPackageFromArray:(id)arg1;	// IMP=0x00000001002b446c
@property(readonly) long long priority;
@property(copy) AppInstallPolicy *installPolicy;
@property(readonly) NSString *logKey;
@property(readonly, getter=isAutomatic) _Bool automatic;
- (id)initWithStoreItem:(id)arg1;	// IMP=0x00000001002b4174
- (id)placeholderBuilderUsingPackage:(id)arg1 withError:(id *)arg2;	// IMP=0x00000001002350c8
- (id)coordinatorBuilderWithError:(id *)arg1;	// IMP=0x000000010028ceb4
- (id)copyEvaluatorDownloadWithPackage:(id)arg1;	// IMP=0x00000001002aa35c
- (id)copyEvaluatorDownloadUsingConnection:(id)arg1;	// IMP=0x00000001002aa254

@end

