//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class InAppPromotionDatabaseStore;

@interface InAppPromotionManager : NSObject
{
    InAppPromotionDatabaseStore *_databaseStore;	// 8 = 0x8
}

+ (id)manager;	// IMP=0x000000010018ed58
- (void).cxx_destruct;	// IMP=0x000000010018f3e8
- (id)promotionInfoForProductIdentifiers:(id)arg1 bundleID:(id)arg2 error:(id *)arg3;	// IMP=0x000000010018f138
- (_Bool)setPromotionInfo:(id)arg1 forBundleID:(id)arg2 error:(id *)arg3;	// IMP=0x000000010018ef6c
- (void)removePromotionInfoForBundleID:(id)arg1;	// IMP=0x000000010018eec0
- (id)init;	// IMP=0x000000010018edf4

@end

