//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteDatabaseStore.h"

@interface InGameAnalyticsDatabaseStore : SQLiteDatabaseStore
{
}

+ (_Bool)createOrMigrateStoreUsingSchema:(id)arg1;	// IMP=0x000000010028a524
+ (id)storeDescriptor;	// IMP=0x000000010028a4a4
+ (id)sharedStore;	// IMP=0x000000010028a340

@end

