//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface LaunchEventEntity : SQLiteEntity
{
}

+ (Class)memoryEntityClass;	// IMP=0x0000000100298a48
+ (id)defaultProperties;	// IMP=0x0000000100298998
+ (id)databaseTable;	// IMP=0x000000010029898c

@end

