//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface MigratorConfiguration : NSObject
{
    NSString *_migratorType;	// 8 = 0x8
    NSMutableDictionary *_migratorValues;	// 16 = 0x10
    unsigned long long _attempts;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010006e5c0
@property(readonly, nonatomic) NSString *migratorType; // @synthesize migratorType=_migratorType;
@property(readonly, nonatomic) unsigned long long attempts; // @synthesize attempts=_attempts;
- (void)setMigratorValue:(id)arg1 forConfigurationKey:(id)arg2;	// IMP=0x000000010006e528
- (void)incrementAttempts;	// IMP=0x000000010006e518
- (id)copyMigratorValueForConfigurationKey:(id)arg1;	// IMP=0x000000010006e4a0
- (id)copyUserDefaultsRepresentation;	// IMP=0x000000010006e3c8
- (id)initWithUserDefaultsRepresentation:(id)arg1;	// IMP=0x000000010006e264
- (id)initWithMigratorType:(id)arg1;	// IMP=0x000000010006e1e4
- (id)init;	// IMP=0x000000010006e1a8

@end

