//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSPredicateVisitor-Protocol.h"

@class NSArray, NSMutableArray;

@interface PredicateValidator : NSObject <NSPredicateVisitor>
{
    _Bool _acceptableExpressionTypes[32];	// 8 = 0x8
    NSArray *_acceptableKeyPaths;	// 40 = 0x28
    NSMutableArray *_errors;	// 48 = 0x30
    _Bool _valid;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001002306e8
- (void)visitPredicateOperator:(id)arg1;	// IMP=0x00000001002306e4
- (void)visitPredicateExpression:(id)arg1;	// IMP=0x000000010023056c
- (void)visitPredicate:(id)arg1;	// IMP=0x0000000100230568
- (_Bool)validatePredicate:(id)arg1 withError:(id *)arg2;	// IMP=0x00000001002303c8
- (void)setAcceptableKeyPaths:(id)arg1;	// IMP=0x0000000100230380
- (void)setAcceptableExpressionTypes:(unsigned long long *)arg1 count:(unsigned long long)arg2;	// IMP=0x0000000100230360
- (id)init;	// IMP=0x000000010023031c

@end

