//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class TaskQueue;
@protocol OS_dispatch_queue;

@interface StoreQueueManager : NSObject
{
    _Bool _automaticDownloadsAreDisabled;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_callbackQueue;	// 16 = 0x10
    _Bool _checkAutomaticDownloadQueueOnEnable;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 32 = 0x20
    TaskQueue *_operationQueue;	// 40 = 0x28
}

+ (id)storeItemsFromResponseDictionary:(id)arg1;	// IMP=0x00000001000d0778
+ (_Bool)processJobResult:(id)arg1 forReason:(id)arg2;	// IMP=0x00000001000d0490
+ (id)sharedInstance;	// IMP=0x00000001000cf49c
- (void).cxx_destruct;	// IMP=0x00000001000d0a88
- (id)_operationQueue;	// IMP=0x00000001000d0a2c
- (void)_dispatchCallbackAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001000d0900
- (void)_dispatchAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001000d07d4
- (void)managedApplicationRequestWithOptions:(id)arg1 clientID:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000cff40
- (void)getDownloadQueueWithType:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000cfab0
- (void)enableAutomaticDownloadsWithReason:(id)arg1;	// IMP=0x00000001000cf810
- (void)disableAutomaticDownloadsWithReason:(id)arg1;	// IMP=0x00000001000cf6b8
- (void)claimApplicationsWithOptions:(id)arg1 clientID:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000cf5c4
- (void)checkQueue:(long long)arg1 clientID:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000cf538
- (id)init;	// IMP=0x00000001000cf414

@end

