//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface XDCLaunchAppResponse : PBCodable <NSCopying>
{
    int _status;	// 8 = 0x8
}

@property(nonatomic) int status; // @synthesize status=_status;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001002a1a64
- (unsigned long long)hash;	// IMP=0x00000001002a1a48
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001002a19d4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001002a1984
- (void)writeTo:(id)arg1;	// IMP=0x00000001002a196c
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001002a1964
- (id)dictionaryRepresentation;	// IMP=0x00000001002a16cc
- (id)description;	// IMP=0x00000001002a1618

@end

