//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC12searchpartyd21SPTimedAnalyticsEvent.h"

@class MISSING_TYPE;

@interface _TtC12searchpartyd37SPAnalyticsItemRefreshDeviceListEvent : _TtC12searchpartyd21SPTimedAnalyticsEvent
{
    MISSING_TYPE *sessionID;	// 1869045599 = 0x6f675f5f
}

- (void).cxx_destruct;	// IMP=0x000000010029828c

@end

