//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC12searchpartyd21SPTimedAnalyticsEvent.h"

@class MISSING_TYPE;

@interface _TtC12searchpartyd24SPAnalyticsItemPairEvent : _TtC12searchpartyd21SPTimedAnalyticsEvent
{
    MISSING_TYPE *beginVerifyPairing;	// 0 = 0x0
    MISSING_TYPE *endVerifyPairing;	// 1094999903 = 0x41445f5f
    MISSING_TYPE *beginFinalize;	// 1414745679 = 0x54534e4f
    MISSING_TYPE *endFinalize;	// 3981312 = 0x3cc000
    MISSING_TYPE *beginAck;	// 5792 = 0x16a0
}

- (void).cxx_destruct;	// IMP=0x0000000100298410

@end

