//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12searchpartydP33_EBCE4CC9FC18641636B173DB27D7BE0028AdvertisementCacheTrampoline : NSObject
{
    MISSING_TYPE *implementation;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003e054
- (id)init;	// IMP=0x000000010003e064
- (void)clearCacheWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010003df3c
- (void)advertisementCacheSimulation:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003de44
- (void)advertisementsForSearchCriteria:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003ddb8
- (void)markAdvertisementsProcessed:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003d60c
- (void)saveAdvertisements:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003d3ec
- (void)beaconAdvertisementAtFileURL:(id)arg1 beaconIdentifier:(id)arg2 scanDate:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010003cd80
- (void)beaconPayloadsForSearchCriteria:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003cc18
- (void)markFilesProcessed:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003c6e8
- (void)saveBeaconPayloads:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003c59c

@end

