//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPBeaconManagerUserAgentDaemonInternalXPCProtocol-Protocol.h"
#import "SPLocalBeaconManagerXPCProtocol-Protocol.h"
#import "SPLocalPairingManagerXPCProtocol-Protocol.h"

@class MISSING_TYPE;

@interface _TtC12searchpartyd34LightweightBeaconManagerTrampoline : NSObject <SPLocalBeaconManagerXPCProtocol, SPLocalPairingManagerXPCProtocol, SPBeaconManagerUserAgentDaemonInternalXPCProtocol>
{
    MISSING_TYPE *implementation;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010014b778
- (id)init;	// IMP=0x000000010014b788
- (void)currentBeaconingKeyWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014b6a0
- (void)notifyBeaconKeyURLChanged:(id)arg1 deleted:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010014b5a0
- (void)notifyConfigurationChanged:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010014b4cc
- (void)containerWithName:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010014b344
- (void)purgeLocalBeaconRecordWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014b2ec
- (void)pushLocalBeaconRecord:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010014b248
- (void)alwaysBeaconStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014b1a0
- (void)setAlwaysBeaconState:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010014b0e4
- (void)getLocalPairingDataWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014b03c
- (void)getMacBeaconConfigWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014afdc
- (void)beaconingKeysWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014af10
- (void)beaconingStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010014ae58

@end

