//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12searchpartyd14CentralManager : NSObject
{
    MISSING_TYPE *queue;	// 8 = 0x8
    MISSING_TYPE *lock;	// 16 = 0x10
    MISSING_TYPE *connectingPeripherals;	// 24 = 0x18
    MISSING_TYPE *stateChangedSubject;	// 32 = 0x20
    MISSING_TYPE *peripheralDiscoveredSubject;	// 40 = 0x28
    MISSING_TYPE *connectionEventSubject;	// 48 = 0x30
    MISSING_TYPE *serviceIdentifiers;	// 56 = 0x38
    MISSING_TYPE *shouldScan;	// 64 = 0x40
    MISSING_TYPE *garbageCollectInterval;	// 72 = 0x48
    MISSING_TYPE *garbageCollectTimer;	// 80 = 0x50
    MISSING_TYPE *discovered;	// 88 = 0x58
    MISSING_TYPE *centralManager;	// 96 = 0x60
    MISSING_TYPE *pairingAgent;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x000000010032cad8
- (id)init;	// IMP=0x000000010032ca7c

@end

