//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VCPMADTaskProtocol-Protocol.h"

@class NSArray, PHPhotoLibrary, VCPDatabaseWriter;

@interface VCPEffectsAssetProcessingTask : NSObject <VCPMADTaskProtocol>
{
    CDUnknownBlockType _progressHandler;	// 8 = 0x8
    CDUnknownBlockType _completionHandler;	// 16 = 0x10
    NSArray *_assets;	// 24 = 0x18
    PHPhotoLibrary *_photoLibrary;	// 32 = 0x20
    VCPDatabaseWriter *_database;	// 40 = 0x28
    struct atomic<bool> _cancel;	// 48 = 0x30
    struct atomic<bool> _started;	// 49 = 0x31
}

+ (id)taskWithAssets:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 andCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100037b84
- (void).cxx_destruct;	// IMP=0x0000000100038cd8
- (void)cancel;	// IMP=0x0000000100038cc8
- (int)run;	// IMP=0x0000000100038b34
- (int)main;	// IMP=0x0000000100038898
- (int)processAsset:(id)arg1;	// IMP=0x000000010003840c
- (float)resourceRequirement;	// IMP=0x0000000100038404
- (void)dealloc;	// IMP=0x0000000100038344
- (int)persistResults:(id)arg1 forAsset:(id)arg2;	// IMP=0x0000000100037c40
- (id)initWithAssets:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 andCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010003798c

@end

