//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HBCloudSyncDeviceToCloudSyncUtility : NSObject
{
}

+ (id)_appIdsFromRootFolder:(id)arg1;	// IMP=0x00000001000696ec
+ (_Bool)parentFolderForApp:(id)arg1 containsOnlyNonRestorableApps:(id)arg2;	// IMP=0x0000000100069458
+ (_Bool)hasAllParametersForInstallation:(id)arg1;	// IMP=0x000000010006925c
+ (_Bool)isFolderSyncable:(id)arg1;	// IMP=0x0000000100068ff8
+ (_Bool)isAppSyncable:(id)arg1;	// IMP=0x0000000100068c18
+ (id)validateFolderStructureAndDiscardUnwantedItems:(id)arg1;	// IMP=0x0000000100068698
+ (id)appsWithChangedAlternateAppIconsFromAllApps:(id)arg1 appIdsToSyncedIconNames:(id)arg2;	// IMP=0x00000001000682c8
+ (id)updateItemOrderIdsForMovedItemsInFolder:(id)arg1 baseOrderId:(double)arg2;	// IMP=0x0000000100067d90
+ (id)updateItemOrderIdsForMovedItemsInFolder:(id)arg1;	// IMP=0x0000000100067d7c
+ (id)indicesForUnarrangedItemsInFolder:(id)arg1 subfolder:(CDUnknownBlockType)arg2;	// IMP=0x0000000100067904
+ (id)allItemsWithUpdatedOrderIdsFromFolder:(id)arg1 baseOrderId:(unsigned long long)arg2;	// IMP=0x0000000100067668
+ (_Bool)needToResetOrderingForItemsInFolder:(id)arg1;	// IMP=0x00000001000672a0
+ (_Bool)doItemOrderIdsCollideInFolder:(id)arg1;	// IMP=0x00000001000670d4
+ (id)deletedItemsListFromFolder:(id)arg1 itemsToParentMapping:(id)arg2;	// IMP=0x0000000100066ebc
+ (id)addedOrModifiedItemsFromRootFolderItems:(id)arg1 currentParentFolderLevel:(long long)arg2 itemsToParentMapping:(id)arg3;	// IMP=0x0000000100066814
+ (id)foldersWithChangedDisplayNamesFromFolder:(id)arg1 folderIdentifiersMappedToDisplayNames:(id)arg2;	// IMP=0x00000001000665b8
+ (id)folderIdentifiersMappedToDisplayNamesFromSyncedRecords:(id)arg1 existingMapping:(id)arg2;	// IMP=0x00000001000662b8
+ (id)folderIdentifiersMappedToDisplayNames:(id)arg1;	// IMP=0x00000001000660bc
+ (id)itemsToParentMappingFromItems:(id)arg1 currentFolderLevelIndex:(long long)arg2;	// IMP=0x0000000100065cf4
+ (id)itemsToParentMappingFromAddedRecords:(id)arg1 deletedRecordIDs:(id)arg2 existingItemsToParentMapping:(id)arg3 rootFolder:(id)arg4;	// IMP=0x0000000100065870
+ (void)initialize;	// IMP=0x000000010006580c

@end

