//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HBTopShelfAction.h"

@class HBTopShelfInstallApplicationAction, NSProgress;

@interface HBTopShelfInstallingApplicationAction : HBTopShelfAction
{
    NSProgress *_installApplicationProgress;	// 8 = 0x8
    HBTopShelfInstallApplicationAction *_installApplicationAction;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100041018
@property(retain, nonatomic) HBTopShelfInstallApplicationAction *installApplicationAction; // @synthesize installApplicationAction=_installApplicationAction;
- (id)installApplicationProgress;	// IMP=0x0000000100040fe4
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x0000000100040f4c
- (void)updateInstallApplicationPercentage:(double)arg1;	// IMP=0x0000000100040e04
- (id)initWithInstallApplicationAction:(id)arg1;	// IMP=0x0000000100040d4c

@end

