//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HBUITopShelfRottenTomatoesRating-Protocol.h"

@class NSString, TVTopShelfRottenTomatoesRating;

@interface HBTopShelfRottenTomatoesRating : NSObject <HBUITopShelfRottenTomatoesRating>
{
    TVTopShelfRottenTomatoesRating *_topShelfRating;	// 8 = 0x8
}

+ (long long)_freshnessTypeFromTopShelfFreshnessType:(unsigned long long)arg1;	// IMP=0x00000001000a06e0
- (void).cxx_destruct;	// IMP=0x00000001000a0708
@property(retain, nonatomic) TVTopShelfRottenTomatoesRating *topShelfRating; // @synthesize topShelfRating=_topShelfRating;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) double score;
@property(readonly, nonatomic) long long freshness;
- (id)initWithTopShelfRottenTomatoesRating:(id)arg1;	// IMP=0x00000001000a04bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

