//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TVCollectionViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class MPModelLibraryRequest, MPModelResponse, MPSectionedCollection, NSString, TVCollectionView, TVMusicLibraryHeaderView;
@protocol MPLazySectionedCollectionDataSource, UINavigationControllerDelegate;

@interface TVMusicMPRequestViewController : UIViewController <UICollectionViewDelegateFlowLayout, UINavigationControllerDelegate, TVCollectionViewDelegate, UICollectionViewDataSource>
{
    TVMusicLibraryHeaderView *_headerView;	// 8 = 0x8
    id <UINavigationControllerDelegate> _navigationControllerDelegate;	// 16 = 0x10
    UIViewController *_viewControllerWithZoomAnimation;	// 24 = 0x18
    MPModelResponse *_lastReceivedResponse;	// 32 = 0x20
    _Bool _visibleOnScreen;	// 40 = 0x28
    _Bool _shouldUpdateOnViewDidAppear;	// 41 = 0x29
    _Bool _showIndexBarTitles;	// 42 = 0x2a
    _Bool _preventPopWhenEmpty;	// 43 = 0x2b
    MPModelLibraryRequest *_libraryRequest;	// 48 = 0x30
    double _collectionViewTop;	// 56 = 0x38
    MPSectionedCollection *_mpResults;	// 64 = 0x40
    id <MPLazySectionedCollectionDataSource> _sectionedCollectionDataSource;	// 72 = 0x48
    long long _totalNumberOfItems;	// 80 = 0x50
    unsigned long long _lastFocusHeading;	// 88 = 0x58
    TVCollectionView *_collectionView;	// 96 = 0x60
    struct CGRect _focusedCellFrame;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x00000001000c3598
@property(readonly, nonatomic) TVMusicLibraryHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) TVCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) struct CGRect focusedCellFrame; // @synthesize focusedCellFrame=_focusedCellFrame;
@property(nonatomic) unsigned long long lastFocusHeading; // @synthesize lastFocusHeading=_lastFocusHeading;
@property(nonatomic) long long totalNumberOfItems; // @synthesize totalNumberOfItems=_totalNumberOfItems;
@property(retain, nonatomic) id <MPLazySectionedCollectionDataSource> sectionedCollectionDataSource; // @synthesize sectionedCollectionDataSource=_sectionedCollectionDataSource;
@property(retain, nonatomic) MPSectionedCollection *mpResults; // @synthesize mpResults=_mpResults;
@property(nonatomic) double collectionViewTop; // @synthesize collectionViewTop=_collectionViewTop;
@property(nonatomic) _Bool preventPopWhenEmpty; // @synthesize preventPopWhenEmpty=_preventPopWhenEmpty;
@property(nonatomic) _Bool showIndexBarTitles; // @synthesize showIndexBarTitles=_showIndexBarTitles;
@property(retain, nonatomic) MPModelLibraryRequest *libraryRequest; // @synthesize libraryRequest=_libraryRequest;
- (void)_modelResponseDidInvalidate:(id)arg1;	// IMP=0x00000001000c3400
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;	// IMP=0x00000001000c33c8
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x00000001000c3338
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x00000001000c3248
- (_Bool)updateWithModelResponse:(id)arg1;	// IMP=0x00000001000c3160
- (double)cellsTopMargin;	// IMP=0x00000001000c3138
- (struct CGSize)artworkSize;	// IMP=0x00000001000c3128
- (struct CGSize)cellSize;	// IMP=0x00000001000c3114
- (struct CGPoint)cellSpacing;	// IMP=0x00000001000c3100
- (void)didSelectItemAtIndexPath:(id)arg1;	// IMP=0x00000001000c30fc
- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000c30f4
- (void)handlePlayPauseCommand;	// IMP=0x00000001000c30f0
- (void)_updateHeaderViews:(id)arg1 forFocusContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x00000001000c2b9c
- (void)_adjustOffsetForHeaderViews:(id)arg1 withCells:(id)arg2;	// IMP=0x00000001000c2920
- (void)_configureCollectionViewLayout:(id)arg1;	// IMP=0x00000001000c282c
- (void)_handlePlayPause:(id)arg1;	// IMP=0x00000001000c2820
@property(readonly, nonatomic) NSString *cellIdentifier;
- (void)_processResponse:(id)arg1 error:(id)arg2;	// IMP=0x00000001000c247c
- (void)_performRequest;	// IMP=0x00000001000c2270
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;	// IMP=0x00000001000c215c
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x00000001000c2058
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000c1bc4
- (id)collectionView:(id)arg1 indexPathForIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x00000001000c19ec
- (id)indexTitlesForCollectionView:(id)arg1;	// IMP=0x00000001000c194c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000c193c
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x00000001000c18e4
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x00000001000c18dc
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000c18cc
- (void)_sortButtonSelected;	// IMP=0x00000001000c181c
- (void)_updateControls;	// IMP=0x00000001000c1690
- (double)headerVerticalOffset;	// IMP=0x00000001000c1684
- (void)setMpResults:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000c15fc
- (void)updateCollectionViewLayout;	// IMP=0x00000001000c1588
- (id)collectionViewLayout;	// IMP=0x00000001000c1530
- (void)setLibraryRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000c10e4
- (void)setTitle:(id)arg1;	// IMP=0x00000001000c101c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000c0f30
- (id)preferredFocusEnvironments;	// IMP=0x00000001000c0e94
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000c0e20
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000c0dd4
- (_Bool)showGradientMask;	// IMP=0x00000001000c0d98
- (void)viewDidLoad;	// IMP=0x00000001000c060c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000c03f0
- (id)initWithTitle:(id)arg1 libraryRequest:(id)arg2;	// IMP=0x00000001000c0354

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

