//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TVMusicLibrarySortUtilities : NSObject
{
}

+ (void)showSortMenuForLibraryRequest:(id)arg1 inViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000a934c
+ (id)_alertActionForSortType:(long long)arg1 inCategory:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000a9164
+ (id)_titleForSortType:(long long)arg1;	// IMP=0x00000001000a907c
+ (id)sortButton;	// IMP=0x00000001000a8fc8
+ (id)_sortDescriptorsForSortType:(long long)arg1;	// IMP=0x00000001000a88a0
+ (id)sortDescriptorsForRequest:(id)arg1;	// IMP=0x00000001000a8820
+ (id)_categoryForRequest:(id)arg1;	// IMP=0x00000001000a8634
+ (void)_setScopedMusicVideosForScopedAlbumSortType:(long long)arg1;	// IMP=0x00000001000a85e8
+ (void)_setCurrentSortType:(long long)arg1 forCategory:(id)arg2;	// IMP=0x00000001000a8534
+ (long long)_currentSortTypeForCategory:(id)arg1;	// IMP=0x00000001000a83dc
+ (long long)_legacySortTypeForCategory:(id)arg1;	// IMP=0x00000001000a833c
+ (_Bool)_hasLegacySortTypeForCategory:(id)arg1;	// IMP=0x00000001000a82a8
+ (long long)_defaultSortTypeForCategory:(id)arg1;	// IMP=0x00000001000a817c
+ (_Bool)canSortRequest:(id)arg1;	// IMP=0x00000001000a8140
+ (id)_supportedSortTypeDictionary;	// IMP=0x00000001000a7ff0

@end

