//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UAAdvertiser.h"

@class NSArray, UAUserActivityInfo;

@interface UAActivityReplayAdvertiser : UAAdvertiser
{
    NSArray *_advertisableItems;	// 8 = 0x8
    UAUserActivityInfo *_advertisedItem;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100008fb4
@property(retain) UAUserActivityInfo *advertisedItem; // @synthesize advertisedItem=_advertisedItem;
- (void)setItem:(id)arg1;	// IMP=0x0000000100008f44
- (void)setAdvertisableItems:(id)arg1;	// IMP=0x0000000100008e90
- (id)advertisingItems;	// IMP=0x0000000100008e84
- (_Bool)advertising;	// IMP=0x0000000100008e48
- (id)advertisableItems;	// IMP=0x0000000100008d9c
- (_Bool)active;	// IMP=0x0000000100008d90

@end

