//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UAAnalyticsEvent.h"

@class NSString;

@interface UAActivityWasSuggestedEvent : UAAnalyticsEvent
{
    NSString *_activityType;	// 8 = 0x8
    NSString *_bundleIdentifier;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010003f59c
@property(copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy) NSString *activityType; // @synthesize activityType=_activityType;
- (id)reportedActivityType;	// IMP=0x000000010003f504
- (void)sendEvent;	// IMP=0x000000010003f4a4
- (id)eventPayload;	// IMP=0x000000010003f398
- (id)eventName;	// IMP=0x000000010003f38c
- (id)initWithAnalyticsInfo:(id)arg1;	// IMP=0x000000010003f2b4

@end

