//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "TVCSTapToSetupManagerDelegate-Protocol.h"

@class NSString, TVCSTapToSetupManager, TVSettingsTapToSetupView;
@protocol TVSettingsTapToSetupViewControllerDelegate;

@interface TVSettingsTapToSetupViewController : TSKViewController <TVCSTapToSetupManagerDelegate>
{
    id <TVSettingsTapToSetupViewControllerDelegate> _delegate;	// 8 = 0x8
    TVSettingsTapToSetupView *_tapToSetupView;	// 16 = 0x10
    TVCSTapToSetupManager *_tapToSetupManager;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000b115c
@property(retain, nonatomic) TVCSTapToSetupManager *tapToSetupManager; // @synthesize tapToSetupManager=_tapToSetupManager;
@property(retain, nonatomic) TVSettingsTapToSetupView *tapToSetupView; // @synthesize tapToSetupView=_tapToSetupView;
@property(nonatomic) __weak id <TVSettingsTapToSetupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_presentAlertController:(id)arg1;	// IMP=0x00000001000b0ff0
- (void)tapToSetupManager:(id)arg1 presentErrorAlert:(id)arg2;	// IMP=0x00000001000b0fe0
- (void)tapToSetupManager:(id)arg1 didFailSetupWithError:(id)arg2;	// IMP=0x00000001000b0ca4
- (void)tapToSetupManagerDidFinishSetup:(id)arg1 deviceInfo:(id)arg2;	// IMP=0x00000001000b0a44
- (void)tapToSetupManager:(id)arg1 didBeginSetupWithDeviceName:(id)arg2 isNewFlow:(_Bool)arg3;	// IMP=0x00000001000b0950
- (void)tapToSetupManagerDidPromptToBeginSetup:(id)arg1;	// IMP=0x00000001000b0834
- (id)presentingControllerForTTSUManager:(id)arg1;	// IMP=0x00000001000b0830
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000b07d8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000b0780
- (void)viewDidLoad;	// IMP=0x00000001000b058c
- (void)dealloc;	// IMP=0x00000001000b0520
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000b04a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

