//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "PBSOSUpdateServiceDelegate-Protocol.h"

@class NSString, TVSUIOSUpdateView, UITapGestureRecognizer;

@interface TVSettingsOSRestoreViewController : UIViewController <PBSOSUpdateServiceDelegate>
{
    _Bool _cancelOnExit;	// 8 = 0x8
    TVSUIOSUpdateView *_progressView;	// 16 = 0x10
    UITapGestureRecognizer *_menuRecognizer;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010003aac4
@property(retain, nonatomic) UITapGestureRecognizer *menuRecognizer; // @synthesize menuRecognizer=_menuRecognizer;
@property(nonatomic) _Bool cancelOnExit; // @synthesize cancelOnExit=_cancelOnExit;
@property(retain, nonatomic) TVSUIOSUpdateView *progressView; // @synthesize progressView=_progressView;
- (void)_menuButtonAction:(id)arg1;	// IMP=0x000000010003a6e8
- (void)osUpdateServiceDidFinishApplyWithData:(id)arg1;	// IMP=0x000000010003a5dc
- (void)osUpdateServiceDidEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x000000010003a5d8
- (void)osUpdateServiceDidUpdateApplyProgressWithData:(id)arg1;	// IMP=0x000000010003a5d4
- (void)osUpdateServiceDidStartApplyWithData:(id)arg1;	// IMP=0x000000010003a524
- (void)osUpdateServiceDidStartRedownloadWithData:(id)arg1;	// IMP=0x000000010003a520
- (void)osUpdateServiceDidFinishDownloadWithData:(id)arg1;	// IMP=0x000000010003a3f0
- (void)osUpdateServiceDidUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x000000010003a0dc
- (void)osUpdateServiceDidStartDownloadWithData:(id)arg1;	// IMP=0x000000010003a0d8
- (void)osUpdateServiceDidFinishCheckWithData:(id)arg1;	// IMP=0x0000000100039fac
- (void)osUpdateServiceDidStartCheckWithData:(id)arg1;	// IMP=0x0000000100039f14
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100039e34
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100039cec
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100039b48

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

