//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TSKSettingItemEditingController-Protocol.h"

@class NSString, SFDeviceSetupTVLatencyService, TSKSettingItem, TVSettingsAudioLatencyCalibrationView, TVSettingsHDMIEnforcer, UIActivityIndicatorView;
@protocol TSKSettingItemEditingControllerDelegate;

@interface TVSettingsAudioLatencyCalibrationViewController : UIViewController <TSKSettingItemEditingController>
{
    TSKSettingItem *_editingItem;	// 8 = 0x8
    id <TSKSettingItemEditingControllerDelegate> _editingDelegate;	// 16 = 0x10
    TVSettingsHDMIEnforcer *_hdmiEnforcer;	// 24 = 0x18
    UIActivityIndicatorView *_activityIndicatorView;	// 32 = 0x20
    TVSettingsAudioLatencyCalibrationView *_calibrationView;	// 40 = 0x28
    SFDeviceSetupTVLatencyService *_audioLatencyEstimationService;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00000001000232e4
@property(retain, nonatomic) SFDeviceSetupTVLatencyService *audioLatencyEstimationService; // @synthesize audioLatencyEstimationService=_audioLatencyEstimationService;
@property(retain, nonatomic) TVSettingsAudioLatencyCalibrationView *calibrationView; // @synthesize calibrationView=_calibrationView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) TVSettingsHDMIEnforcer *hdmiEnforcer; // @synthesize hdmiEnforcer=_hdmiEnforcer;
@property(nonatomic) __weak id <TSKSettingItemEditingControllerDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
@property(retain, nonatomic) TSKSettingItem *editingItem; // @synthesize editingItem=_editingItem;
- (void)createSFService;	// IMP=0x00000001000225e0
- (void)dismiss;	// IMP=0x0000000100022450
- (void)dismissWithError:(id)arg1;	// IMP=0x0000000100022104
- (void)startCalibrationFlow;	// IMP=0x00000001000218f0
- (void)_applicationDidMoveToBackgroundNotification;	// IMP=0x000000010002182c
- (_Bool)stopNowPlayingApplicationIfNeeded;	// IMP=0x0000000100021554
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001000214cc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100020fd0
- (void)viewDidLoad;	// IMP=0x0000000100020ee8
- (id)init;	// IMP=0x0000000100020e8c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

