//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVSettingsWholeHomeAudioHomePickerViewControllerDelegate-Protocol.h"
#import "TVSettingsWholeHomeAudioRoomPickerViewControllerDelegate-Protocol.h"
#import "TVSettingsWholeHomeAudioSetupViewControllerDelegate-Protocol.h"

@class UINavigationController, UIViewController;

@interface TVSettingsHomeSetupController : NSObject <TVSettingsWholeHomeAudioSetupViewControllerDelegate, TVSettingsWholeHomeAudioRoomPickerViewControllerDelegate, TVSettingsWholeHomeAudioHomePickerViewControllerDelegate>
{
    UIViewController *_presentingViewController;	// 8 = 0x8
    UIViewController *_roomPickerInitialViewController;	// 16 = 0x10
    UINavigationController *_navigationController;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000ef17c
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak UIViewController *roomPickerInitialViewController; // @synthesize roomPickerInitialViewController=_roomPickerInitialViewController;
@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (id)_makeRoomPickerViewControllerWithHome:(id)arg1;	// IMP=0x00000001000ef0ac
- (id)_makeHomePickerViewController;	// IMP=0x00000001000ef06c
- (id)_makeRoomPickerViewController;	// IMP=0x00000001000eed68
- (void)wholeHomeAudioSetupViewControllerDidTransitionToUnconfiguredWithLocalAccessoryState:(id)arg1;	// IMP=0x00000001000eeca0
- (void)wholeHomeAudioSetupViewControllerDidTransitionToConfiguredState:(id)arg1;	// IMP=0x00000001000eec64
- (void)homePickerViewController:(id)arg1 didSelectHome:(id)arg2;	// IMP=0x00000001000eebc8
- (void)roomPickerViewControllerDidFinish:(id)arg1;	// IMP=0x00000001000eeb00
- (void)pushRoomPickerFromInitialViewController:(id)arg1;	// IMP=0x00000001000eea60
- (void)startSetupWithType:(long long)arg1 presentingViewController:(id)arg2;	// IMP=0x00000001000ee8f4

@end

