//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BKDisplayAnnotationController, BKDisplayAnnotationLocation, BKDisplayAnnotationRenderer, BKDisplayAnnotationStyleSheet, BKNamespaceNode, NSString;
@protocol BKDisplayAnnotationContent;

@interface BKDisplayAnnotation : NSObject
{
    BKDisplayAnnotationLocation *_location;	// 8 = 0x8
    BKDisplayAnnotationRenderer *_renderer;	// 16 = 0x10
    NSString *_section;	// 24 = 0x18
    long long _subnodeScreenEdgeTreatment;	// 32 = 0x20
    id <BKDisplayAnnotationContent> _content;	// 40 = 0x28
    BKDisplayAnnotationController *_annotationController;	// 48 = 0x30
    BKDisplayAnnotationStyleSheet *_styleSheet;	// 56 = 0x38
    BKNamespaceNode *_namespaceNode;	// 64 = 0x40
}

+ (id)new;	// IMP=0x0000000100057e80
+ (id)annotationWithRectangleSize:(struct CGSize)arg1;	// IMP=0x0000000100057d84
+ (id)annotationWithEllipseSize:(struct CGSize)arg1;	// IMP=0x0000000100057c88
+ (id)subannotationWithString:(id)arg1;	// IMP=0x0000000100057c28
+ (id)annotationWithString:(id)arg1;	// IMP=0x0000000100057b24
- (void).cxx_destruct;	// IMP=0x0000000100057ac0
@property(nonatomic) __weak BKNamespaceNode *namespaceNode; // @synthesize namespaceNode=_namespaceNode;
@property(retain, nonatomic) BKDisplayAnnotationStyleSheet *styleSheet; // @synthesize styleSheet=_styleSheet;
@property(nonatomic) __weak BKDisplayAnnotationController *annotationController; // @synthesize annotationController=_annotationController;
@property(retain, nonatomic) id <BKDisplayAnnotationContent> content; // @synthesize content=_content;
@property(nonatomic) long long subnodeScreenEdgeTreatment; // @synthesize subnodeScreenEdgeTreatment=_subnodeScreenEdgeTreatment;
@property(copy, nonatomic) NSString *section; // @synthesize section=_section;
@property(retain, nonatomic) BKDisplayAnnotationRenderer *renderer; // @synthesize renderer=_renderer;
@property(retain, nonatomic) BKDisplayAnnotationLocation *location; // @synthesize location=_location;
- (void)setStyleModifier:(id)arg1;	// IMP=0x00000001000579f0
- (void)modifyStyleSheet:(CDUnknownBlockType)arg1;	// IMP=0x00000001000579b8
- (void)setShapeSize:(struct CGSize)arg1;	// IMP=0x0000000100057964
- (void)setString:(id)arg1;	// IMP=0x00000001000578ac
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010005764c
- (id)description;	// IMP=0x000000010005763c
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x00000001000575bc
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x0000000100057568
- (id)succinctDescriptionBuilder;	// IMP=0x0000000100057550
- (id)succinctDescription;	// IMP=0x00000001000574fc
- (id)_init;	// IMP=0x0000000100057458
- (id)init;	// IMP=0x00000001000573d4

@end

