//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSTimer, TVSStateMachine;

@interface PBAXFeatureManager : NSObject
{
    NSArray *_pendingUpdates;	// 8 = 0x8
    CDUnknownBlockType _updateCompletion;	// 16 = 0x10
    NSTimer *_updateTimer;	// 24 = 0x18
    TVSStateMachine *_stateMachine;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x00000001001d48c0
- (void).cxx_destruct;	// IMP=0x00000001001d9894
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(copy, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(copy, nonatomic) CDUnknownBlockType updateCompletion; // @synthesize updateCompletion=_updateCompletion;
@property(copy, nonatomic) NSArray *pendingUpdates; // @synthesize pendingUpdates=_pendingUpdates;
- (void)_cancelPendingUpdates;	// IMP=0x00000001001d961c
- (void)_servicePendingUpdates;	// IMP=0x00000001001d913c
- (void)_applyUpdatesWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001d9010
- (id)_updatesForConfigurationOptions:(id)arg1;	// IMP=0x00000001001d78e0
- (id)_currentConfigOptions;	// IMP=0x00000001001d70d8
- (id)_handleSetDefaultConfiguration:(id)arg1;	// IMP=0x00000001001d6cc4
- (id)_handleSetSingleAppConfiguration:(id)arg1;	// IMP=0x00000001001d68ac
- (void)_initialzeStateMachine;	// IMP=0x00000001001d5ff8
- (void)updateWithConfiguration:(id)arg1;	// IMP=0x00000001001d5ed8
- (_Bool)handleAXShortcutEvent;	// IMP=0x00000001001d4a84
- (id)init;	// IMP=0x00000001001d49c0

@end

