//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE, NSArray, UIColor, _TtC6Arcade19BreakoutDetailsView;

@interface _TtC6Arcade31SmallBreakoutCollectionViewCell : UICollectionViewCell
{
    MISSING_TYPE *iconView;	// 8 = 0x8
    MISSING_TYPE *backgroundArtwork;	// 16 = 0x10
    MISSING_TYPE *detailsView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100196584
@property(nonatomic, readonly) _TtC6Arcade19BreakoutDetailsView *accessibilityDetailsView;
- (void)prepareForReuse;	// IMP=0x0000000100196468
- (void)layoutSubviews;	// IMP=0x000000010019643c
@property(nonatomic, readonly) _Bool canBecomeFocused;
@property(nonatomic, readonly) NSArray *preferredFocusEnvironments;
@property(nonatomic, retain) UIColor *backgroundColor;
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100195fc4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100195fa4

@end

