//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

@class MISSING_TYPE;

@interface _TtC6Arcade29StoreCollectionViewController : UICollectionViewController
{
    MISSING_TYPE *lifecycleObserver;	// 8 = 0x8
    MISSING_TYPE *gradientMaskLengths;	// 48 = 0x30
    MISSING_TYPE *registeredForApplicationDidBecomeActive;	// 80 = 0x50
    MISSING_TYPE *overlayView;	// 88 = 0x58
    MISSING_TYPE *collectionViewDelegate;	// 96 = 0x60
    MISSING_TYPE *collectionViewDataSource;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x00000001001a9e9c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001a9e30
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001001a9dac
- (id)initWithCollectionViewLayout:(id)arg1;	// IMP=0x00000001001a9d70
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x00000001001a9cdc
- (void)appExitedWhileAppeared;	// IMP=0x00000001001a9cb0
- (void)appEnteredWhileAppeared;	// IMP=0x00000001001a9c84
- (void)viewWillLayoutSubviews;	// IMP=0x00000001001a9bd4
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001001a9b8c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001001a9a5c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001001a97a0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001001a955c
- (void)viewDidLoad;	// IMP=0x00000001001a951c
- (void)loadView;	// IMP=0x00000001001a93a8

@end

