//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade25ShelfDisplayingFlowLayout.h"

@class MISSING_TYPE;

@interface _TtC6Arcade13ProductLayout : _TtC6Arcade25ShelfDisplayingFlowLayout
{
    MISSING_TYPE *topBackgroundFrame;	// 24 = 0x18
    MISSING_TYPE *bottomBackgroundFrame;	// 56 = 0x38
    MISSING_TYPE *pendingPrepareObserver;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00000001000a6fbc
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x00000001000a6edc
- (void)prepareLayout;	// IMP=0x00000001000a6d80
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000a6b74
- (id)init;	// IMP=0x00000001000a6b54

@end

