//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade31LargeBreakoutCollectionViewCell.h"

@interface _TtC6Arcade35LargeHeroBreakoutCollectionViewCell : _TtC6Arcade31LargeBreakoutCollectionViewCell
{
}

- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000934f8

@end

