//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade22ArcadeWelcomeItemsView : UIView
{
    MISSING_TYPE *layoutMetrics;	// 8 = 0x8
    MISSING_TYPE *itemViews;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00000001000a6648
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000a65e8
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x00000001000a64cc
- (void)layoutSubviews;	// IMP=0x00000001000a64a0
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000a6278

@end

