//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, _TtC6Arcade11ArtworkView, _TtC6Arcade16DynamicTypeLabel;

@interface _TtC6Arcade15SmallLockupView : UIView
{
    MISSING_TYPE *artworkView;	// 8 = 0x8
    MISSING_TYPE *titleLabel;	// 16 = 0x10
    MISSING_TYPE *subtitleLabel;	// 24 = 0x18
    MISSING_TYPE *metrics;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010009a544
@property(nonatomic, readonly) _TtC6Arcade16DynamicTypeLabel *accessibilitySubtitleLabel;
@property(nonatomic, readonly) _TtC6Arcade16DynamicTypeLabel *accessibilityTitleLabel;
@property(nonatomic, readonly) _TtC6Arcade11ArtworkView *accessibilityArtworkView;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010009a410
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010009a2a0
- (void)layoutSubviews;	// IMP=0x000000010009a274
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100099fec
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100099fcc

@end

