//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade25ProductBackgroundUberView : UIView
{
    MISSING_TYPE *videoContainer;	// 8 = 0x8
    MISSING_TYPE *artworkLoader;	// 16 = 0x10
    MISSING_TYPE *uberView;	// 24 = 0x18
    MISSING_TYPE *uberBlurView;	// 32 = 0x20
    MISSING_TYPE *uber;	// 40 = 0x28
    MISSING_TYPE *fallbackArtworkEffectView;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x00000001001c07c8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001001c1970
- (void)layoutSubviews;	// IMP=0x00000001001c12a0
- (void)dealloc;	// IMP=0x00000001001c072c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001c0670

@end

