//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC6Arcade24UpsellGridViewController : UIViewController
{
    MISSING_TYPE *objectGraph;	// 8 = 0x8
    MISSING_TYPE *presenter;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 24 = 0x18
    MISSING_TYPE *gridView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010017acf0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010017ad48
- (void)viewDidLoad;	// IMP=0x000000010017ac10
- (void)loadView;	// IMP=0x000000010017abac
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010017ab54

@end

