//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, _TtC6Arcade16DynamicTypeLabel;

@interface _TtC6Arcade19PrivacyCategoryView : UIView
{
    MISSING_TYPE *iconView;	// 8 = 0x8
    MISSING_TYPE *titleLabel;	// 16 = 0x10
    MISSING_TYPE *dataTypesLabel;	// 24 = 0x18
    MISSING_TYPE *category;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100026334
@property(nonatomic, readonly) _TtC6Arcade16DynamicTypeLabel *accessibilityDataTypesLabel;
@property(nonatomic, readonly) _TtC6Arcade16DynamicTypeLabel *accessibilityTitleLabel;
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x0000000100026178
- (void)layoutSubviews;	// IMP=0x0000000100025b8c
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100025520
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100025500

@end

