//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ACCFeatureServer.h"

#import "NSXPCListenerDelegate-Protocol.h"

@class NSMutableArray, NSString, NSXPCConnection;
@protocol ACCCommunicationsXPCClientProtocol;

@interface ACCCommunicationsServer : ACCFeatureServer <NSXPCListenerDelegate>
{
    NSMutableArray *_clientConnections;	// 40 = 0x28
    NSXPCConnection *_activeConnection;	// 48 = 0x30
    id <ACCCommunicationsXPCClientProtocol> _remoteObject;	// 56 = 0x38
}

+ (id)sharedServer;	// IMP=0x0000000100117114
- (void).cxx_destruct;	// IMP=0x0000000100117228
@property(retain, nonatomic) id <ACCCommunicationsXPCClientProtocol> remoteObject; // @synthesize remoteObject=_remoteObject;
@property(retain, nonatomic) NSXPCConnection *activeConnection; // @synthesize activeConnection=_activeConnection;
@property(retain, nonatomic) NSMutableArray *clientConnections; // @synthesize clientConnections=_clientConnections;
- (_Bool)sendDTMF:(int)arg1 forCallWithUUID:(id)arg2;	// IMP=0x0000000100116fcc
- (_Bool)updateMuteStatus:(_Bool)arg1;	// IMP=0x0000000100116f4c
- (_Bool)updateHoldStatus:(_Bool)arg1 forCallWithUUID:(id)arg2;	// IMP=0x0000000100116ea8
- (_Bool)mergeCalls;	// IMP=0x0000000100116e30
- (_Bool)swapCalls;	// IMP=0x0000000100116db8
- (_Bool)endAllCalls;	// IMP=0x0000000100116d40
- (_Bool)endCallWithAction:(int)arg1 callUUID:(id)arg2;	// IMP=0x0000000100116c9c
- (_Bool)acceptCallWithAction:(int)arg1 callUUID:(id)arg2;	// IMP=0x0000000100116bf8
- (_Bool)initiateRedial;	// IMP=0x0000000100116b80
- (_Bool)initiateCallToVoicemail;	// IMP=0x0000000100116b08
- (_Bool)initiateCallToDestination:(id)arg1 withService:(int)arg2 addressBookID:(id)arg3;	// IMP=0x0000000100116a48
- (void)triggerUpdateForListType:(int)arg1 coalesce:(_Bool)arg2;	// IMP=0x000000010011679c
- (void)triggerCommunicationsUpdate;	// IMP=0x000000010011656c
- (void)triggerCallStateUpdates;	// IMP=0x000000010011633c
- (void)sendUpdatedSubscriberList;	// IMP=0x0000000100116038
- (void)refreshClientData;	// IMP=0x0000000100115dc8
- (unsigned long long)invokeBlockOnClients:(CDUnknownBlockType)arg1 synchronous:(_Bool)arg2;	// IMP=0x00000001001159dc
- (_Bool)shouldAcceptXPCConnection:(id)arg1;	// IMP=0x00000001001159d4
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100115090
- (id)initWithXPCServiceName:(id)arg1 andFeatureNotification:(const char *)arg2;	// IMP=0x0000000100114ffc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

