//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSetupKit/TVSKViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BYLocaleDataSource, NSArray, NSDictionary, NSString, SATVInternationalUtility, SATVTableViewController, _SATVRegionOtherCountriesContainerView;

@interface SATVRegionViewController : TVSKViewController <UITableViewDelegate, UITableViewDataSource>
{
    CDUnknownBlockType _completionHandler;	// 8 = 0x8
    BYLocaleDataSource *_localeDataSource;	// 16 = 0x10
    _SATVRegionOtherCountriesContainerView *_otherCountriesContainer;	// 24 = 0x18
    NSArray *_otherCountriesSectionIndexTitles;	// 32 = 0x20
    NSDictionary *_otherCountriesSectionIndex;	// 40 = 0x28
    NSArray *_otherCountriesSectionIndexKeys;	// 48 = 0x30
    SATVInternationalUtility *_internationalUtility;	// 56 = 0x38
    SATVTableViewController *_tableViewController;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x000000010000a66c
@property(retain, nonatomic) SATVTableViewController *tableViewController; // @synthesize tableViewController=_tableViewController;
@property(retain, nonatomic) SATVInternationalUtility *internationalUtility; // @synthesize internationalUtility=_internationalUtility;
@property(copy, nonatomic) NSArray *otherCountriesSectionIndexKeys; // @synthesize otherCountriesSectionIndexKeys=_otherCountriesSectionIndexKeys;
@property(copy, nonatomic) NSDictionary *otherCountriesSectionIndex; // @synthesize otherCountriesSectionIndex=_otherCountriesSectionIndex;
@property(copy, nonatomic) NSArray *otherCountriesSectionIndexTitles; // @synthesize otherCountriesSectionIndexTitles=_otherCountriesSectionIndexTitles;
@property(retain, nonatomic) _SATVRegionOtherCountriesContainerView *otherCountriesContainer; // @synthesize otherCountriesContainer=_otherCountriesContainer;
@property(retain, nonatomic) BYLocaleDataSource *localeDataSource; // @synthesize localeDataSource=_localeDataSource;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x000000010000a538
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x000000010000a468
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010000a15c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x000000010000a090
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100009ef0
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100009ec4
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x0000000100009ebc
- (id)sectionIndexTitlesForTableView:(id)arg1;	// IMP=0x0000000100009eac
- (void)_configureSectionIndex;	// IMP=0x00000001000099d8
- (id)_countryAtSectionIndexPath:(id)arg1;	// IMP=0x0000000100009880
- (void)countryScanCompleted:(id)arg1;	// IMP=0x000000010000975c
- (id)preferredFocusEnvironments;	// IMP=0x00000001000096d4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000967c
- (void)viewDidLoad;	// IMP=0x0000000100009048
- (void)autoAdvance;	// IMP=0x0000000100008f5c
- (void)dealloc;	// IMP=0x0000000100008ee4
- (id)init;	// IMP=0x0000000100008e18

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

