//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVSKStep-Protocol.h"

@class NSString, SATVCloudConfigContainerViewController;
@protocol TVSKStepDelegate;

@interface SATVCloudConfigStep : NSObject <TVSKStep>
{
    id <TVSKStepDelegate> stepDelegate;	// 8 = 0x8
    SATVCloudConfigContainerViewController *_cloudConfigContainerViewController;	// 16 = 0x10
}

+ (id)stableIdentifier;	// IMP=0x0000000100058190
+ (void)initialize;	// IMP=0x000000010005812c
- (void).cxx_destruct;	// IMP=0x00000001000589e0
@property(retain, nonatomic) SATVCloudConfigContainerViewController *cloudConfigContainerViewController; // @synthesize cloudConfigContainerViewController=_cloudConfigContainerViewController;
@property(nonatomic) __weak id <TVSKStepDelegate> stepDelegate; // @synthesize stepDelegate;
- (void)_notifyTriggerStatusChangeAndReset:(_Bool)arg1;	// IMP=0x00000001000588ec
- (void)_completeStepWithCloudConfigSuccess:(_Bool)arg1;	// IMP=0x0000000100058850
- (void)_showCloudConfigContainerViewController;	// IMP=0x0000000100058584
- (_Bool)_shouldShowCloudConfigUI;	// IMP=0x00000001000584e8
- (void)autoAdvance;	// IMP=0x0000000100058454
- (id)executeStepForContext:(id)arg1;	// IMP=0x000000010005819c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

