//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SATVChoiceViewDataSource-Protocol.h"
#import "SATVChoiceViewDelegate-Protocol.h"

@class NSString, SATVChoiceView;
@protocol SATVConsentViewControllerDataSource, SATVConsentViewControllerDelegate;

@interface SATVConsentViewController : UIViewController <SATVChoiceViewDelegate, SATVChoiceViewDataSource>
{
    _Bool _useStackedConsentButtonLayout;	// 8 = 0x8
    _Bool _centeredHorizontally;	// 9 = 0x9
    SATVChoiceView *_choiceView;	// 16 = 0x10
    id <SATVConsentViewControllerDelegate> _delegate;	// 24 = 0x18
    id <SATVConsentViewControllerDataSource> _dataSource;	// 32 = 0x20
    double _maximumChoiceViewWidth;	// 40 = 0x28
    double _choiceViewHorizontalCenter;	// 48 = 0x30
    long long _choiceViewStyle;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001000492ac
@property(nonatomic, getter=isCenteredHorizontally) _Bool centeredHorizontally; // @synthesize centeredHorizontally=_centeredHorizontally;
@property(nonatomic) _Bool useStackedConsentButtonLayout; // @synthesize useStackedConsentButtonLayout=_useStackedConsentButtonLayout;
@property(readonly, nonatomic) long long choiceViewStyle; // @synthesize choiceViewStyle=_choiceViewStyle;
@property(nonatomic) double choiceViewHorizontalCenter; // @synthesize choiceViewHorizontalCenter=_choiceViewHorizontalCenter;
@property(nonatomic) double maximumChoiceViewWidth; // @synthesize maximumChoiceViewWidth=_maximumChoiceViewWidth;
@property(nonatomic) __weak id <SATVConsentViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SATVConsentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SATVChoiceView *choiceView; // @synthesize choiceView=_choiceView;
- (void)didSelectAuxiliaryButton;	// IMP=0x000000010004913c
- (void)didSelectFooterButton;	// IMP=0x00000001000490d8
- (void)didSelectChoice:(unsigned long long)arg1;	// IMP=0x0000000100049064
- (id)auxiliaryButtonViewForChoiceView:(id)arg1;	// IMP=0x0000000100048fe4
- (id)footerButtonViewForChoiceView:(id)arg1;	// IMP=0x0000000100048f64
- (id)auxiliaryButtonTextForChoiceView:(id)arg1;	// IMP=0x0000000100048ee4
- (id)footerButtonTextForChoiceView:(id)arg1;	// IMP=0x0000000100048e64
- (id)footnoteTextForChoiceView:(id)arg1;	// IMP=0x0000000100048de4
- (id)choiceHeaderButtonTextForChoiceView:(id)arg1;	// IMP=0x0000000100048d64
- (id)attributedSubtitleStringForChoiceView;	// IMP=0x0000000100048cf8
- (id)subtitleTextForChoiceView:(id)arg1;	// IMP=0x0000000100048c7c
- (id)titleTextForChoiceView:(id)arg1;	// IMP=0x0000000100048c20
- (id)choiceView:(id)arg1 textForChoice:(unsigned long long)arg2;	// IMP=0x0000000100048b90
- (id)preferredFocusEnvironments;	// IMP=0x0000000100048ae4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100048988
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100048788
- (void)loadView;	// IMP=0x000000010004864c
- (id)initWithChoiceViewStyle:(long long)arg1;	// IMP=0x00000001000485fc
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100048558

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

