//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSetupKit/TVSKViewController.h>

#import "SATVConsentViewControllerDataSource-Protocol.h"
#import "SATVConsentViewControllerDelegate-Protocol.h"

@class NSString, OBPrivacyLinkController;

@interface SATVSiriAndDictationViewController : TVSKViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource>
{
    CDUnknownBlockType _completionHandler;	// 8 = 0x8
    OBPrivacyLinkController *_privacyLink;	// 16 = 0x10
}

+ (void)initialize;	// IMP=0x000000010001cac8
- (void).cxx_destruct;	// IMP=0x000000010001d1c0
@property(retain, nonatomic) OBPrivacyLinkController *privacyLink; // @synthesize privacyLink=_privacyLink;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void)_enableSiriAndDictation:(_Bool)arg1;	// IMP=0x000000010001d0fc
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x000000010001d084
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x000000010001d00c
- (id)footerButtonViewForConsentViewController:(id)arg1;	// IMP=0x000000010001cff4
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010001cf74
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010001cef4
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x000000010001ce74
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x000000010001cdf4
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010001cd8c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010001cd34
- (void)viewDidLoad;	// IMP=0x000000010001cc2c
- (void)dealloc;	// IMP=0x000000010001cbb4
- (id)init;	// IMP=0x000000010001cb2c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

