//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (TVPreviewTableViewControllerAdditions)
- (CDUnknownBlockType)backdropViewHideStateNeedsUpdatingBlock;	// IMP=0x00000001000769e0
- (void)setBackdropViewHideStateNeedsUpdatingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000769dc
- (_Bool)shouldHideBackdropView;	// IMP=0x00000001000769d4
- (_Bool)shouldAnimatePreviewView;	// IMP=0x00000001000769cc
@end

