//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NRBabelSource.h"

@interface NRBabelSourceLocal : NRBabelSource
{
}

- (void)resetGCTimer;	// IMP=0x00000001000743f8
- (void)setupGCTimer;	// IMP=0x00000001000743f4
- (_Bool)isNewDistanceFeasibleWithSeqno:(unsigned short)arg1 metric:(unsigned short)arg2;	// IMP=0x00000001000743ec
- (unsigned short)seqno;	// IMP=0x00000001000743a0
- (id)descriptionWithoutMetric;	// IMP=0x0000000100074394
- (id)description;	// IMP=0x0000000100074318
- (id)initWithPrefix:(id)arg1 instance:(id)arg2;	// IMP=0x0000000100074264

@end

