//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NRBabelRoute.h"

@interface NRBabelRouteLocal : NRBabelRoute
{
}

- (void)applyUsingSystem;	// IMP=0x00000001000752f4
- (void)resetExpiryTimer;	// IMP=0x00000001000752f0
- (id)initWithPrefix:(id)arg1 instance:(id)arg2;	// IMP=0x000000010007522c
- (unsigned short)metric;	// IMP=0x0000000100075224
- (unsigned short)seqno;	// IMP=0x00000001000751d8

@end

