//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NRBTLinkPreferencesAgentDelegate-Protocol.h"
#import "NRLinkDelegate-Protocol.h"
#import "NRLinkManagerBluetoothDelegate-Protocol.h"
#import "NRLinkManagerQuickRelayDelegate-Protocol.h"
#import "NRLinkManagerWiFiDelegate-Protocol.h"
#import "NRPhoneCallRelayAgentDelegate-Protocol.h"
#import "NRQuickRelayAgentDelegate-Protocol.h"

@class NRAnalyticsPhoneCallRelay, NRAnalyticsPreferWiFi, NRBTLinkPreferencesAgent, NRCompanionLinkViabilityAgent, NRDevicePreferencesManager, NRLink, NRQuickRelayAgent, NSData, NSMutableArray, NSMutableSet, NSString, NSUUID, NWAddressEndpoint;
@protocol OS_dispatch_queue;

@interface NRDDeviceConductor : NSObject <NRLinkDelegate, NRLinkManagerWiFiDelegate, NRLinkManagerBluetoothDelegate, NRLinkManagerQuickRelayDelegate, NRPhoneCallRelayAgentDelegate, NRQuickRelayAgentDelegate, NRBTLinkPreferencesAgentDelegate>
{
    _Bool _isEnabled;	// 8 = 0x8
    _Bool _preferWiFiRequest;	// 9 = 0x9
    _Bool _deviceSetupInProgress;	// 10 = 0xa
    _Bool _bringUpWiFiImmediately;	// 11 = 0xb
    _Bool _wifiBringUpTimeoutSet;	// 12 = 0xc
    _Bool _preferwiFiTimeoutSet;	// 13 = 0xd
    _Bool _helloMessageSent;	// 14 = 0xe
    _Bool _helloMessageReceivedOnce;	// 15 = 0xf
    _Bool _disableRangeExtension;	// 16 = 0x10
    _Bool _disablePreferWiFi;	// 17 = 0x11
    _Bool _forceSendWiFiEndpointOnce;	// 18 = 0x12
    _Bool _pendingPreferWiFiRequest;	// 19 = 0x13
    _Bool _peerDeviceIsAsleep;	// 20 = 0x14
    _Bool _peerDeviceIsNearby;	// 21 = 0x15
    _Bool _hasPhoneCallRelayRequest;	// 22 = 0x16
    _Bool _hasQuickRelayRequest;	// 23 = 0x17
    _Bool _apsIsConnected;	// 24 = 0x18
    _Bool _hasReceivedFirstAPSIsConnectedUpdate;	// 25 = 0x19
    _Bool _didForceWoWMode;	// 26 = 0x1a
    _Bool _alwaysOnWiFiQueryComplete;	// 27 = 0x1b
    _Bool _alwaysOnWiFiUpdateSent;	// 28 = 0x1c
    unsigned char _latestPreferWiFiRequestType;	// 29 = 0x1d
    unsigned char _lastPrimaryLinkType;	// 30 = 0x1e
    unsigned short _deviceLinkInnerVersion;	// 32 = 0x20
    NSUUID *_nrUUID;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
    NSMutableSet *_availableLinks;	// 56 = 0x38
    NSMutableArray *_requests;	// 64 = 0x40
    NRLink *_primaryLink;	// 72 = 0x48
    NWAddressEndpoint *_lastSentWiFiEndpoint;	// 80 = 0x50
    NSData *_lastSentWiFiSignature;	// 88 = 0x58
    NSMutableSet *_deviceMonitorConnections;	// 96 = 0x60
    NSMutableSet *_deviceSetupInProgressConnections;	// 104 = 0x68
    NRDevicePreferencesManager *_devicePreferencesManager;	// 112 = 0x70
    NRQuickRelayAgent *_quickRelayAgent;	// 120 = 0x78
    NRBTLinkPreferencesAgent *_btLinkPreferencesAgent;	// 128 = 0x80
    unsigned long long _peerDeviceIsNearbyUpdateCounter;	// 136 = 0x88
    NSUUID *_forcedWoWUUID;	// 144 = 0x90
    NSString *_policyIdentifier;	// 152 = 0x98
    unsigned long long _latestWiFiAddressUpdateMsgIdentifier;	// 160 = 0xa0
    unsigned long long _latestPreferWiFiRequestMsgIdentifier;	// 168 = 0xa8
    unsigned long long _latestPreferWiFiAckMsgIdentifier;	// 176 = 0xb0
    NRAnalyticsPreferWiFi *_preferWiFiAnalytics;	// 184 = 0xb8
    NRAnalyticsPhoneCallRelay *_phoneCallRelayAnalytics;	// 192 = 0xc0
    NRCompanionLinkViabilityAgent *_companionLinkViabilityAgent;	// 200 = 0xc8
    unsigned long long _companionLinkViableCounter;	// 208 = 0xd0
    unsigned long long _rejectPreferWiFiRequestTime;	// 216 = 0xd8
}

+ (id)copyDeviceMonitorStatusForOrphanWithNRUUID:(id)arg1 replyDict:(id)arg2;	// IMP=0x000000010008a820
+ (id)createDeviceMonitorDictWithNRUUID:(id)arg1 isNearby:(_Bool)arg2 isConnected:(_Bool)arg3 isCloudConnected:(_Bool)arg4 isAsleep:(_Bool)arg5 isClassCConnected:(_Bool)arg6 linkType:(unsigned char)arg7 replyDict:(id)arg8;	// IMP=0x000000010008a574
- (void).cxx_destruct;	// IMP=0x0000000100089514
@property(nonatomic) unsigned long long rejectPreferWiFiRequestTime; // @synthesize rejectPreferWiFiRequestTime=_rejectPreferWiFiRequestTime;
@property(nonatomic) unsigned char lastPrimaryLinkType; // @synthesize lastPrimaryLinkType=_lastPrimaryLinkType;
@property(nonatomic) unsigned long long companionLinkViableCounter; // @synthesize companionLinkViableCounter=_companionLinkViableCounter;
@property(retain, nonatomic) NRCompanionLinkViabilityAgent *companionLinkViabilityAgent; // @synthesize companionLinkViabilityAgent=_companionLinkViabilityAgent;
@property(retain, nonatomic) NRAnalyticsPhoneCallRelay *phoneCallRelayAnalytics; // @synthesize phoneCallRelayAnalytics=_phoneCallRelayAnalytics;
@property(retain, nonatomic) NRAnalyticsPreferWiFi *preferWiFiAnalytics; // @synthesize preferWiFiAnalytics=_preferWiFiAnalytics;
@property(nonatomic) unsigned long long latestPreferWiFiAckMsgIdentifier; // @synthesize latestPreferWiFiAckMsgIdentifier=_latestPreferWiFiAckMsgIdentifier;
@property(nonatomic) unsigned long long latestPreferWiFiRequestMsgIdentifier; // @synthesize latestPreferWiFiRequestMsgIdentifier=_latestPreferWiFiRequestMsgIdentifier;
@property(nonatomic) unsigned long long latestWiFiAddressUpdateMsgIdentifier; // @synthesize latestWiFiAddressUpdateMsgIdentifier=_latestWiFiAddressUpdateMsgIdentifier;
@property(retain, nonatomic) NSString *policyIdentifier; // @synthesize policyIdentifier=_policyIdentifier;
@property(nonatomic) unsigned char latestPreferWiFiRequestType; // @synthesize latestPreferWiFiRequestType=_latestPreferWiFiRequestType;
@property(nonatomic) _Bool alwaysOnWiFiUpdateSent; // @synthesize alwaysOnWiFiUpdateSent=_alwaysOnWiFiUpdateSent;
@property(nonatomic) _Bool alwaysOnWiFiQueryComplete; // @synthesize alwaysOnWiFiQueryComplete=_alwaysOnWiFiQueryComplete;
@property(retain, nonatomic) NSUUID *forcedWoWUUID; // @synthesize forcedWoWUUID=_forcedWoWUUID;
@property(nonatomic) _Bool didForceWoWMode; // @synthesize didForceWoWMode=_didForceWoWMode;
@property(nonatomic) _Bool hasReceivedFirstAPSIsConnectedUpdate; // @synthesize hasReceivedFirstAPSIsConnectedUpdate=_hasReceivedFirstAPSIsConnectedUpdate;
@property(nonatomic) _Bool apsIsConnected; // @synthesize apsIsConnected=_apsIsConnected;
@property(nonatomic) _Bool hasQuickRelayRequest; // @synthesize hasQuickRelayRequest=_hasQuickRelayRequest;
@property(nonatomic) _Bool hasPhoneCallRelayRequest; // @synthesize hasPhoneCallRelayRequest=_hasPhoneCallRelayRequest;
@property(nonatomic) unsigned long long peerDeviceIsNearbyUpdateCounter; // @synthesize peerDeviceIsNearbyUpdateCounter=_peerDeviceIsNearbyUpdateCounter;
@property(nonatomic) _Bool peerDeviceIsNearby; // @synthesize peerDeviceIsNearby=_peerDeviceIsNearby;
@property(nonatomic) _Bool peerDeviceIsAsleep; // @synthesize peerDeviceIsAsleep=_peerDeviceIsAsleep;
@property(nonatomic) _Bool pendingPreferWiFiRequest; // @synthesize pendingPreferWiFiRequest=_pendingPreferWiFiRequest;
@property(nonatomic) _Bool forceSendWiFiEndpointOnce; // @synthesize forceSendWiFiEndpointOnce=_forceSendWiFiEndpointOnce;
@property(nonatomic) _Bool disablePreferWiFi; // @synthesize disablePreferWiFi=_disablePreferWiFi;
@property(nonatomic) _Bool disableRangeExtension; // @synthesize disableRangeExtension=_disableRangeExtension;
@property(nonatomic) _Bool helloMessageReceivedOnce; // @synthesize helloMessageReceivedOnce=_helloMessageReceivedOnce;
@property(nonatomic) _Bool helloMessageSent; // @synthesize helloMessageSent=_helloMessageSent;
@property(nonatomic) _Bool preferwiFiTimeoutSet; // @synthesize preferwiFiTimeoutSet=_preferwiFiTimeoutSet;
@property(nonatomic) _Bool wifiBringUpTimeoutSet; // @synthesize wifiBringUpTimeoutSet=_wifiBringUpTimeoutSet;
@property(nonatomic) _Bool bringUpWiFiImmediately; // @synthesize bringUpWiFiImmediately=_bringUpWiFiImmediately;
@property(nonatomic) _Bool deviceSetupInProgress; // @synthesize deviceSetupInProgress=_deviceSetupInProgress;
@property(nonatomic) _Bool preferWiFiRequest; // @synthesize preferWiFiRequest=_preferWiFiRequest;
@property(nonatomic) _Bool isEnabled; // @synthesize isEnabled=_isEnabled;
@property(nonatomic, getter=getDeviceLinkInnerVersion) unsigned short deviceLinkInnerVersion; // @synthesize deviceLinkInnerVersion=_deviceLinkInnerVersion;
@property(retain, nonatomic) NRBTLinkPreferencesAgent *btLinkPreferencesAgent; // @synthesize btLinkPreferencesAgent=_btLinkPreferencesAgent;
@property(retain, nonatomic) NRQuickRelayAgent *quickRelayAgent; // @synthesize quickRelayAgent=_quickRelayAgent;
@property(retain, nonatomic) NRDevicePreferencesManager *devicePreferencesManager; // @synthesize devicePreferencesManager=_devicePreferencesManager;
@property(retain, nonatomic) NSMutableSet *deviceSetupInProgressConnections; // @synthesize deviceSetupInProgressConnections=_deviceSetupInProgressConnections;
@property(retain, nonatomic) NSMutableSet *deviceMonitorConnections; // @synthesize deviceMonitorConnections=_deviceMonitorConnections;
@property(retain, nonatomic) NSData *lastSentWiFiSignature; // @synthesize lastSentWiFiSignature=_lastSentWiFiSignature;
@property(retain, nonatomic) NWAddressEndpoint *lastSentWiFiEndpoint; // @synthesize lastSentWiFiEndpoint=_lastSentWiFiEndpoint;
@property(retain, nonatomic) NRLink *primaryLink; // @synthesize primaryLink=_primaryLink;
@property(retain, nonatomic) NSMutableArray *requests; // @synthesize requests=_requests;
@property(retain, nonatomic) NSMutableSet *availableLinks; // @synthesize availableLinks=_availableLinks;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSUUID *nrUUID; // @synthesize nrUUID=_nrUUID;
- (void)measureBTLatencyWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000890bc
- (id)wifiManager;	// IMP=0x0000000100089060
- (void)handleAlwaysOnWiFiQueryComplete;	// IMP=0x0000000100088fe4
- (void)removeDevicePreferencesManagerConnection:(id)arg1;	// IMP=0x0000000100088f44
- (void)setPolicyTrafficClasses:(id)arg1 forConnection:(id)arg2;	// IMP=0x0000000100088e80
- (void)setLinkPreferences:(id)arg1 forConnection:(id)arg2;	// IMP=0x0000000100088dbc
- (void)removeDeviceMonitorConnection:(id)arg1;	// IMP=0x0000000100088d1c
- (void)addDeviceMonitorConnection:(id)arg1;	// IMP=0x0000000100088c7c
- (void)removeDeviceSetupInProgressConnection:(id)arg1;	// IMP=0x0000000100088b88
- (void)addDeviceSetupInProgressConnection:(id)arg1;	// IMP=0x0000000100088a94
- (void)reportEvent:(int)arg1;	// IMP=0x0000000100088a84
- (void)reportEvent:(int)arg1 detailsFormat:(id)arg2;	// IMP=0x00000001000889f0
- (void)reportEvent:(int)arg1 details:(id)arg2;	// IMP=0x00000001000889e0
- (void)deviceHasBTLinkUpgradeRequest:(_Bool)arg1;	// IMP=0x0000000100088868
- (void)deviceHasQuickRelayRequest:(id)arg1 hasQuickRelayRequest:(_Bool)arg2;	// IMP=0x0000000100088624
- (void)apsIsConnected:(_Bool)arg1;	// IMP=0x0000000100088500
- (void)deviceHasPhoneCallRelayRequest:(_Bool)arg1;	// IMP=0x00000001000882dc
- (void)pipeDidConnectForNRUUID:(_Bool)arg1 nrUUID:(id)arg2;	// IMP=0x0000000100088048
- (void)linkPeerIsAsleep:(id)arg1 isAsleep:(_Bool)arg2;	// IMP=0x0000000100087fac
- (void)linkDidReceiveData:(id)arg1 data:(id)arg2;	// IMP=0x00000001000876dc
- (void)linkIsUnavailable:(id)arg1;	// IMP=0x0000000100087230
- (void)linkIsSuspended:(id)arg1;	// IMP=0x000000010008704c
- (void)linkIsReady:(id)arg1;	// IMP=0x0000000100086cb8
- (void)linkIsAvailable:(id)arg1;	// IMP=0x00000001000866b4
- (void)sendDeviceLinkStateOnLink:(id)arg1;	// IMP=0x00000001000865cc
- (void)addStopQuickRelayRequest;	// IMP=0x0000000100086514
- (unsigned int)cancelAllLinks;	// IMP=0x0000000100086330
- (void)removePoliciesForLink:(id)arg1;	// IMP=0x00000001000862ec
- (void)setIPTunnelPolicyForLink:(id)arg1;	// IMP=0x0000000100083480
- (void)resumeLinkOfType:(unsigned char)arg1;	// IMP=0x00000001000832e4
- (void)suspendLinkOfType:(unsigned char)arg1;	// IMP=0x0000000100083180
- (void)sendHelloWithPreferredLink:(id)arg1 forced:(_Bool)arg2;	// IMP=0x0000000100083084
- (void)rejectPreferWiFiRequest:(id)arg1;	// IMP=0x0000000100082efc
- (void)updatePrimaryLink;	// IMP=0x0000000100082c6c
- (void)serviceRequests;	// IMP=0x0000000100082638
- (void)processRequest:(id)arg1;	// IMP=0x00000001000817f0
- (_Bool)hasServiceRequestOfType:(unsigned char)arg1;	// IMP=0x0000000100081698
- (void)removeRequestOfType:(unsigned char)arg1;	// IMP=0x0000000100081404
- (void)removeRequest:(id)arg1;	// IMP=0x0000000100081364
- (void)addRequest:(id)arg1;	// IMP=0x0000000100080ff8
- (void)refreshCompanionProxyAgent;	// IMP=0x0000000100080e84
- (id)copyStatusString;	// IMP=0x000000010008099c
- (void)enableWiFiAutojoin;	// IMP=0x00000001000808ac
- (void)disableWiFiAutojoinIfApplicable;	// IMP=0x00000001000807dc
- (void)updateWiFiAssertionReason;	// IMP=0x0000000100080704
- (void)forceWoWMode;	// IMP=0x0000000100080700
- (_Bool)isDeviceNearby;	// IMP=0x00000001000806a0
- (_Bool)isAlwaysOnWiFiSupported;	// IMP=0x000000010008051c
- (void)setWiFiLinkBringUpTimeout;	// IMP=0x0000000100080384
- (void)setPreferWiFiTimeout;	// IMP=0x0000000100080218
- (_Bool)sendPreferWiFiRequest:(_Bool)arg1 immediately:(_Bool)arg2 removeIfFailed:(_Bool)arg3 preferLinkType:(unsigned char)arg4 isAck:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x0000000100080088
- (_Bool)isLastSentWiFiEndpointValid;	// IMP=0x000000010007ffe0
- (void)setWiFiRangeExtensionAllowedForTesting:(_Bool)arg1;	// IMP=0x000000010007fdf0
- (void)setWiFiState:(_Bool)arg1;	// IMP=0x000000010007fbf0
- (void)setBringUpWiFiImmediatelyInner:(_Bool)arg1 timeout:(unsigned short)arg2 addSuspendBTRequest:(_Bool)arg3;	// IMP=0x000000010007f8e8
- (id)copyPrimaryLink;	// IMP=0x000000010007f8b0
- (id)copyLinkOfType:(unsigned char)arg1;	// IMP=0x000000010007f754
- (void)sendPreferWiFiRequestAck;	// IMP=0x000000010007f3a0
- (void)createCmpLnkViabilityAgentIfApplicable;	// IMP=0x000000010007f314
- (void)addSuspendBluetoothRequestWhenWiFiAvailable;	// IMP=0x000000010007f25c
- (void)updateDeviceMonitorConnections;	// IMP=0x000000010007f004
- (id)copyDeviceMonitorStatusWithReplyDict:(id)arg1;	// IMP=0x000000010007edb0
- (void)updateCompanionLinkViability;	// IMP=0x000000010007ea8c
- (void)startQuickRelayLinkIfApplicable;	// IMP=0x000000010007e918
- (void)cancelConductor;	// IMP=0x000000010007e2ec
- (void)startConductor;	// IMP=0x000000010007dce4
- (id)initConductorWithNRUUID:(id)arg1 queue:(id)arg2;	// IMP=0x000000010007d92c
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

