//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKService.h"

#import "GKAnalyticsService-Protocol.h"

@class NSString;

@interface GKAnalyticsService : GKService <GKAnalyticsService>
{
}

+ (unsigned long long)requiredEntitlements;	// IMP=0x00000001000e094c
+ (Class)interfaceClass;	// IMP=0x00000001000e0940
- (void)respondedToBulletin:(id)arg1;	// IMP=0x00000001000e099c
- (void)purchasedGame:(id)arg1;	// IMP=0x00000001000e0998
- (void)stoppedPlayingGame;	// IMP=0x00000001000e0994
- (void)beganPlayingGame;	// IMP=0x00000001000e0990
- (void)quitMatch:(id)arg1 withOutcome:(long long)arg2;	// IMP=0x00000001000e098c
- (void)disconnectedMatchWithID:(id)arg1;	// IMP=0x00000001000e0988
- (void)rematchedWithMatchRequest:(id)arg1;	// IMP=0x00000001000e0984
- (void)sentMatchRequest:(id)arg1;	// IMP=0x00000001000e0980
- (void)declinedInvite:(id)arg1;	// IMP=0x00000001000e097c
- (void)declinedInviteForTurnBasedMatch:(id)arg1;	// IMP=0x00000001000e0978
- (void)acceptedInviteForTurnBasedMatch:(id)arg1;	// IMP=0x00000001000e0974
- (void)acceptedInvite:(id)arg1;	// IMP=0x00000001000e0970
- (void)completedChallenge:(id)arg1;	// IMP=0x00000001000e096c
- (void)wantsToPlayChallenge:(id)arg1;	// IMP=0x00000001000e0968
- (void)declinedChallenge:(id)arg1;	// IMP=0x00000001000e0964
- (void)postedScore:(id)arg1;	// IMP=0x00000001000e0960
- (void)updatedAchievement:(id)arg1;	// IMP=0x00000001000e095c
- (_Bool)requiresAuthentication;	// IMP=0x00000001000e0954

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

