//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GKDatabaseConnectionFactory : NSObject
{
    NSString *_databasePath;	// 8 = 0x8
}

+ (id)factoryWithDatabaseName:(id)arg1 environment:(long long)arg2;	// IMP=0x0000000100136e8c
+ (id)pathForDatabaseName:(id)arg1 environment:(long long)arg2;	// IMP=0x0000000100136e24
+ (id)directoryForEnvironment:(long long)arg1;	// IMP=0x0000000100136d74
@property(copy, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
- (id)connectionForWriterWithName:(id)arg1;	// IMP=0x0000000100136fcc
- (id)connectionForReaderWithName:(id)arg1;	// IMP=0x0000000100136fc4
- (void)dealloc;	// IMP=0x0000000100136f7c
- (id)initWithPath:(id)arg1;	// IMP=0x0000000100136f1c

@end

