//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKEntitlements : NSObject
{
    unsigned long long _entitlements;	// 8 = 0x8
}

- (_Bool)_shouldBypasAuthenticationForConnection:(id)arg1;	// IMP=0x00000001000cf8fc
- (_Bool)hasAnyPrivateEntitlement;	// IMP=0x00000001000cf8e8
- (_Bool)hasAnyEntitlement;	// IMP=0x00000001000cf8e0
- (_Bool)hasEntitlements:(unsigned long long)arg1;	// IMP=0x00000001000cf8d0
- (id)fullEntitlements;	// IMP=0x00000001000cf8c0
- (id)initWithConnection:(id)arg1;	// IMP=0x00000001000cf7d0
- (unsigned long long)_valuesForEntitlement:(id)arg1 forConnection:(id)arg2;	// IMP=0x00000001000cf610
- (id)description;	// IMP=0x00000001000cf41c
- (unsigned long long)_entitlementForName:(id)arg1;	// IMP=0x00000001000cf318

@end

