//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NIServerBaseSession.h"

@class NINearbyUpdatesEngine, NSObject, _NIWiFiRangingTestConfiguration;
@protocol OS_dispatch_queue;

@interface _NIServerTestWiFiOnlySession : NIServerBaseSession
{
    NINearbyUpdatesEngine *_updatesEngine;	// 8 = 0x8
    struct unique_ptr<WiFiRanging::Session, std::__1::default_delete<WiFiRanging::Session>> _wifiRangingSession;	// 16 = 0x10
    _Bool _shouldDeliverUpdates;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_clientQueue;	// 32 = 0x20
    _NIWiFiRangingTestConfiguration *_configuration;	// 40 = 0x28
}

- (id).cxx_construct;	// IMP=0x00000001001c7548
- (void).cxx_destruct;	// IMP=0x00000001001c74e0
@property(readonly) _NIWiFiRangingTestConfiguration *configuration; // @synthesize configuration=_configuration;
- (void)cycleElapsed;	// IMP=0x00000001001c74c0
- (void)peerInactivityPeriodExceeded:(id)arg1;	// IMP=0x00000001001c72c4
- (void)wifiRangingRangeError:(const int *)arg1;	// IMP=0x00000001001c6ff8
- (void)wifiRangingRangeResults:(const vector_7b261d6f *)arg1;	// IMP=0x00000001001c6fe0
- (void)invalidate;	// IMP=0x00000001001c6f14
- (id)_disableWiFiAndReturnError;	// IMP=0x00000001001c6ec8
- (void)_handleFailedToRemovePeer;	// IMP=0x00000001001c6df8
- (void)_handleFailedToAddPeer;	// IMP=0x00000001001c6d28
- (id)_removePeers:(id)arg1;	// IMP=0x00000001001c6a64
- (id)_addPeers:(id)arg1;	// IMP=0x00000001001c681c
- (void)_triggerWiFiRanging:(id)arg1;	// IMP=0x00000001001c65d0
- (void)bluetoothAdvertisingAddressChanged:(unsigned long long)arg1;	// IMP=0x00000001001c65b4
- (id)disableAllServices;	// IMP=0x00000001001c64d0
- (id)pause;	// IMP=0x00000001001c63e4
- (id)run;	// IMP=0x00000001001c61d0
- (id)configure;	// IMP=0x00000001001c5d30
- (id)lastConfiguration;	// IMP=0x00000001001c5d20
- (id)initWithResourcesManager:(id)arg1 configuration:(id)arg2 error:(id *)arg3;	// IMP=0x00000001001c59b8

@end

