//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PRBeaconRangingProtocol-Protocol.h"
#import "PRClientProxy-Protocol.h"
#import "PRRangingClientProtocol-Protocol.h"

@class NSDictionary, NSString, PRNSXPCConnection;
@protocol PRRangingClientProtocol;

@interface PRBeaconRangingClientProxy : NSObject <PRClientProxy, PRRangingClientProtocol, PRBeaconRangingProtocol>
{
    PRNSXPCConnection<PRRangingClientProtocol> *_connWrapper;	// 8 = 0x8
    shared_ptr_55175bc8 _rangingManagerClient;	// 16 = 0x10
    NSDictionary *_clientInfo;	// 32 = 0x20
    unsigned short _initiatorTicketId;	// 40 = 0x28
    unsigned short _responderTicketId;	// 42 = 0x2a
    _Bool _terminated;	// 44 = 0x2c
    double _initiationTime;	// 48 = 0x30
    struct map<unsigned long long, double, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<const unsigned long long, double>>> _responders;	// 56 = 0x38
    struct mutex _mapMutex;	// 80 = 0x50
    unsigned short _pointToShareInitiatorServiceId;	// 144 = 0x90
}

- (id).cxx_construct;	// IMP=0x000000010001ef2c
- (void).cxx_destruct;	// IMP=0x000000010001eee0
@property unsigned short pointToShareInitiatorServiceId; // @synthesize pointToShareInitiatorServiceId=_pointToShareInitiatorServiceId;
@property(readonly, copy) NSDictionary *clientInfo; // @synthesize clientInfo=_clientInfo;
- (_Bool)createBeaconListenerJob:(id *)arg1;	// IMP=0x000000010001e878
- (void)disablePTSInitiating:(CDUnknownBlockType)arg1;	// IMP=0x000000010001e14c
- (void)enablePTSInitiating:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001daa8
- (void)clearBeaconWhitelist:(CDUnknownBlockType)arg1;	// IMP=0x000000010001d88c
- (void)pushBeaconWhitelist:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001d0f8
- (void)stopBeaconing:(long long)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ce9c
- (void)startBeaconing:(long long)arg1 options:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001cc14
- (void)rangingRequestDidUpdateStatus:(unsigned long long)arg1;	// IMP=0x000000010001cb04
- (void)rangingServiceDidUpdateState:(unsigned long long)arg1 cause:(long long)arg2;	// IMP=0x000000010001c9f4
- (void)didReceiveNewSolutions:(id)arg1;	// IMP=0x000000010001c670
- (void)didFailWithError:(id)arg1;	// IMP=0x000000010001c504
- (void)terminate;	// IMP=0x000000010001c450
- (void)activate;	// IMP=0x000000010001c29c
- (void)dealloc;	// IMP=0x000000010001c1c0
- (void)connectWithClientInfo:(id)arg1;	// IMP=0x000000010001bffc
- (id)initWithConnection:(id)arg1 queue:(id)arg2;	// IMP=0x000000010001bd74

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

