//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;

@interface SYDSyncTaskMap : NSObject
{
    NSMutableDictionary *_tasksByStoreIdentifierByBundleIdentifier;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010004997c
@property(retain, nonatomic) NSMutableDictionary *tasksByStoreIdentifierByBundleIdentifier; // @synthesize tasksByStoreIdentifierByBundleIdentifier=_tasksByStoreIdentifierByBundleIdentifier;
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *allApplications;
@property(readonly, nonatomic) NSArray *allSyncTasks;
- (void)enumerateSyncTasksWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000492c8
- (id)syncTaskWithBundleIdentifier:(id)arg1 storeIdentifier:(id)arg2;	// IMP=0x0000000100049228
- (void)removeSyncTask:(id)arg1;	// IMP=0x0000000100048e88
- (void)addSyncTask:(id)arg1;	// IMP=0x0000000100048d80
- (id)init;	// IMP=0x0000000100048d1c

@end

