//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PAMediaConversionServiceImageMetadataPolicy.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface PAMediaConversionServiceCompositeImageMetadataPolicy : PAMediaConversionServiceImageMetadataPolicy
{
    NSArray *_policies;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010000864c
+ (id)policyWithPolicies:(id)arg1;	// IMP=0x0000000100008580
- (void).cxx_destruct;	// IMP=0x000000010000856c
@property(retain) NSArray *policies; // @synthesize policies=_policies;
- (id)processMetadata:(id)arg1;	// IMP=0x00000001000083d8
- (_Bool)metadataNeedsProcessing:(id)arg1;	// IMP=0x0000000100008280
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100008208
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100008174

@end

