//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

__attribute__((visibility("hidden")))
@interface PAMediaConversionServiceImageMetadataPolicy : NSObject <NSSecureCoding>
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100007538
+ (id)standardPolicy;	// IMP=0x0000000100007434
- (id)processMetadata:(id)arg1;	// IMP=0x000000010000742c
- (_Bool)metadataNeedsProcessing:(id)arg1;	// IMP=0x0000000100007424
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100007420
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010000741c

@end

