//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SystemDiagnosticLogAgent : NSObject
{
}

+ (_Bool)_runBlock:(CDUnknownBlockType)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100006dcc
+ (id)sharedInstance;	// IMP=0x000000010000447c
- (id)stringForReqType:(long long)arg1;	// IMP=0x0000000100006f34
- (_Bool)getPreferences:(const char *)arg1 withTimeout:(double)arg2;	// IMP=0x0000000100006c48
- (void)writePreferenceInDomain:(id)arg1 withKey:(id)arg2 toDirectory:(const char *)arg3 currentUser:(_Bool)arg4;	// IMP=0x0000000100006958
- (id)getPreferencesforDomain:(id)arg1 withKeys:(id)arg2 currentUser:(_Bool)arg3;	// IMP=0x0000000100006798
- (void)revertToRootMode:(_Bool)arg1;	// IMP=0x000000010000677c
- (void)setUserMode:(_Bool)arg1;	// IMP=0x0000000100006748
- (_Bool)_libNotifyTaskAtLocation:(const char *)arg1 andTimeout:(long long)arg2;	// IMP=0x000000010000661c
- (_Bool)ASPToolTaskForDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100006454
- (_Bool)ASPToolSnapshotForDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x00000001000062bc
- (_Bool)ASPToolGenericWithTimeout:(double)arg1 andBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000061b8
- (id)coreCaptureConfigTask:(double)arg1;	// IMP=0x0000000100005cc8
- (id)_memoryExceptionsTaskWithTimeout:(long long)arg1;	// IMP=0x0000000100005b50
- (id)_powerTaskWithTimeout:(long long)arg1;	// IMP=0x000000010000575c
- (_Bool)coreCaptureTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2 ofType:(int)arg3;	// IMP=0x00000001000050cc
- (long long)_logItemForType:(int)arg1;	// IMP=0x00000001000050b0
- (_Bool)runningBoardTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100004ea4
- (_Bool)timezoneTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100004bc0
- (_Bool)batteryHealthTaskWithDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x000000010000465c
- (_Bool)DSCSYMTaskForDir:(const char *)arg1 WithTimeout:(double)arg2;	// IMP=0x0000000100004528
- (void)processMessage:(id)arg1 replyWith:(id)arg2;	// IMP=0x00000001000044e8

@end

