//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IXAppInstallObserverProtocolInterface : NSObject
{
}

+ (void)configureInterface:(id)arg1;	// IMP=0x000000010004bc34
+ (id)interfaceProtocol;	// IMP=0x000000010004bc28
+ (id)interface;	// IMP=0x000000010004bb4c
+ (id)new;	// IMP=0x000000010004bb34
- (id)init;	// IMP=0x000000010004bb1c

@end

