//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TVPCollectionViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSString, TVPCollectionView, UIScrollView, UIView;

@interface TVPPhotoLibraryCollectionViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, TVPCollectionViewDelegate>
{
    UIView *_loadingView;	// 8 = 0x8
    TVPCollectionView *_photoLibraryCollectionView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100087108
@property(retain, nonatomic) TVPCollectionView *photoLibraryCollectionView; // @synthesize photoLibraryCollectionView=_photoLibraryCollectionView;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
- (void)_dismissLoadingView;	// IMP=0x000000010008702c
- (void)_displayLoadingView;	// IMP=0x0000000100086f30
- (id)_photoLibraryCollectionView;	// IMP=0x0000000100086f20
- (Class)_collectionViewCellClass;	// IMP=0x0000000100086f14
- (Class)_sectionHeaderViewClass;	// IMP=0x0000000100086f08
- (Class)_collectionViewTitleViewClass;	// IMP=0x0000000100086efc
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x0000000100086ea0
- (_Bool)collectionView:(id)arg1 canFocusItemAtIndexPath:(id)arg2;	// IMP=0x0000000100086e98
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100086dd8
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100086d24
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100086d1c
- (id)preferredFocusEnvironments;	// IMP=0x0000000100086c70
- (id)photosDetailsContextForMemory:(id)arg1;	// IMP=0x0000000100086a70
- (void)viewDidLoad;	// IMP=0x0000000100086724
@property(readonly, nonatomic) UIScrollView *ppt_scrollView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

