//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "PXPhotoLibraryUIChangeObserver-Protocol.h"
#import "TVPCollectionViewCachingManagerDataSource-Protocol.h"
#import "TVPCollectionViewDelegate-Protocol.h"
#import "TVPCollectionViewDelegateFlowLayout-Protocol.h"
#import "TVPPhotoLibraryTabbedViewController-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, PHCollectionList, TVPCollectionView, TVPCollectionViewCachingManager, TVPFetchManager, UIView;

@interface TVPPhotoLibraryAlbumsListController : UIViewController <UICollectionViewDataSource, TVPCollectionViewDelegate, PXPhotoLibraryUIChangeObserver, TVPCollectionViewCachingManagerDataSource, TVPCollectionViewDelegateFlowLayout, TVPPhotoLibraryTabbedViewController>
{
    _Bool _needsReload;	// 8 = 0x8
    TVPCollectionView *_albumsListView;	// 16 = 0x10
    UIView *_loadingView;	// 24 = 0x18
    TVPFetchManager *_fetchManager;	// 32 = 0x20
    TVPCollectionViewCachingManager *_cachingManager;	// 40 = 0x28
    NSArray *_albumAssetCollections;	// 48 = 0x30
    PHCollectionList *_defaultCollectionList;	// 56 = 0x38
    NSMutableDictionary *__subCollectionKeyAssetsFetchResults;	// 64 = 0x40
    NSMutableDictionary *__folderCountFetchResults;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x000000010006fde0
@property(nonatomic) _Bool needsReload; // @synthesize needsReload=_needsReload;
@property(readonly, nonatomic) NSMutableDictionary *_folderCountFetchResults; // @synthesize _folderCountFetchResults=__folderCountFetchResults;
@property(readonly, nonatomic) NSMutableDictionary *_subCollectionKeyAssetsFetchResults; // @synthesize _subCollectionKeyAssetsFetchResults=__subCollectionKeyAssetsFetchResults;
@property(retain, nonatomic) PHCollectionList *defaultCollectionList; // @synthesize defaultCollectionList=_defaultCollectionList;
@property(copy, nonatomic) NSArray *albumAssetCollections; // @synthesize albumAssetCollections=_albumAssetCollections;
@property(retain, nonatomic) TVPCollectionViewCachingManager *cachingManager; // @synthesize cachingManager=_cachingManager;
@property(retain, nonatomic) TVPFetchManager *fetchManager; // @synthesize fetchManager=_fetchManager;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) TVPCollectionView *albumsListView; // @synthesize albumsListView=_albumsListView;
- (id)ppt_albumListCollectionView;	// IMP=0x000000010006fcc4
@property(readonly, nonatomic) long long tabMode;
- (id)_albumAtIndexPath:(id)arg1;	// IMP=0x000000010006fc04
- (id)_assetAtIndexPath:(id)arg1;	// IMP=0x000000010006fa80
- (void)_dismissLoadingView;	// IMP=0x000000010006f9ec
- (void)_displayLoadingView;	// IMP=0x000000010006f8f0
- (long long)_assetCountForCollection:(id)arg1;	// IMP=0x000000010006f85c
- (void)_fetchAlbumCollectionsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010006f2f0
- (id)_overlayImageForAlbum:(id)arg1;	// IMP=0x000000010006f224
- (id)collectionViewCachingManager:(id)arg1 assetsForIndexPaths:(id)arg2;	// IMP=0x000000010006f064
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010006edb0
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x000000010006ece0
- (void)_loadFolderCell:(id)arg1 withFolder:(id)arg2;	// IMP=0x000000010006e5a4
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010006e004
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x000000010006dfec
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x000000010006dfa8
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x000000010006df64
- (void)photoLibraryDidChangeOnMainQueue:(id)arg1;	// IMP=0x000000010006d240
- (unsigned long long)_indexOfFavouriteMemoryAlbumInArray:(id)arg1;	// IMP=0x000000010006d0f0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010006d034
- (id)preferredFocusEnvironments;	// IMP=0x000000010006cfac
- (void)dealloc;	// IMP=0x000000010006cf34
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010006ce84
- (void)viewDidLoad;	// IMP=0x000000010006c778
- (id)init;	// IMP=0x000000010006c768
- (id)initWithCollectionList:(id)arg1;	// IMP=0x000000010006c60c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

