//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@class NSTimer;

@interface TVPRestGestureRecognizer : UIGestureRecognizer
{
    _Bool _selectButtonDepressed;	// 8 = 0x8
    int _touchCount;	// 12 = 0xc
    long long _stateToEnter;	// 16 = 0x10
    double _minimumPressDuration;	// 24 = 0x18
    NSTimer *_pressDurationTimer;	// 32 = 0x20
    struct CGPoint _digitizerStartLocation;	// 40 = 0x28
    struct CGPoint _digitizerLocation;	// 56 = 0x38
}

+ (_Bool)_shouldDefaultToTouches;	// IMP=0x0000000100030110
- (void).cxx_destruct;	// IMP=0x000000010003099c
@property(nonatomic) __weak NSTimer *pressDurationTimer; // @synthesize pressDurationTimer=_pressDurationTimer;
@property(nonatomic) double minimumPressDuration; // @synthesize minimumPressDuration=_minimumPressDuration;
@property(readonly, nonatomic) struct CGPoint digitizerLocation; // @synthesize digitizerLocation=_digitizerLocation;
@property(readonly, nonatomic) struct CGPoint digitizerStartLocation; // @synthesize digitizerStartLocation=_digitizerStartLocation;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003091c
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000306c4
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000306c0
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100030544
- (void)recognizeFingerRest;	// IMP=0x00000001000304d0
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000303f0
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100030310
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100030290
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100030118
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x00000001000300b4

@end

