//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSUUID;

@interface TVPSlideshowUtilities : NSObject
{
    long long _mode;	// 8 = 0x8
    NSUUID *_uuid;	// 16 = 0x10
    NSString *_currentTheme;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010008fd64
@property(retain, nonatomic) NSString *currentTheme; // @synthesize currentTheme=_currentTheme;
@property(readonly, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (id)_getRandomizedMarimbaTheme;	// IMP=0x000000010008fb68
- (void)_setTransitionTiming:(double)arg1 marimbaView:(id)arg2;	// IMP=0x000000010008f84c
- (void)logSlideshowDidEndReachingSlideshowEnd:(_Bool)arg1;	// IMP=0x000000010008f710
- (void)logSlideshowDidResume;	// IMP=0x000000010008f628
- (void)logSlideshowDidPause;	// IMP=0x000000010008f540
- (void)logSlideshowDidStartWithAssetCountsByPlaybackStyle:(id)arg1 repeating:(_Bool)arg2 shuffled:(_Bool)arg3 defaultSlideDuration:(double)arg4;	// IMP=0x000000010008f2c0
- (id)alertControllerDisplayingTimePerSlideOptionsForCell:(id)arg1;	// IMP=0x000000010008e94c
- (_Bool)themeHasAdditionalOptions:(id)arg1;	// IMP=0x000000010008e8d4
- (double)timePerSlide;	// IMP=0x000000010008e824
- (void)cleanUpMarimbaResources:(id)arg1;	// IMP=0x000000010008e788
- (void)updateMarimbaView:(id)arg1 transitionTiming:(double)arg2;	// IMP=0x000000010008e4e0
- (void)updateTransitionTimingForMarimbaView:(id)arg1;	// IMP=0x000000010008e4d0
- (void)updateMarimbaView:(id)arg1 currentTheme:(id)arg2 currentTransition:(id)arg3;	// IMP=0x000000010008dd14
- (id)updateMarimbaDocument:(id)arg1 photoAssets:(id)arg2;	// IMP=0x000000010008d7f4
- (id)init;	// IMP=0x000000010008d7a8
- (id)initWithMarimbaMode:(long long)arg1;	// IMP=0x000000010008d72c

@end

