//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UICollectionViewDataSource-Protocol.h"

@class TVPSharedPSCommentsView, UIView;

@protocol TVPSharedPSCommentsViewDataSource <UICollectionViewDataSource>
- (UIView *)headerViewForLikesInCommentsView:(TVPSharedPSCommentsView *)arg1;

@optional
- (UIView *)subHeaderViewInCommentsView:(TVPSharedPSCommentsView *)arg1;
@end

