//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UIScrollViewDelegate-Protocol.h"

@class MTActionButtonContainerView, MTCollectionView, MTUIFocusedTouchGestureRecognizer, NSString, UIButton, UIImageView, UIScrollView, UITapGestureRecognizer, UIView;
@protocol MTCollectionViewCellDelegate;

@interface MTCollectionViewCell : UICollectionViewCell <UIScrollViewDelegate>
{
    UIView *_contentView;	// 8 = 0x8
    UIScrollView *_scrollView;	// 16 = 0x10
    UIImageView *_editingControl;	// 24 = 0x18
    _Bool _editing;	// 32 = 0x20
    _Bool _userSwiping;	// 33 = 0x21
    _Bool _showsMoreButton;	// 34 = 0x22
    id <MTCollectionViewCellDelegate> _delegate;	// 40 = 0x28
    unsigned long long _swipeState;	// 48 = 0x30
    UITapGestureRecognizer *_tapGestureRecognizer;	// 56 = 0x38
    MTUIFocusedTouchGestureRecognizer *_dismissOnTouchRecognizer;	// 64 = 0x40
    MTActionButtonContainerView *_actionButtonsContainer;	// 72 = 0x48
    UIButton *_deleteButton;	// 80 = 0x50
    UIButton *_moreButton;	// 88 = 0x58
}

+ (id)_multiSelectNotSelectedImage;	// IMP=0x0000000100151b00
+ (id)_multiSelectCheckmarkImage;	// IMP=0x0000000100151a58
+ (Class)_contentViewClass;	// IMP=0x0000000100151a4c
+ (double)maximumContentWidth;	// IMP=0x0000000100151a40
+ (double)estimatedHeight;	// IMP=0x0000000100151a34
- (void).cxx_destruct;	// IMP=0x0000000100153f70
@property(nonatomic) _Bool showsMoreButton; // @synthesize showsMoreButton=_showsMoreButton;
@property(nonatomic) _Bool userSwiping; // @synthesize userSwiping=_userSwiping;
@property(retain, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) MTActionButtonContainerView *actionButtonsContainer; // @synthesize actionButtonsContainer=_actionButtonsContainer;
@property(retain, nonatomic) MTUIFocusedTouchGestureRecognizer *dismissOnTouchRecognizer; // @synthesize dismissOnTouchRecognizer=_dismissOnTouchRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) unsigned long long swipeState; // @synthesize swipeState=_swipeState;
@property(nonatomic) __weak id <MTCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
- (double)defaultActionButtonsXOriginForScrollFrame:(struct CGRect)arg1 andActionContainerSize:(struct CGSize)arg2;	// IMP=0x0000000100153e10
- (void)scrollViewExposedDelete;	// IMP=0x0000000100153dc8
- (void)scrollViewHidDelete;	// IMP=0x0000000100153d80
- (double)targetXOffsetForExposedActions;	// IMP=0x0000000100153c40
- (void)hideActionsAnimated:(_Bool)arg1;	// IMP=0x0000000100153b14
- (void)exposeActionsAnimated:(_Bool)arg1;	// IMP=0x0000000100153a90
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;	// IMP=0x00000001001539ac
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x0000000100153628
- (void)removeDismissRecognizer;	// IMP=0x00000001001534e0
- (void)addDismissRecognizer;	// IMP=0x0000000100153470
- (void)dismissDelete:(id)arg1;	// IMP=0x0000000100153434
- (void)setOpen:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001533d0
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x00000001001532a8
- (void)moreButtonTapCancelled:(id)arg1;	// IMP=0x0000000100153228
- (void)moreButtonTapped:(id)arg1;	// IMP=0x0000000100153184
- (void)deleteButtonTapped:(id)arg1;	// IMP=0x0000000100153108
- (id)mt_collectionView;	// IMP=0x0000000100152c4c
@property(readonly, nonatomic) MTCollectionView *collectionView;
- (id)contentView;	// IMP=0x0000000100152b30
- (id)scrollView;	// IMP=0x0000000100152ac4
- (void)layoutSubviews;	// IMP=0x000000010015272c
- (struct CGRect)editingControlRectInBounds:(struct CGRect)arg1;	// IMP=0x0000000100152598
- (struct CGRect)contentRectForEditControlWidth:(double)arg1;	// IMP=0x00000001001524ec
@property(readonly, nonatomic) _Bool exposedActions;
@property(nonatomic, getter=isSwipeEnabled) _Bool swipeEnabled;
- (void)setSelected:(_Bool)arg1;	// IMP=0x000000010015218c
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100152078
- (void)prepareForReuse;	// IMP=0x0000000100151fcc
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000100151e9c
- (void)configureSubviews;	// IMP=0x0000000100151c6c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100151c00

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

