//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTPodcastCell.h"

@class UIView;

@interface MTPodcastPlaylistCell : MTPodcastCell
{
    UIView *_disabledView;	// 24 = 0x18
    _Bool _added;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000d8008
@property(nonatomic, getter=isAdded) _Bool added; // @synthesize added=_added;
- (void)setEnabled:(_Bool)arg1;	// IMP=0x00000001000d7f30
- (void)prepareForReuse;	// IMP=0x00000001000d7ec8
- (void)layoutSubviews;	// IMP=0x00000001000d7db4
- (id)countView;	// IMP=0x00000001000d7dac
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000d7d50

@end

