//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol TVPPlayback><TVPAVFPlayback;

@interface MTTVPlayerManager : NSObject
{
    id <TVPPlayback><TVPAVFPlayback> _player;	// 8 = 0x8
}

+ (id)defaultPlayer;	// IMP=0x00000001000b40f8
+ (id)sharedInstance;	// IMP=0x00000001000b405c
- (void).cxx_destruct;	// IMP=0x00000001000b41cc
@property(retain, nonatomic) id <TVPPlayback><TVPAVFPlayback> player; // @synthesize player=_player;
- (id)init;	// IMP=0x00000001000b4154

@end

