//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ApplicationWorkspaceOperation.h"

@interface ApplicationWorkspaceInstallPlaceholderOperation : ApplicationWorkspaceOperation
{
}

- (id)_download;	// IMP=0x00000001001e1ff8
- (void)runWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001001e1f44
- (_Bool)blocksAppInstallation;	// IMP=0x00000001001e1f3c
- (id)initWithApplicationHandle:(id)arg1 iconData:(id)arg2;	// IMP=0x00000001001e1f08
- (id)initWithApplicationHandle:(id)arg1 forceUpdate:(_Bool)arg2;	// IMP=0x00000001001e1ed4

@end

