//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class NSString, SSPlayInfoRequestContext, SSPlayInfoResponse;

@interface GetPlayInfoOperation : ISOperation
{
    NSString *_clientIdentifierHeader;	// 96 = 0x60
    SSPlayInfoRequestContext *_context;	// 104 = 0x68
    SSPlayInfoResponse *_response;	// 112 = 0x70
    NSString *_userAgent;	// 120 = 0x78
}

- (void)_setResponseForOutput:(id)arg1;	// IMP=0x0000000100092b50
- (void)_setPlayInfoResponse:(id)arg1;	// IMP=0x0000000100092aec
- (void)_failWithError:(id)arg1;	// IMP=0x0000000100092a54
- (id)_copyRequestBody:(id *)arg1;	// IMP=0x00000001000924f0
- (void)run;	// IMP=0x0000000100091ec0
@property(copy) NSString *userAgent;
@property(copy) NSString *clientIdentifierHeader;
@property(readonly) SSPlayInfoResponse *playInfoResponse;
@property(readonly) SSPlayInfoRequestContext *playInfoContext;
- (void)dealloc;	// IMP=0x0000000100091c48
- (id)initWithPlayInfoRequestContext:(id)arg1;	// IMP=0x0000000100091be0

@end

