//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface WiFiManager : NSObject
{
    int _clientType;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    struct __WiFiManagerClient *_wifiClient;	// 24 = 0x18
}

+ (id)sharedWiFiManager;	// IMP=0x00000001001d7fdc
- (id)_wifiInterfaceName;	// IMP=0x00000001001d856c
- (long long)_wifiClientTypeForManagerType:(int)arg1;	// IMP=0x00000001001d8560
- (void *)_wifiClient;	// IMP=0x00000001001d8518
@property int clientType;
@property(readonly) NSString *IPAddress;
- (void)dealloc;	// IMP=0x00000001001d7f84
- (id)init;	// IMP=0x00000001001d7f28

@end

