//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewDiffableDataSource.h>

@class UICollectionView;
@protocol _TVHCollectionViewDiffableDataSourceOverriding;

@interface _TVHCollectionViewDiffableDataSource : UICollectionViewDiffableDataSource
{
    UICollectionView *_collectionView;	// 8 = 0x8
    id <_TVHCollectionViewDiffableDataSourceOverriding> _dataSourceOverrider;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010004a4a0
@property(nonatomic) __weak id <_TVHCollectionViewDiffableDataSourceOverriding> dataSourceOverrider; // @synthesize dataSourceOverrider=_dataSourceOverrider;
@property(readonly, nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 indexPathForIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x0000000100049f50
- (id)indexTitlesForCollectionView:(id)arg1;	// IMP=0x0000000100049efc
- (id)initWithCollectionView:(id)arg1 cellProvider:(CDUnknownBlockType)arg2;	// IMP=0x0000000100049e74

@end

