//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableString.h>

@interface NSMutableString (TVHomeSharing)
- (void)tvh_decodeXMLEntities;	// IMP=0x000000010004e7f0
- (void)tvh_encodeXMLEntities;	// IMP=0x000000010004e6c0
@end

