//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface TVHImageProxyQueueLoader : NSObject
{
    _Bool _randomized;	// 8 = 0x8
    _Bool _paused;	// 9 = 0x9
    NSArray *_imageProxies;	// 16 = 0x10
    unsigned long long _preloadCount;	// 24 = 0x18
    CDUnknownBlockType _preloadCompletionHandler;	// 32 = 0x20
    unsigned long long _nextIndex;	// 40 = 0x28
    NSMutableArray *_pendingImageProxies;	// 48 = 0x30
    NSMutableArray *_loadingImageProxies;	// 56 = 0x38
    NSMutableArray *_finishedImages;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000a5c70
@property(retain, nonatomic) NSMutableArray *finishedImages; // @synthesize finishedImages=_finishedImages;
@property(retain, nonatomic) NSMutableArray *loadingImageProxies; // @synthesize loadingImageProxies=_loadingImageProxies;
@property(retain, nonatomic) NSMutableArray *pendingImageProxies; // @synthesize pendingImageProxies=_pendingImageProxies;
@property(nonatomic) unsigned long long nextIndex; // @synthesize nextIndex=_nextIndex;
@property(copy, nonatomic) CDUnknownBlockType preloadCompletionHandler; // @synthesize preloadCompletionHandler=_preloadCompletionHandler;
@property(nonatomic) unsigned long long preloadCount; // @synthesize preloadCount=_preloadCount;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(nonatomic, getter=isRandomized) _Bool randomized; // @synthesize randomized=_randomized;
@property(copy, nonatomic) NSArray *imageProxies; // @synthesize imageProxies=_imageProxies;
- (void)_checkForPreloadCompletion;	// IMP=0x00000001000a5b80
- (void)_imageProxyDidFail:(id)arg1 withError:(id)arg2;	// IMP=0x00000001000a5a44
- (void)_imageProxyDidLoad:(id)arg1 withImage:(id)arg2;	// IMP=0x00000001000a59a0
- (void)_loadPendingImages;	// IMP=0x00000001000a5620
- (void)_loadPendingImagesIfPossible;	// IMP=0x00000001000a55dc
- (id)_imageProxyToLoadNext;	// IMP=0x00000001000a5528
- (void)_fillQueue;	// IMP=0x00000001000a5438
- (unsigned long long)_currentQueueSize;	// IMP=0x00000001000a53dc
- (id)popNextImage;	// IMP=0x00000001000a533c
- (void)preloadImageCount:(long long)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a52e0
- (void)dealloc;	// IMP=0x00000001000a51e0
- (id)init;	// IMP=0x00000001000a5118

@end

