//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVHMediaEntitiesFetchViewController.h"

#import "TVHMediaEntitiesFetchViewControllerDelegate-Protocol.h"

@class NSString, TVHKMediaEntityIdentifier, TVHMoviesDataStore;

@interface TVHMovieLookupViewController : TVHMediaEntitiesFetchViewController <TVHMediaEntitiesFetchViewControllerDelegate>
{
    TVHKMediaEntityIdentifier *_movieIdentifier;	// 8 = 0x8
    TVHMoviesDataStore *_dataStore;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010004011c
@property(readonly, nonatomic) TVHMoviesDataStore *dataStore; // @synthesize dataStore=_dataStore;
@property(readonly, nonatomic) TVHKMediaEntityIdentifier *movieIdentifier; // @synthesize movieIdentifier=_movieIdentifier;
- (void)_updateDataStoreWithFetchControllerResultSet:(id)arg1;	// IMP=0x0000000100040090
- (void)mediaEntitiesFetchViewController:(id)arg1 updateContentViewController:(id)arg2 withFetchControllerResultSet:(id)arg3;	// IMP=0x0000000100040080
- (id)mediaEntitiesFetchViewController:(id)arg1 contentViewControllerWithFetchControllerResultSet:(id)arg2 sourceMediaEntity:(id)arg3 sourceMediaEntityBackgroundImageInfo:(id)arg4;	// IMP=0x000000010003feb0
- (id)initWithMovieIdentifier:(id)arg1 mediaLibrary:(id)arg2;	// IMP=0x000000010003fd04
- (id)initWithMediaLibrary:(id)arg1 fetchRequests:(id)arg2 mode:(unsigned long long)arg3 sourceMediaEntity:(id)arg4 sourceMediaEntitiesFetchContext:(id)arg5;	// IMP=0x000000010003fc7c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

