//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVHMediaEntitiesFetchViewController.h"

#import "TVHMediaEntitiesFetchViewControllerDelegate-Protocol.h"
#import "TVHMediaEntitiesGridViewControllerDelegate-Protocol.h"

@class NSString, TVHMediaEntitiesGridDataSource, TVHMediaEntitiesGridViewController;

@interface TVHPhotosPlaylistsViewController : TVHMediaEntitiesFetchViewController <TVHMediaEntitiesFetchViewControllerDelegate, TVHMediaEntitiesGridViewControllerDelegate>
{
    unsigned long long _displayType;	// 8 = 0x8
    TVHMediaEntitiesGridViewController *_gridViewController;	// 16 = 0x10
    TVHMediaEntitiesGridDataSource *_gridDataSource;	// 24 = 0x18
    struct CGSize _cellSize;	// 32 = 0x20
}

+ (id)_titleForDisplayType:(unsigned long long)arg1 andSourceFolder:(id)arg2;	// IMP=0x000000010006e870
+ (id)_noContentErrorMessageForMode:(unsigned long long)arg1;	// IMP=0x000000010006e784
- (void).cxx_destruct;	// IMP=0x000000010006eb28
@property(retain, nonatomic) TVHMediaEntitiesGridDataSource *gridDataSource; // @synthesize gridDataSource=_gridDataSource;
@property(retain, nonatomic) TVHMediaEntitiesGridViewController *gridViewController; // @synthesize gridViewController=_gridViewController;
@property(nonatomic) struct CGSize cellSize; // @synthesize cellSize=_cellSize;
@property(nonatomic) unsigned long long displayType; // @synthesize displayType=_displayType;
- (void)_updateWithFetchControllerResultSet:(id)arg1;	// IMP=0x000000010006e994
- (void)mediaEntitiesGridViewController:(id)arg1 didSelectMediaEntity:(id)arg2;	// IMP=0x000000010006e4f4
- (void)mediaEntitiesGridViewController:(id)arg1 configureLockup:(id)arg2 forMediaEntity:(id)arg3;	// IMP=0x000000010006e43c
- (void)mediaEntitiesFetchViewController:(id)arg1 updateContentViewController:(id)arg2 withFetchControllerResultSet:(id)arg3;	// IMP=0x000000010006e42c
- (id)mediaEntitiesFetchViewController:(id)arg1 contentViewControllerWithFetchControllerResultSet:(id)arg2 sourceMediaEntity:(id)arg3 sourceMediaEntityBackgroundImageInfo:(id)arg4;	// IMP=0x000000010006e1d4
- (id)_initWithMediaLibrary:(id)arg1 displayType:(unsigned long long)arg2 sourceFolder:(id)arg3 sourceFoldersFetchContext:(id)arg4;	// IMP=0x000000010006de8c
- (id)initWithMediaLibrary:(id)arg1 displayType:(unsigned long long)arg2 sourceFolder:(id)arg3 sourceFoldersFetchContext:(id)arg4;	// IMP=0x000000010006de04
- (id)initWithMediaLibrary:(id)arg1 displayType:(unsigned long long)arg2;	// IMP=0x000000010006ddf0
- (id)initWithMediaLibrary:(id)arg1 fetchRequests:(id)arg2 mode:(unsigned long long)arg3 sourceMediaEntity:(id)arg4 sourceMediaEntitiesFetchContext:(id)arg5;	// IMP=0x000000010006dd68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

