//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface AMPMusicCatalogContent : PBCodable <NSCopying>
{
    long long _adamId;	// 8 = 0x8
    long long _canonicalId;	// 16 = 0x10
    long long _releaseDate;	// 24 = 0x18
    NSMutableArray *_contentFeatures;	// 32 = 0x20
    int _contentType;	// 40 = 0x28
    _Bool _isExplicit;	// 44 = 0x2c
    struct {
        unsigned int adamId:1;
        unsigned int canonicalId:1;
        unsigned int releaseDate:1;
        unsigned int contentType:1;
        unsigned int isExplicit:1;
    } _has;	// 48 = 0x30
}

+ (Class)contentFeaturesType;	// IMP=0x00000001000ab800
- (void).cxx_destruct;	// IMP=0x00000001000accdc
@property(retain, nonatomic) NSMutableArray *contentFeatures; // @synthesize contentFeatures=_contentFeatures;
@property(nonatomic) _Bool isExplicit; // @synthesize isExplicit=_isExplicit;
@property(nonatomic) long long releaseDate; // @synthesize releaseDate=_releaseDate;
@property(nonatomic) long long canonicalId; // @synthesize canonicalId=_canonicalId;
@property(nonatomic) long long adamId; // @synthesize adamId=_adamId;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000aca6c
- (unsigned long long)hash;	// IMP=0x00000001000ac988
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000ac808
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000ac5c0
- (void)copyTo:(id)arg1;	// IMP=0x00000001000ac41c
- (void)writeTo:(id)arg1;	// IMP=0x00000001000ac234
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000ac22c
- (id)dictionaryRepresentation;	// IMP=0x00000001000ab8c0
- (id)description;	// IMP=0x00000001000ab80c
- (id)contentFeaturesAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000ab7e8
- (unsigned long long)contentFeaturesCount;	// IMP=0x00000001000ab7d0
- (void)addContentFeatures:(id)arg1;	// IMP=0x00000001000ab75c
- (void)clearContentFeatures;	// IMP=0x00000001000ab744
@property(nonatomic) _Bool hasIsExplicit;
@property(nonatomic) _Bool hasReleaseDate;
@property(nonatomic) _Bool hasCanonicalId;
@property(nonatomic) _Bool hasAdamId;
- (int)StringAsContentType:(id)arg1;	// IMP=0x00000001000ab4f0
- (id)contentTypeAsString:(int)arg1;	// IMP=0x00000001000ab454
@property(nonatomic) _Bool hasContentType;
@property(nonatomic) int contentType; // @synthesize contentType=_contentType;

@end

