//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "JaliscoImporter.h"

@class ICDJaliscoMediaFilter, NSArray;
@protocol ICDJaliscoSupportedMediaKindsHandler;

@interface JaliscoMediaImporter : JaliscoImporter
{
    ICDJaliscoMediaFilter *_mediaFilter;	// 8 = 0x8
    NSArray *_supportedMediaKinds;	// 16 = 0x10
    id <ICDJaliscoSupportedMediaKindsHandler> _supportedMediaKindsHandler;	// 24 = 0x18
}

+ (id)oversizeLogCategory;	// IMP=0x00000001000bbf74
+ (id)logCategory;	// IMP=0x00000001000bbf6c
- (void).cxx_destruct;	// IMP=0x00000001000be178
- (id)_supportedMediaKindsDatabasePropertyValue;	// IMP=0x00000001000be0f4
- (id)_importTracksFromRevision:(unsigned int)arg1 toRevision:(unsigned int)arg2 withItemsResponse:(id)arg3;	// IMP=0x00000001000bd36c
- (id)_chapterArtworkURLsForData:(id)arg1 baseURL:(id)arg2;	// IMP=0x00000001000bcff0
- (id)_chapterDataFromURL:(id)arg1;	// IMP=0x00000001000bcf60
- (id)updateLibraryFromRevision:(unsigned int)arg1 toRevision:(unsigned int)arg2 withResponse:(id)arg3;	// IMP=0x00000001000bceb0
- (void)clearNeedsUpdateForTokens;	// IMP=0x00000001000bce6c
- (_Bool)needsUpdateForTokens;	// IMP=0x00000001000bcc80
- (id)supportedMediaKinds;	// IMP=0x00000001000bcc00
- (id)metadataKeys;	// IMP=0x00000001000bc654
- (id)purchaseTokens;	// IMP=0x00000001000bc26c
- (id)queryFilter;	// IMP=0x00000001000bc218
- (id)mediaFilter;	// IMP=0x00000001000bc154
- (unsigned int)onDiskRevision;	// IMP=0x00000001000bc108
- (void)cancel;	// IMP=0x00000001000bc014
- (id)initWithConnection:(id)arg1 supportedMediaKindsHandler:(id)arg2;	// IMP=0x00000001000bbf7c

@end

