//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface iAP2Localize : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x0000000100075108
- (id)CopyLocalizedString:(id)arg1;	// IMP=0x0000000100075474
- (id)GetLocalizationInfoFromInfoType:(int)arg1;	// IMP=0x0000000100075374
- (id)GetLocalizedStringFromPropertyID:(int)arg1;	// IMP=0x000000010007517c
- (void)dealloc;	// IMP=0x00000001000750d4
- (id)init;	// IMP=0x00000001000750a0

@end

