//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "iAP2FileTransferRecvDelegate-Protocol.h"
#import "iAP2FileTransferSendDelegate-Protocol.h"

@class NSMutableDictionary, NSTimer, iAP2AppLaunchController, iAP2AuthenticationController, iAP2FileTransferManager, iAP2FileTransferRecv, iAP2HIDManager, iAP2IdentificationInfo, iAP2MediaLibrary, iAP2MsgAssistiveTouch, iAP2MsgBTPairing, iAP2MsgCamera, iAP2MsgCarPlayStatusNotification, iAP2MsgDestinationSharing, iAP2MsgDigitalAudio, iAP2MsgLocation, iAP2MsgNavigation, iAP2MsgOOBBTPairing, iAP2MsgSiri, iAP2MsgUSBHostMode, iAP2MsgVehicleStatus, iAP2MsgVoiceOver, iAP2MsgWifi, iAP2NowPlaying, iAP2Port, iAP2PowerUpdates, iAP2Session;
@protocol OS_dispatch_queue;

@interface iAP2Connection : NSObject <iAP2FileTransferSendDelegate, iAP2FileTransferRecvDelegate>
{
    iAP2MediaLibrary *_mediaLibrary;	// 8 = 0x8
    iAP2NowPlaying *_nowPlaying;	// 16 = 0x10
    iAP2MsgWifi *_msgWifi;	// 24 = 0x18
    iAP2MsgLocation *_msgLocation;	// 32 = 0x20
    iAP2MsgCamera *_msgCamera;	// 40 = 0x28
    iAP2MsgVehicleStatus *_msgVehicleStatus;	// 48 = 0x30
    iAP2MsgDigitalAudio *_msgDigitalAudio;	// 56 = 0x38
    iAP2HIDManager *_iap2hidManager;	// 64 = 0x40
    iAP2IdentificationInfo *_IdentificationInfo;	// 72 = 0x48
    NSMutableDictionary *_AccessoryDictionary;	// 80 = 0x50
    iAP2PowerUpdates *_powerUpdates;	// 88 = 0x58
    iAP2MsgAssistiveTouch *_assistiveTouch;	// 96 = 0x60
    iAP2MsgVoiceOver *_voiceOver;	// 104 = 0x68
    iAP2MsgSiri *_siri;	// 112 = 0x70
    iAP2MsgDestinationSharing *_msgDestinationSharing;	// 120 = 0x78
    iAP2MsgOOBBTPairing *_msgOOBBTPairing;	// 128 = 0x80
    iAP2MsgNavigation *_msgNavigation;	// 136 = 0x88
    iAP2MsgUSBHostMode *_msgUSBHostMode;	// 144 = 0x90
    iAP2MsgBTPairing *_msgBTPairing;	// 152 = 0x98
    iAP2MsgCarPlayStatusNotification *_msgCarPlayStatusNotification;	// 160 = 0xa0
    int _identificationState;	// 168 = 0xa8
    NSTimer *_identifyTimer;	// 176 = 0xb0
    struct __CFUserNotification *_accessoryNotSupportedAlert;	// 184 = 0xb8
    struct __CFUserNotification *_noAppForAccessoryAlert;	// 192 = 0xc0
    CDUnknownFunctionPointerType _callbackForNoAppForAccessory;	// 200 = 0xc8
    _Bool _findAppForAccessoryAlertDelayedForLockScreen;	// 208 = 0xd0
    iAP2FileTransferRecv *_testRecvFile;	// 216 = 0xd8
    double _authStartedTime;	// 224 = 0xe0
    double _authSucceededTime;	// 232 = 0xe8
    _Bool _isInList;	// 240 = 0xf0
    _Bool _shuttingDown;	// 241 = 0xf1
    _Bool _failed;	// 242 = 0xf2
    unsigned char _ControlSessionVersion;	// 243 = 0xf3
    unsigned int _magic;	// 244 = 0xf4
    unsigned int _connectionID;	// 248 = 0xf8
    iAP2Port *_port;	// 256 = 0x100
    NSObject<OS_dispatch_queue> *_serializeQ;	// 264 = 0x108
    iAP2Session *_controlSession;	// 272 = 0x110
    iAP2AuthenticationController *_authStatus;	// 280 = 0x118
    iAP2AppLaunchController *_appLaunchController;	// 288 = 0x120
    CDStruct_7e3aad02 *accessoryPowerManager;	// 296 = 0x128
    NSMutableDictionary *_serviceTests;	// 304 = 0x130
    iAP2FileTransferManager *_fileTransferManager;	// 312 = 0x138
}

+ (void)handleWakeUp;	// IMP=0x00000001000196ec
+ (void)handleGoToSleep;	// IMP=0x0000000100019400
+ (unsigned int)activeHIDDescriptorCountForAllConnections;	// IMP=0x0000000100019208
+ (id)connectedAccessories;	// IMP=0x0000000100018fcc
+ (id)ConnectionFromID:(unsigned int)arg1;	// IMP=0x0000000100018e8c
+ (void)ConnectionListPerformAsync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100018dec
+ (void)ConnectionListPerform:(CDUnknownBlockType)arg1;	// IMP=0x0000000100018d30
@property(readonly, nonatomic) iAP2FileTransferManager *fileTransferManager; // @synthesize fileTransferManager=_fileTransferManager;
@property(readonly, nonatomic) unsigned char ControlSessionVersion; // @synthesize ControlSessionVersion=_ControlSessionVersion;
@property(readonly, nonatomic) double authSucceededTime; // @synthesize authSucceededTime=_authSucceededTime;
@property(readonly, nonatomic) double authStartedTime; // @synthesize authStartedTime=_authStartedTime;
@property(retain, nonatomic) iAP2FileTransferRecv *TestRecvFile; // @synthesize TestRecvFile=_testRecvFile;
@property(readonly, nonatomic) NSMutableDictionary *ServiceTests; // @synthesize ServiceTests=_serviceTests;
@property(nonatomic) int identificationState; // @synthesize identificationState=_identificationState;
@property(readonly, nonatomic) CDStruct_7e3aad02 *accessoryPowerManager; // @synthesize accessoryPowerManager;
@property(readonly, nonatomic) iAP2AuthenticationController *AuthStatus; // @synthesize AuthStatus=_authStatus;
@property(readonly, nonatomic) iAP2Session *ControlSession; // @synthesize ControlSession=_controlSession;
@property(readonly, nonatomic) _Bool Failed; // @synthesize Failed=_failed;
@property(readonly, nonatomic) _Bool ShuttingDown; // @synthesize ShuttingDown=_shuttingDown;
@property(readonly, nonatomic) _Bool IsInList; // @synthesize IsInList=_isInList;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *SerializeQ; // @synthesize SerializeQ=_serializeQ;
@property(readonly, nonatomic) iAP2Port *Port; // @synthesize Port=_port;
@property(readonly, nonatomic) unsigned int ConnectionID; // @synthesize ConnectionID=_connectionID;
@property(readonly, nonatomic) unsigned int Magic; // @synthesize Magic=_magic;
- (_Bool)isOOBBTPairingSupported;	// IMP=0x000000010001dd8c
- (_Bool)shouldRequestUserAuthorization;	// IMP=0x000000010001dd38
- (_Bool)isCarPlaySupported;	// IMP=0x000000010001dbe8
- (_Bool)isCarPlaySupportedOverWiFi;	// IMP=0x000000010001db58
- (_Bool)isCarPlaySupportedOverUSB;	// IMP=0x000000010001da90
- (void)postNoAppForAccessoryAlertWithCallback:(CDUnknownFunctionPointerType)arg1;	// IMP=0x000000010001d93c
- (void)tearDownFindAppForAccessoryAlert;	// IMP=0x000000010001d8dc
- (void)_shouldPostNoAppAlertIfHoldSwitchOff;	// IMP=0x000000010001d878
- (void)postAccessoryNotSupportedNotification;	// IMP=0x000000010001d7f8
- (int)checkIdentificationInfo:(id)arg1;	// IMP=0x000000010001d710
- (void)processAuthChangeNotification:(id)arg1;	// IMP=0x000000010001d57c
- (void)processDeviceTimeNotifications:(id)arg1;	// IMP=0x000000010001d4ec
- (void)processDeviceStateNotifications:(id)arg1;	// IMP=0x000000010001d440
- (void)unregisterForSystemNotifications;	// IMP=0x000000010001d3bc
- (void)registerForSystemNotifications;	// IMP=0x000000010001d328
- (long long)EventNotify:(int)arg1 param:(void *)arg2;	// IMP=0x000000010001d318
- (_Bool)fileTransferRecvDidTiemout:(id)arg1;	// IMP=0x000000010001d238
- (_Bool)fileTransferRecv:(id)arg1 didFinish:(_Bool)arg2;	// IMP=0x000000010001d1a4
- (_Bool)fileTransferRecv:(id)arg1 didGetBuff:(id)arg2 soFar:(unsigned long long)arg3 outOf:(unsigned long long)arg4;	// IMP=0x000000010001cf4c
- (_Bool)fileTransferSendDidTimeout:(id)arg1;	// IMP=0x000000010001ce74
- (_Bool)fileTransferSendDidSend:(id)arg1;	// IMP=0x000000010001cc08
@property(readonly, nonatomic) _Bool HasActiveMsgBTPairing;
@property(readonly, nonatomic) _Bool IsNavigationFeatureSupported;
@property(readonly, nonatomic) _Bool IsCameraFeatureSupported;
@property(readonly, nonatomic) _Bool IsOOBBTPairingSupported;
@property(readonly, nonatomic) _Bool DoesAccessorySupportAccessibility;
@property(readonly, nonatomic) _Bool IsSupportedUSBHostMode;
- (_Bool)IsSupportedCCK;	// IMP=0x000000010001c9c4
@property(readonly, nonatomic) _Bool IsSupportedUSBAudioOut;
@property(readonly, nonatomic) _Bool IsSupportedIPodOut;
- (_Bool)SendDataForSession:(unsigned char)arg1 Data:(char *)arg2 Len:(unsigned int)arg3 andNotify:(CDUnknownBlockType)arg4 withContext:(void *)arg5 onQueue:(id)arg6;	// IMP=0x000000010001c710
- (_Bool)SendDataForSession:(unsigned char)arg1 Data:(char *)arg2 Len:(unsigned int)arg3;	// IMP=0x000000010001c614
- (_Bool)ProcessTestSession:(unsigned char)arg1 Data:(char *)arg2 Len:(unsigned int)arg3;	// IMP=0x000000010001c514
- (_Bool)ProcessEASession:(unsigned char)arg1 Data:(char *)arg2 Len:(unsigned int)arg3;	// IMP=0x000000010001c440
- (_Bool)ProcessBufferSession:(unsigned char)arg1 Data:(char *)arg2 Len:(unsigned int)arg3;	// IMP=0x000000010001c3cc
- (_Bool)ProcessControlSession:(unsigned char)arg1 Data:(char *)arg2 Len:(unsigned int)arg3;	// IMP=0x000000010001c204
- (id)MainQueue;	// IMP=0x000000010001c1ec
- (unsigned char)sessionVersionForID:(unsigned char)arg1;	// IMP=0x000000010001c1ac
- (unsigned char)sessionIDForServiceType:(int)arg1;	// IMP=0x000000010001c178
- (int)serviceTypeForSessionID:(unsigned char)arg1;	// IMP=0x000000010001c13c
- (struct iAP2Link_st *)iAP2Link;	// IMP=0x000000010001c0ec
- (void)connectionFailed;	// IMP=0x000000010001c054
- (void)connectionDown;	// IMP=0x000000010001bf28
- (void)setIsShuttingDown;	// IMP=0x000000010001bf1c
- (void)_connectionShutdown;	// IMP=0x000000010001b6f4
- (void)SetupSessionsAfterIdentification;	// IMP=0x000000010001b558
- (void)SetupSessionsAfterLinkInitialization;	// IMP=0x000000010001b160
- (void)IAP2TimeSyncResetKalmanFilter;	// IMP=0x000000010001b0a8
- (void)IAP2TimeSyncInfoDictPerformBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010001ae80
- (void)IAP2TimeSyncSetParamsThreshold:(unsigned long long)arg1 interval:(unsigned int)arg2;	// IMP=0x000000010001ada4
- (void)SetNotInListShuttingDown;	// IMP=0x000000010001ad98
@property(readonly, nonatomic) iAP2AppLaunchController *appLaunchController; // @synthesize appLaunchController=_appLaunchController;
@property(readonly, nonatomic) iAP2HIDManager *IAP2HIDManager;
@property(readonly, nonatomic) iAP2NowPlaying *NowPlaying;
@property(readonly, nonatomic) iAP2MediaLibrary *MediaLibrary;
@property(readonly, nonatomic) iAP2MsgWifi *MsgWifi;
@property(readonly, nonatomic) iAP2MsgCamera *MsgCamera;
@property(readonly, nonatomic) iAP2MsgLocation *MsgLocation;
@property(readonly, nonatomic) iAP2MsgVehicleStatus *MsgVehicleStatus;
@property(readonly, nonatomic) iAP2MsgDigitalAudio *MsgDigitalAudio;
- (void)ClearIdentificationInfo;	// IMP=0x000000010001a6dc
@property(readonly, nonatomic) iAP2IdentificationInfo *IdentificationInfo;
@property(readonly, nonatomic) NSMutableDictionary *AccessoryDictionary;
@property(readonly, nonatomic) iAP2PowerUpdates *PowerUpdates;
@property(readonly, nonatomic) iAP2MsgAssistiveTouch *MsgAssistiveTouch;
@property(readonly, nonatomic) iAP2MsgVoiceOver *MsgVoiceOver;
@property(readonly, nonatomic) iAP2MsgBTPairing *MsgBTPairing;
@property(readonly, nonatomic) iAP2MsgUSBHostMode *MsgUSBHostMode;
@property(readonly, nonatomic) iAP2MsgCarPlayStatusNotification *MsgCarPlayStatusNotification;
@property(readonly, nonatomic) iAP2MsgNavigation *MsgNavigation;
@property(readonly, nonatomic) iAP2MsgOOBBTPairing *MsgOOBBTPairing;
@property(readonly, nonatomic) iAP2MsgDestinationSharing *MsgDestinationSharing;
@property(readonly, nonatomic) iAP2MsgSiri *MsgSiri;
- (id)getiAP2Feature:(id *)arg1 allocBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019ec4
- (id)description;	// IMP=0x0000000100019df0
- (void)_changeListenerQueuePriorityStop:(id)arg1;	// IMP=0x0000000100019dac
- (void)_changeListenerQueuePriorityHigh:(id)arg1;	// IMP=0x0000000100019cfc
- (void)dealloc;	// IMP=0x0000000100019c20
- (id)initWithPort:(id)arg1;	// IMP=0x0000000100019890

@end

