//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, iAP2Connection;

@interface iAP2MsgUSBHostMode : NSObject
{
    iAP2Connection *_pkConnection;	// 8 = 0x8
    struct IONotificationPort *_ioNotifyPortMaster;	// 16 = 0x10
    struct __CFRunLoopSource *_ioAccMgrRunLoopSrc;	// 24 = 0x18
    int _ioAccUsbConnType;	// 32 = 0x20
    unsigned int _ioAccNotification;	// 36 = 0x24
    unsigned int _ioAccService;	// 40 = 0x28
    NSMutableDictionary *_usbFaultStates;	// 48 = 0x30
    NSMutableDictionary *_usbFaultStatesSent;	// 56 = 0x38
    NSMutableDictionary *_requestedUSBFaultNotifications;	// 64 = 0x40
    struct IONotificationPort *_ioUSBCardReaderNotifyPort;	// 72 = 0x48
    unsigned int _ioUSBCardReaderNotification;	// 80 = 0x50
    unsigned int _ioUSBCardReaderService;	// 84 = 0x54
    unsigned int _ioUSBCardReaderMatchIterator;	// 88 = 0x58
    unsigned int _ioUSBCardReaderTerminateIterator;	// 92 = 0x5c
    struct IONotificationPort *_ioIOResourceNotifyPort;	// 96 = 0x60
    unsigned int _ioIOResourceNotification;	// 104 = 0x68
    unsigned int _ioIOResourceService;	// 108 = 0x6c
    unsigned int _ioIOResourceMatchIterator;	// 112 = 0x70
    unsigned int _ioIOResourceTerminateIterator;	// 116 = 0x74
    unsigned long long _uid;	// 120 = 0x78
    struct IONotificationPort *_ioUSB30XHCIRemovablePortNotifyPort;	// 128 = 0x80
    unsigned int _ioUSB30XHCIRemovablePortNotification;	// 136 = 0x88
    unsigned int _ioUSB30XHCIRemovablePortService;	// 140 = 0x8c
    unsigned int _ioUSB30XHCIRemovablePortMatchIterator;	// 144 = 0x90
    unsigned int _ioUSB30XHCIRemovablePortTerminateIterator;	// 148 = 0x94
}

- (void)checkUSBCardReaderProperty:(unsigned int)arg1;	// IMP=0x000000010000997c
- (void)initFaultConditionNotifications;	// IMP=0x0000000100009360
- (void)cleanupUSB30XHCIRemovablePortNotifications;	// IMP=0x00000001000092f4
- (void)initUSB30XHCIRemovablePortNotifications;	// IMP=0x0000000100008d40
- (void)initIOResourceNotifications;	// IMP=0x0000000100008858
- (id)description;	// IMP=0x0000000100008800
- (void)addFaultNotification:(int)arg1;	// IMP=0x0000000100008794
- (_Bool)getFaultState:(int)arg1;	// IMP=0x0000000100008748
- (void)setFaultState:(int)arg1 flag:(_Bool)arg2;	// IMP=0x0000000100008688
- (int)sendUSBModeNotification;	// IMP=0x00000001000084b4
- (int)stopUSBHostMode;	// IMP=0x0000000100008410
- (int)startUSBHostMode;	// IMP=0x000000010000836c
- (_Bool)usbHostModeFromConnectType:(int)arg1;	// IMP=0x0000000100008360
- (void)shuttingDown;	// IMP=0x0000000100008314
- (void)dealloc;	// IMP=0x0000000100008148
- (id)initWithConnection:(id)arg1;	// IMP=0x0000000100007cd8

@end

